#!/usr/bin/env python3
"""Deterministically rebuild Docs/PROJECT_ROOT_BIBLES_COMBINED.md."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "Docs" / "PROJECT_ROOT_BIBLES_COMBINED.md"

SOURCE_FILES = [
    "ai.md",
    "animation.md",
    "data.md",
    "persistence.md",
    "physics.md",
    "PROCEDURAL_ASSET_PIPELINE.md",
    "rendering.md",
    "streaming.md",
    "systems.md",
    "vehicles.md",
    "voxels.md",
    "PROJECT_BIBLES.md",
    "celestial.md",
    "bootstrap.md",
    "camera.md",
    "combat.md",
    "lighting.md",
    "localization.md",
    "settings.md",
    "shaders.md",
    "terrain.md",
    "UI_DIEGETIC_HUD_STANDARDS.md",
    "UI_MENU_SCREEN_STANDARDS.md",
    "vfx.md",
    "cinematics.md",
    "drones.md",
    "ecosystem.md",
    "logistics.md",
    "sonar.md",
    "xr.md",
    "3DMODEL_FAUNA.md",
    "quality.md",
    "textes.md",
    "AGENTS.md",
    "TASTE.md",
    "VISION_LOCKS.md",
    "input.md",
    "inventory.md",
    "testing.md",
    "atmosphere.md",
    "authoring.md",
    "compute.md",
    "networking.md",
    "performance.md",
    "survival.md",
    "3DMODEL_FLORA_CORAL.md",
    "3DMODEL_HERO_REALISM_OVERKILL.md",
    "3DMODEL_TEXTURES_MATERIALS.md",
    "3DMODEL_EQUIPMENT_PROPS.md",
    "3DMODEL_GEOLOGY_ROCKS.md",
    "modding.md",
    "platform.md",
    "math.md",
    "release.md",
    "telemetry.md",
    "accessibility.md",
    "3DMODEL_HARD_SURFACE_MODULES.md",
    "water.md",
    "audio.md",
    "gameplay.md",
    "ui.md",
    "world.md",
    "construction.md",
    "creatures.md",
    "narrative.md",
    "writing.md",
    "player.md",
    "presentation.md",
    "tools.md",
    "3dmodel.md",
    "3DMODEL_TEXTURE_GENERATION_PLAYBOOK.md",
]


def normalize_text(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").rstrip("\n")


def source_anchor(index: int, source_file: str) -> str:
    slug = source_file.lower().replace(".", "-").replace("/", "-").replace(" ", "-")
    return f"{index:02d}---{slug}"


def read_source(source_file: str) -> str:
    path = ROOT / source_file
    if not path.is_file():
        raise FileNotFoundError(f"Missing source file: {source_file}")
    return normalize_text(path.read_text(encoding="utf-8-sig"))


def build_document() -> str:
    lines: list[str] = [
        "# HECTON-8 Combined Root Documentation",
        "",
        "Status: GENERATED_SNAPSHOT / STATIC_DOC / RUNTIME_PROOF_NOT_IMPLIED",
        "Evidence class: STATIC_DOC",
        "Generated by: `Tools/Docs/BuildProjectRootBiblesCombined.py`",
        "Do not hand-edit this file. Regenerate it from the explicit source list in the generator.",
        "Freshness boundary: this concatenated snapshot is a convenience copy only. Live root source files routed by `PROJECT_BIBLES.md` remain binding if this file becomes stale.",
        "Source policy: explicit root sources only. Reports, task logs, status files, archives, deprecated docs, generated evidence, and edited AGENTS derivatives are excluded. `AGENTS.md` is included read-only because the previous combined index already selected it as root authority.",
        "",
        "## Source Index",
        "",
    ]

    for index, source_file in enumerate(SOURCE_FILES, start=1):
        lines.append(f"{index}. [{source_file}](#{source_anchor(index, source_file)})")

    lines.append("")
    lines.append("---")

    for index, source_file in enumerate(SOURCE_FILES, start=1):
        lines.append("")
        lines.append(f"## {index:02d} - {source_file}")
        lines.append("")
        lines.append(f"Source: `{source_file}`")
        lines.append("")
        lines.append(read_source(source_file))

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild the combined root bibles snapshot deterministically."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero if the output file differs from generated content.",
    )
    args = parser.parse_args()

    generated = build_document()

    if args.check:
        current = normalize_text(OUTPUT.read_text(encoding="utf-8-sig")) if OUTPUT.is_file() else ""
        expected = generated.rstrip("\n")
        if current == expected:
            return 0

        print(f"{OUTPUT}: generated snapshot differs from live root docs")
        diff = difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=str(OUTPUT),
            tofile="generated",
            lineterm="",
            n=3,
        )
        for index, line in enumerate(diff):
            if index >= 80:
                print("... diff truncated; regenerate with Tools/Docs/BuildProjectRootBiblesCombined.py")
                break
            print(line)
        return 1

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
