using Unity.Jobs;
using UnityEngine;

namespace Hecton8.Physics
{
    public enum RuntimePhysicsBakeCommitPhase1609 : byte
    {
        Invalid = 0,
        PostSimulation = 1,
        VisualSync = 2
    }

    /// <summary>
    /// Runtime handoff component for prefabs whose low-poly collision mesh is baked off the main simulation path.
    /// The component is data-only until an owner schedules <see cref="RuntimePhysicsBakeJob1609"/> and commits after simulation.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class RuntimePhysicsBaker1609 : MonoBehaviour
    {
        [Header("Bake Target")]
        [Tooltip("Low-poly COL_ proxy mesh generated by the offline collider optimizer.")]
        [SerializeField] private Mesh collisionProxyMesh;

        [Tooltip("MeshCollider that receives the baked COL_ mesh only after the bake job has completed.")]
        [SerializeField] private MeshCollider targetCollider;

        [Tooltip("Primitive fallback collider that keeps the prefab blocking while the COL_ mesh bake is pending.")]
        [SerializeField] private BoxCollider bootstrapProxyCollider;

        [Tooltip("Whether the COL_ mesh should be baked and committed as a convex collider.")]
        [SerializeField] private bool convex = true;

        [Tooltip("Cooking options used by the dispatcher bake job and the target MeshCollider.")]
        [SerializeField] private MeshColliderCookingOptions cookingOptions =
            MeshColliderCookingOptions.CookForFasterSimulation |
            MeshColliderCookingOptions.EnableMeshCleaning |
            MeshColliderCookingOptions.WeldColocatedVertices;

        [SerializeField, HideInInspector] private byte lastCommitPhase;
        [SerializeField, HideInInspector] private ulong cachedCollisionProxyMeshKey;

        private EntityId cachedCollisionProxyMeshEntityId;

        /// <summary>Gets the low-poly mesh selected by offline authoring.</summary>
        public Mesh CollisionProxyMesh => collisionProxyMesh;

        /// <summary>Gets the target collider selected by offline authoring.</summary>
        public MeshCollider TargetCollider => targetCollider;

        /// <summary>Gets the primitive fallback collider selected by offline authoring.</summary>
        public BoxCollider BootstrapProxyCollider => bootstrapProxyCollider;

        /// <summary>Gets whether the mesh should be baked as convex.</summary>
        public bool Convex => convex;

        /// <summary>Gets the mesh cooking options selected during offline authoring.</summary>
        public MeshColliderCookingOptions CookingOptions => cookingOptions;

        /// <summary>Gets the last accepted commit phase as a byte for allocation-free diagnostics.</summary>
        public byte LastCommitPhase => lastCommitPhase;

        /// <summary>Gets the cached mesh entity key resolved during cold setup.</summary>
        public ulong CachedCollisionProxyMeshKey => cachedCollisionProxyMeshKey;

        private void OnEnable()
        {
            RefreshBakeIdentityCold();
        }

        /// <summary>
        /// Authoring-only configuration entry used by Editor tools. It performs no bake and no scene search.
        /// </summary>
        public void ConfigureAuthoring(
            Mesh proxyMesh,
            MeshCollider collider,
            BoxCollider bootstrapProxy,
            bool bakeConvex,
            MeshColliderCookingOptions bakeCookingOptions)
        {
            collisionProxyMesh = proxyMesh;
            targetCollider = collider;
            bootstrapProxyCollider = bootstrapProxy;
            convex = bakeConvex;
            cookingOptions = bakeCookingOptions;
            RefreshBakeIdentityCold();
        }

        /// <summary>
        /// Cold identity refresh for authoring/import/bootstrap. Dispatcher read accessors must not call Unity object identity APIs.
        /// </summary>
        public void RefreshBakeIdentityCold()
        {
            cachedCollisionProxyMeshEntityId = collisionProxyMesh != null ? collisionProxyMesh.GetEntityId() : default;
            cachedCollisionProxyMeshKey = EntityId.ToULong(cachedCollisionProxyMeshEntityId);
        }

        /// <summary>
        /// Pure read accessor for dispatcher owners that schedule the bake.
        /// </summary>
        public bool TryResolveBakeRequest(
            out EntityId meshEntityId,
            out bool bakeConvex,
            out MeshColliderCookingOptions bakeCookingOptions,
            out MeshCollider collider)
        {
            collider = targetCollider;
            bakeConvex = convex;
            bakeCookingOptions = cookingOptions;
            meshEntityId = cachedCollisionProxyMeshEntityId;
            ulong meshKey = EntityId.ToULong(meshEntityId);
            return collider != null &&
                   collisionProxyMesh != null &&
                   cachedCollisionProxyMeshKey != 0ul &&
                   meshKey == cachedCollisionProxyMeshKey;
        }

        /// <summary>
        /// Applies the already-baked proxy mesh to the target collider. Call from POST_SIMULATION or VISUAL_SYNC only.
        /// </summary>
        public bool CommitBakedCollider(RuntimePhysicsBakeCommitPhase1609 phase)
        {
            if (!IsCommitPhaseAllowed(phase))
                return false;

            if (targetCollider == null ||
                collisionProxyMesh == null ||
                cachedCollisionProxyMeshKey == 0ul ||
                EntityId.ToULong(cachedCollisionProxyMeshEntityId) != cachedCollisionProxyMeshKey)
                return false;

            targetCollider.cookingOptions = cookingOptions;
            targetCollider.sharedMesh = collisionProxyMesh;
            targetCollider.convex = convex;
            targetCollider.enabled = true;

            if (bootstrapProxyCollider != null)
                bootstrapProxyCollider.enabled = false;

            lastCommitPhase = (byte)phase;
            return true;
        }

        /// <summary>
        /// Phase gate for dispatcher owners. Pure and allocation-free.
        /// </summary>
        public static bool IsCommitPhaseAllowed(RuntimePhysicsBakeCommitPhase1609 phase)
        {
            return phase == RuntimePhysicsBakeCommitPhase1609.PostSimulation ||
                   phase == RuntimePhysicsBakeCommitPhase1609.VisualSync;
        }
    }

    /// <summary>
    /// Async bake request. Scheduling and completion ownership belong to the physics dispatcher.
    /// </summary>
    public struct RuntimePhysicsBakeJob1609 : IJob
    {
        public EntityId MeshEntityId;
        public bool Convex;
        public MeshColliderCookingOptions CookingOptions;

        public void Execute()
        {
            if (EntityId.ToULong(MeshEntityId) != 0ul)
                UnityEngine.Physics.BakeMesh(MeshEntityId, Convex, CookingOptions);
        }
    }
}
