using UnityEngine;

namespace Hecton8.Physics
{
    public enum RuntimePhysicsBakeCommitPhase1609 : byte
    {
        Invalid = 0,
        PostSimulation = 1,
        VisualSync = 2
    }

    /// <summary>
    /// Legacy authoring component for prefabs that already carry an offline-authored COL_ mesh.
    /// Runtime mesh cooking is forbidden; this component only verifies prebound collider identity.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class RuntimePhysicsBaker1609 : MonoBehaviour
    {
        [Header("Offline Proxy Target")]
        [Tooltip("Low-poly COL_ proxy mesh generated by the offline collider optimizer.")]
        [SerializeField] private Mesh collisionProxyMesh;

        [Tooltip("MeshCollider that must already reference the offline COL_ mesh before play.")]
        [SerializeField] private MeshCollider targetCollider;

        [Tooltip("Primitive fallback collider used only when an offline COL_ collider is absent.")]
        [SerializeField] private BoxCollider bootstrapProxyCollider;

        [Tooltip("Whether the COL_ mesh was authored as a convex collider.")]
        [SerializeField] private bool convex = true;

        [SerializeField, HideInInspector] private byte lastCommitPhase;
        [SerializeField, HideInInspector] private ulong cachedCollisionProxyMeshKey;

        private EntityId cachedCollisionProxyMeshEntityId;

        /// <summary>Gets the low-poly mesh selected by offline authoring.</summary>
        public Mesh CollisionProxyMesh => collisionProxyMesh;

        /// <summary>Gets the target collider selected by offline authoring.</summary>
        public MeshCollider TargetCollider => targetCollider;

        /// <summary>Gets the primitive fallback collider selected by offline authoring.</summary>
        public BoxCollider BootstrapProxyCollider => bootstrapProxyCollider;

        /// <summary>Gets whether the prebound mesh was authored as convex.</summary>
        public bool Convex => convex;

        /// <summary>Gets the last accepted commit phase as a byte for allocation-free diagnostics.</summary>
        public byte LastCommitPhase => lastCommitPhase;

        /// <summary>Gets the cached mesh entity key resolved during cold setup.</summary>
        public ulong CachedCollisionProxyMeshKey => cachedCollisionProxyMeshKey;

        private void OnEnable()
        {
            RefreshBakeIdentityCold();
        }

        /// <summary>
        /// Authoring-only configuration entry used by Editor tools. It performs no bake and no scene search.
        /// </summary>
        public void ConfigureAuthoring(
            Mesh proxyMesh,
            MeshCollider collider,
            BoxCollider bootstrapProxy,
            bool bakeConvex)
        {
            collisionProxyMesh = proxyMesh;
            targetCollider = collider;
            bootstrapProxyCollider = bootstrapProxy;
            convex = bakeConvex;
            RefreshBakeIdentityCold();
        }

        /// <summary>
        /// Cold identity refresh for authoring/import/bootstrap. Dispatcher read accessors must not call Unity object identity APIs.
        /// </summary>
        public void RefreshBakeIdentityCold()
        {
            cachedCollisionProxyMeshEntityId = collisionProxyMesh != null ? collisionProxyMesh.GetEntityId() : default;
            cachedCollisionProxyMeshKey = EntityId.ToULong(cachedCollisionProxyMeshEntityId);
        }

        /// <summary>
        /// Pure read accessor kept for binary/source compatibility. Runtime scheduling is blocked.
        /// </summary>
        public bool TryResolveBakeRequest(
            out EntityId meshEntityId,
            out bool bakeConvex,
            out MeshCollider collider)
        {
            collider = targetCollider;
            bakeConvex = convex;
            meshEntityId = cachedCollisionProxyMeshEntityId;
            return false;
        }

        /// <summary>
        /// Enables a prebound offline proxy collider. Runtime sharedMesh reassignment is forbidden.
        /// </summary>
        public bool CommitBakedCollider(RuntimePhysicsBakeCommitPhase1609 phase)
        {
            if (!IsCommitPhaseAllowed(phase))
                return false;

            if (targetCollider == null ||
                collisionProxyMesh == null ||
                targetCollider.sharedMesh != collisionProxyMesh ||
                cachedCollisionProxyMeshKey == 0ul ||
                EntityId.ToULong(cachedCollisionProxyMeshEntityId) != cachedCollisionProxyMeshKey)
                return false;

            targetCollider.enabled = true;

            if (bootstrapProxyCollider != null)
                bootstrapProxyCollider.enabled = false;

            lastCommitPhase = (byte)phase;
            return true;
        }

        /// <summary>
        /// Phase gate for dispatcher owners. Pure and allocation-free.
        /// </summary>
        public static bool IsCommitPhaseAllowed(RuntimePhysicsBakeCommitPhase1609 phase)
        {
            return phase == RuntimePhysicsBakeCommitPhase1609.PostSimulation ||
                   phase == RuntimePhysicsBakeCommitPhase1609.VisualSync;
        }
    }

}
