using UnityEngine;

namespace Hecton8.Gameplay
{
    /// <summary>
    /// Authored metadata profile for hazard-zone content.
    /// </summary>
    [CreateAssetMenu(fileName = "HazardZoneProfile_", menuName = "Hecton8/Gameplay/Hazard Zone Profile")]
    public sealed class HazardZoneProfile : ScriptableObject
    {
        [Header("Hazard")]
        [Tooltip("Canonical hazard type emitted by the authored source.")]
        [SerializeField] private HazardType hazardType = HazardType.Radiation;

        [Tooltip("Authoring-side normalized falloff curve. Runtime broadphase still uses bounded quadratic attenuation for zero-GC evaluation.")]
        [SerializeField] private AnimationCurve intensityCurve = AnimationCurve.EaseInOut(0f, 1f, 1f, 0f);

        [Tooltip("Multiplier applied to visor corruption generated by this hazard source.")]
        [SerializeField, Range(0f, 2f)] private float visorGlitchBias = 1f;

        [Tooltip("Authoring identifier for downstream dread-acoustics routing.")]
        [SerializeField] private uint acousticDreadID;

        /// <summary>Canonical emitted hazard type.</summary>
        public HazardType HazardType => hazardType;

        /// <summary>Normalized authored falloff curve for content tooling.</summary>
        public AnimationCurve IntensityCurve => intensityCurve;

        /// <summary>Multiplier applied to visor corruption for this profile.</summary>
        public float VisorGlitchBias => visorGlitchBias;

        /// <summary>Authoring identifier for acoustic dread routing.</summary>
        public uint AcousticDreadID => acousticDreadID;

#if UNITY_EDITOR
        private void OnValidate()
        {
            visorGlitchBias = Mathf.Clamp(visorGlitchBias, 0f, 2f);
            if (intensityCurve == null || intensityCurve.length == 0)
                intensityCurve = AnimationCurve.EaseInOut(0f, 1f, 1f, 0f);
        }
#endif
    }
}
