using UnityEngine;

namespace Hecton8.Gameplay
{
    /// <summary>
    /// Authored metadata profile for hazard-zone content.
    /// </summary>
    [CreateAssetMenu(fileName = "HazardZoneProfile_", menuName = "Hecton8/Gameplay/Hazard Zone Profile")]
    public sealed class HazardZoneProfile : ScriptableObject
    {
        public const int IntensityLutSampleCount = 64;

        [Header("Hazard")]
        [Tooltip("Canonical hazard type emitted by the authored source.")]
        [SerializeField] private HazardType hazardType = HazardType.Radiation;

        [Tooltip("Authoring-side normalized falloff curve. Runtime broadphase still uses bounded quadratic attenuation for zero-GC evaluation.")]
        [SerializeField] private AnimationCurve intensityCurve = AnimationCurve.EaseInOut(0f, 1f, 1f, 0f);

        [Tooltip("Multiplier applied to visor corruption generated by this hazard source.")]
        [SerializeField, Range(0f, 2f)] private float visorGlitchBias = 1f;

        [Tooltip("Authoring identifier for downstream dread-acoustics routing.")]
        [SerializeField] private uint acousticDreadID;

        [SerializeField, HideInInspector] private float[] bakedIntensityLut = new float[IntensityLutSampleCount];

        /// <summary>Canonical emitted hazard type.</summary>
        public HazardType HazardType => hazardType;

        /// <summary>Normalized authored falloff curve for content tooling.</summary>
        public AnimationCurve IntensityCurve => intensityCurve;

        /// <summary>Prebaked normalized falloff LUT consumed by runtime hazard evaluation.</summary>
        public float[] BakedIntensityLut => bakedIntensityLut;

        /// <summary>Multiplier applied to visor corruption for this profile.</summary>
        public float VisorGlitchBias => visorGlitchBias;

        /// <summary>Authoring identifier for acoustic dread routing.</summary>
        public uint AcousticDreadID => acousticDreadID;

#if UNITY_EDITOR
        private void OnValidate()
        {
            visorGlitchBias = ClampFinite(visorGlitchBias, 1f, 0f, 2f);
            if (intensityCurve == null || intensityCurve.length == 0)
                intensityCurve = AnimationCurve.EaseInOut(0f, 1f, 1f, 0f);

            EnsureLutStorage();
            BakeIntensityCurveLut();
        }
#endif

        private void OnEnable()
        {
            EnsureLutStorage();
            BakeIntensityCurveLut();
        }

        private void EnsureLutStorage()
        {
            if (bakedIntensityLut == null || bakedIntensityLut.Length != IntensityLutSampleCount)
                bakedIntensityLut = new float[IntensityLutSampleCount];
        }

        private void BakeIntensityCurveLut()
        {
            if (bakedIntensityLut == null || bakedIntensityLut.Length != IntensityLutSampleCount)
                return;

            for (int i = 0; i < IntensityLutSampleCount; i++)
            {
                float normalizedDistance = IntensityLutSampleCount > 1
                    ? i / (float)(IntensityLutSampleCount - 1)
                    : 0f;
                float sample = intensityCurve != null && intensityCurve.length > 0
                    ? intensityCurve.Evaluate(normalizedDistance)
                    : ResolveDefaultIntensitySample(normalizedDistance);
                bakedIntensityLut[i] = Clamp01Finite(sample, ResolveDefaultIntensitySample(normalizedDistance));
            }
        }

        private static void BakeDefaultIntensityCurveLut(float[] target)
        {
            if (target == null)
                return;

            int sampleCount = Mathf.Min(target.Length, IntensityLutSampleCount);
            for (int i = 0; i < sampleCount; i++)
            {
                float normalizedDistance = sampleCount > 1
                    ? i / (float)(sampleCount - 1)
                    : 0f;
                target[i] = Clamp01Finite(ResolveDefaultIntensitySample(normalizedDistance), 0f);
            }
        }

        private static float ResolveDefaultIntensitySample(float normalizedDistance)
        {
            float safeDistance = Clamp01Finite(normalizedDistance, 0f);
            float attenuation = 1f - (safeDistance * safeDistance);
            return attenuation > 0f ? attenuation * attenuation : 0f;
        }

        private static float Clamp01Finite(float value, float fallback)
        {
            return float.IsFinite(value) ? Mathf.Clamp01(value) : Mathf.Clamp01(fallback);
        }

        private static float ClampFinite(float value, float fallback, float minimum, float maximum)
        {
            return float.IsFinite(value) ? Mathf.Clamp(value, minimum, maximum) : Mathf.Clamp(fallback, minimum, maximum);
        }
    }
}
