using UnityEngine;

namespace Hecton8.Gameplay
{
    /// <summary>
    /// Environment-force bridge that buffers currents, updrafts, and stress before the motor applies them.
    /// </summary>
    public interface IHectonPlayerEnvironmentHandler
    {
        /// <summary>Clears transient step buffers before a new fixed-step evaluation begins.</summary>
        void ResetStepBuffers();

        /// <summary>Clears all runtime state during teardown.</summary>
        void ResetRuntimeState();

        /// <summary>Queues world-space acceleration generated by environment systems.</summary>
        void QueueExternalAcceleration(Vector3 acceleration);

        /// <summary>Queues world-space velocity change generated by environment systems.</summary>
        void QueueVelocityChange(Vector3 velocityChange);

        /// <summary>Queues a normalized hull-stress request from environment systems.</summary>
        void QueueHullStress(float normalizedStress);

        /// <summary>Consumes queued external acceleration.</summary>
        Vector3 ConsumeExternalAcceleration();

        /// <summary>Consumes queued velocity change.</summary>
        Vector3 ConsumeVelocityChange();

        /// <summary>Consumes queued hull-stress request.</summary>
        float ConsumeHullStress();
    }
}
