import json
from pathlib import Path

def E(path, line, quote):
    return dict(path=path, line=line, quote=quote)

d = {}
parts = []
parts.append('hop2 INPUTHOP readHop=2 is recorded ONLY inside InputDispatcher.GetState via DiagRecordReadObservation(2). ')
parts.append('GetState is reached solely through HectonPlayerInputHandler.TryReadFrame after inputService not null and IsPlayerInputEnabled. ')
parts.append('TryReadFrame is only invoked from HPM ProcessPlayerInputFrame or SeedInputStateFromService. ')
parts.append('Fixed-step path: HPM.FixedTick then SampleGameplayLocomotionInputForFixedStep then ProcessPlayerInputFrame then TryReadFrame then GetState. ')
parts.append('L13 moved SampleGameplay before suit juice and driver calls EnsureDispatcherRegistration; hop2 still ABSENT while hop1 CurrentInputState shows MoveDelta equals 0,1. ')
parts.append('Therefore GetState never called. A: HPM FixedTick Tick on PriorityLayer.Player never runs. B: SampleGameplay menu block without GetState. C: IsPlayerInputEnabled false before GetState. ')
parts.append('waitingOn=LocomotionHoldInProgress is normal Swim hold text, not a FixedTick gate. ')
parts.append('Most probable residual after L13: pre-GetState gates menu block and or IsPlayerInputEnabled and or Player fixed-lane still not actually invoked despite registration re-assert.')
d['root_hypothesis'] = ''.join(parts)
d['evidence_files'] = []
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/InputDispatcher.cs', 503, 'CurrentInputState getter calls DiagRecordReadObservation(1) then returns _currentInputState'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/InputDispatcher.cs', 1203, 'readHop: 0=final, 1=CurrentInputState driver-side, 2=GetState movement-side; hop2 proves HPM reads service'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/InputDispatcher.cs', 1207, 'private void DiagRecordReadObservation(int readHop)'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/InputDispatcher.cs', 1251, 'DiagEmitHopCensus emits H8_INPUTHOP readHop'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/InputDispatcher.cs', 1359, 'public PlayerInputState GetState: DiagRecordReadObservation(2); return _currentState'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Gameplay/HectonPlayerInputHandler.cs', 37, 'if inputService == null or not IsPlayerInputEnabled: return false'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Gameplay/HectonPlayerInputHandler.cs', 40, 'PlayerInputState state = inputService.GetState()'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 8217, 'private void SampleGameplayLocomotionInputForFixedStep'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 8221, 'if IsGameplayInputBlockedByMenu: zero inputs; return  # no GetState'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 8233, 'ProcessPlayerInputFrame(); ProcessWipeoutInputOverride()'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 8141, 'if _inputManager not null and IsPlayerInputEnabled: TryReadFrame else zero'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 9930, 'FixedTick: EnsureJuiceProcessor; SampleGameplayLocomotionInputForFixedStep; then suit may return'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 9774, 'IsGameplayInputBlockedByMenu = or PDA.IsOpen or PauseMenuController.IsAnyOpen'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 5470, 'EnsureDispatcherRegistration calls TryRegisterToDispatchers'))
d['evidence_files'].append(E('Assets/_Project/Scripts/HectonPlayerMovement.cs', 5485, 'if not _registeredFixedTick: TryRegisterFixedTickable(this, PriorityLayer.Player)'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/SystemDispatcher.cs', 5274, 'blockGameplayLanes = _runtimeGameplayBootstrapGateActive and HasActiveInstance and not IsGameReady'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/SystemDispatcher.cs', 5320, 'RunFixedStepAccumulator(deltaTime, blockGameplayLanes)'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/SystemDispatcher.cs', 6240, 'DispatchFixedStep(fixedDeltaTime, blockGameplayLanes)'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/SystemDispatcher.cs', 6253, 'if ShouldSkipLaneDuringBootstrap(laneIndex, blockGameplayLanes): continue'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/SystemDispatcher.cs', 6266, 'lane.GetAt(itemIndex).FixedTick(fixedDeltaTime)'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/SystemDispatcher.cs', 7115, 'ShouldSkipLaneDuringBootstrap skips Player lane when blockGameplayLanes'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Core/GlobalRegistry.cs', 6541, 'TryRegisterFixedTickable EnsureDispatcher plus fixedTickables plus SystemDispatcher.Register'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Bootstrap/GameBootstrapper.cs', 3161, 'ShouldSkipLaneDuringBootstrap skips PriorityLayer.Player while not IsGameReady'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Bootstrap/GameBootstrapper.cs', 3165, 'Headless short-circuit PublishGameReady true PublishBootstrapPresence false'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Editor/Diagnostics/H8_HeadlessWorldDriver.cs', 2651, 'EnsureGameplayLocomotionInputReady ForceClose menus SwitchToPlayerInput EnsureDispatcherRegistration'))
d['evidence_files'].append(E('Assets/_Project/Scripts/Editor/Diagnostics/H8_HeadlessWorldDriver.cs', 2848, 'waitReason LocomotionHoldInProgress normal Swim hold not FixedTick gate'))
d['evidence_files'].append(E('Assets/_Project/Scripts/UI/PauseMenuController.cs', 189, 'IsAnyOpen equals _openMenuCount greater than 0'))
d['evidence_files'].append(E('Assets/_Project/Scripts/UI/PauseMenuController.cs', 38, 'IsAnyOpen stays true HPM SampleGameplay zeros input without GetState hop2 starve'))
