import json
from pathlib import Path

root = Path(__file__).resolve().parent
packet_path = root / "Docs" / "Lore" / "AppliedContent" / "packets" / "RS039_FINAL_DECISION_EMOTIONAL_AXIS.packets.json"

texts = {
    "en_US": {
        "title": "Best Route: Residue Left Visible",
        "scanner": "BEST ROUTE RULE // Save a concrete outcome: operator custody, public record, denied payload, living basin, worker-name packet, or Atlas proof hash. Leave damage fields open.",
        "field_note": "If every row closes, the ending hid the room.",
        "terminal": "ENDING RECORD STANDARD\nRequired saved object or state: operator exit, public record, denied Deep Reach payload, preserved basin ecology, worker-name packet, or Atlas proof hash.\nRequired open fields: receiver custody, liability chain, missing names, basin damage, Atlas state, lien residue.\nInvalid record: all costs hidden behind payout, rescue, or corporate closure.\nRecord use: show what changed and what still has a filing party.",
        "audio": "If every row closes, the record is lying.",
        "in_game_wiki": "Residue Left Visible is the standard for the strongest route. The ending should save something concrete without turning HECTON-8 into a reward screen: a public record, denied Deep Reach routing, a preserved basin, a freed operator, worker names, or an Atlas proof hash. The record must also keep open fields for receiver custody, liability, missing names, basin damage, Atlas state, and debt residue.",
        "external_site": "Residue Left Visible is the ending standard: save a concrete outcome, then keep the receiver, liability, missing-name, basin-damage, Atlas-state and debt fields readable.",
        "external_site_article": "The strongest HECTON-8 ending should not repair the setting into a reward screen. It should let the operator accomplish concrete work: leave Black Keel custody, publish a record, deny Deep Reach a return route, preserve a living basin under quarantine, carry worker names out, or seal an Atlas proof hash where it cannot be priced as cargo.\n\nThe record must also keep open fields. A paid exit can omit worker names. Public release can create weaponized receivers. Severance can stop damaged authority and injure repair life. Preservation can protect pressure ecology and keep the old sorter active. A good final record shows the saved thing, the receiver, the debt effect, the Atlas state, and the harm still moving through the system.",
        "localization_status": "source_authority",
    },
    "ar_SA": {
        "title": "أفضل مسار: إبقاء الأثر مرئيا",
        "scanner": "قاعدة أفضل مسار // احفظ نتيجة ملموسة: حيازة المشغل، سجل عام، حمولة مرفوضة، حوض حي، حزمة أسماء عمال، أو Atlas proof hash. اترك حقول الضرر مفتوحة.",
        "field_note": "إذا أغلقت كل الخانات، فقد أخفت النهاية الغرفة.",
        "terminal": "معيار سجل النهاية\nالمطلوب إنقاذه كشيء أو حالة: خروج المشغل، سجل عام، حمولة Deep Reach مرفوضة، بيئة حوض محفوظة، حزمة أسماء عمال، أو Atlas proof hash.\nحقول يجب أن تبقى مفتوحة: حيازة المستقبل، سلسلة المسؤولية، الأسماء المفقودة، ضرر الحوض، حالة Atlas، بقايا الدين.\nسجل مرفوض: كل التكاليف مخفية خلف دفع أو إنقاذ أو إغلاق مؤسسي.\nاستخدام السجل: إظهار ما تغير وما لا يزال له طرف إيداع.",
        "audio": "إذا أغلقت كل الخانات، فالسجل يكذب.",
        "in_game_wiki": "إبقاء الأثر مرئيا هو معيار أقوى مسار. يجب أن تنقذ النهاية شيئا ملموسا من دون تحويل HECTON-8 إلى شاشة مكافأة: سجل عام، منع مسار Deep Reach، حوض محفوظ، مشغل محرر، أسماء عمال، أو Atlas proof hash. ويجب أن تبقي السجل حقولا مفتوحة لحيازة المستقبل، والمسؤولية، والأسماء المفقودة، وضرر الحوض، وحالة Atlas، وبقايا الدين.",
        "external_site": "إبقاء الأثر مرئيا هو معيار النهاية: احفظ نتيجة ملموسة، ثم أبق حقول المستقبل والمسؤولية والأسماء المفقودة وضرر الحوض وحالة Atlas والدين قابلة للقراءة.",
        "external_site_article": "أقوى نهاية في HECTON-8 لا ينبغي أن تصلح المكان ليصبح شاشة مكافأة. يجب أن تسمح للمشغل بعمل ملموس: الخروج من حيازة Black Keel، نشر سجل، منع Deep Reach من طريق عودة، حفظ حوض حي تحت الحجر، إخراج أسماء العمال، أو تثبيت Atlas proof hash في مكان لا يمكن تسعيره كحمولة.\n\nويجب أن تبقي السجل حقولا مفتوحة. خروج مدفوع يمكن أن يحذف أسماء العمال. النشر العام يمكن أن يصنع مستقبلين مسلحين بالملف. القطع يمكن أن يوقف سلطة متضررة ويؤذي حياة الإصلاح. الحفظ يمكن أن يحمي بيئة الضغط ويبقي المصنف القديم نشطا. سجل نهائي جيد يعرض الشيء الذي نجا، والمستقبل، وأثر الدين، وحالة Atlas، والضرر الذي لا يزال يتحرك داخل النظام.",
        "localization_status": "draft_needs_native_review",
    },
    "de_DE": {
        "title": "Beste Route: Rückstände bleiben sichtbar",
        "scanner": "REGEL FÜR DIE BESTE ROUTE // Sichere ein konkretes Ergebnis: Operator-Verwahrung, öffentlicher Datensatz, verweigerte Nutzlast, lebendes Becken, Arbeiternamen-Paket oder Atlas-Proof-Hash. Schadensfelder bleiben offen.",
        "field_note": "Wenn jede Zeile schließt, hat das Ende den Raum versteckt.",
        "terminal": "STANDARD FÜR ENDING-DATENSATZ\nErforderlich gerettetes Objekt oder Zustand: Operator-Ausgang, öffentlicher Datensatz, verweigerte Deep-Reach-Nutzlast, erhaltene Beckenökologie, Arbeiternamen-Paket oder Atlas-Proof-Hash.\nErforderlich offene Felder: Empfängerverwahrung, Haftungskette, fehlende Namen, Beckenschaden, Atlas-Zustand, Pfandreste.\nUngültiger Datensatz: alle Kosten hinter Auszahlung, Rettung oder Firmenschluss verborgen.\nNutzung: zeigen, was sich geändert hat und wofür noch eine Ablagepartei existiert.",
        "audio": "Wenn jede Zeile schließt, lügt der Datensatz.",
        "in_game_wiki": "Rückstände bleiben sichtbar ist der Standard für die stärkste Route. Das Ende soll etwas Konkretes sichern, ohne HECTON-8 in einen Belohnungsbildschirm zu verwandeln: einen öffentlichen Datensatz, verweigertes Deep-Reach-Routing, ein erhaltenes Becken, einen freien Operator, Arbeiternamen oder einen Atlas-Proof-Hash. Der Datensatz muss außerdem offene Felder für Empfängerverwahrung, Haftung, fehlende Namen, Beckenschaden, Atlas-Zustand und Schuldenreste behalten.",
        "external_site": "Rückstände bleiben sichtbar ist der Ending-Standard: ein konkretes Ergebnis sichern und Empfänger-, Haftungs-, Fehlname-, Beckenschaden-, Atlas-Zustand- und Schuldenfelder lesbar lassen.",
        "external_site_article": "Das stärkste HECTON-8-Ende sollte die Welt nicht zu einem Belohnungsbildschirm reparieren. Es sollte dem Operator konkrete Arbeit erlauben: Black-Keel-Verwahrung verlassen, einen Datensatz veröffentlichen, Deep Reach einen Rückweg verwehren, ein lebendes Becken unter Quarantäne erhalten, Arbeiternamen hinaustragen oder einen Atlas-Proof-Hash versiegeln, wo er nicht als Fracht bepreist werden kann.\n\nDer Datensatz muss auch offene Felder behalten. Ein bezahlter Ausgang kann Arbeiternamen auslassen. Öffentliche Freigabe kann bewaffnete Empfänger erzeugen. Trennung kann beschädigte Autorität stoppen und Reparaturleben verletzen. Erhalt kann Druckökologie schützen und den alten Sortierer aktiv lassen. Ein guter finaler Datensatz zeigt das Gerettete, den Empfänger, den Schuldeneffekt, den Atlas-Zustand und den Schaden, der noch durch das System läuft.",
        "localization_status": "draft_needs_native_review",
    },
    "es_ES": {
        "title": "Mejor ruta: residuo visible",
        "scanner": "REGLA DE MEJOR RUTA // Salva un resultado concreto: custodia del operador, registro público, carga denegada, cuenca viva, paquete de nombres laborales o proof-hash de Atlas. Deja abiertos los campos de daño.",
        "field_note": "Si todas las filas cierran, el final escondió la sala.",
        "terminal": "ESTÁNDAR DE REGISTRO DE FINAL\nObjeto o estado salvado requerido: salida del operador, registro público, carga de Deep Reach denegada, ecología de cuenca preservada, paquete de nombres laborales o proof-hash de Atlas.\nCampos abiertos requeridos: custodia del receptor, cadena de responsabilidad, nombres ausentes, daño de cuenca, estado de Atlas, residuo de deuda.\nRegistro inválido: todos los costes escondidos tras pago, rescate o cierre corporativo.\nUso del registro: mostrar qué cambió y qué aún tiene parte de archivo.",
        "audio": "Si todas las filas cierran, el registro miente.",
        "in_game_wiki": "Residuo visible es el estándar de la ruta más fuerte. El final debe salvar algo concreto sin convertir HECTON-8 en una pantalla de recompensa: un registro público, rutas de Deep Reach denegadas, una cuenca preservada, un operador libre, nombres laborales o un proof-hash de Atlas. El registro también debe conservar campos abiertos para custodia del receptor, responsabilidad, nombres ausentes, daño de cuenca, estado de Atlas y residuo de deuda.",
        "external_site": "Residuo visible es el estándar de final: salvar un resultado concreto y dejar legibles los campos de receptor, responsabilidad, nombres ausentes, daño de cuenca, estado de Atlas y deuda.",
        "external_site_article": "El final más fuerte de HECTON-8 no debe reparar el escenario hasta convertirlo en una pantalla de recompensa. Debe permitir que el operador haga trabajo concreto: salir de la custodia de Black Keel, publicar un registro, negar a Deep Reach una ruta de regreso, preservar una cuenca viva en cuarentena, sacar nombres de trabajadores o sellar un proof-hash de Atlas donde no pueda tasarse como carga.\n\nEl registro también debe mantener campos abiertos. Una salida pagada puede omitir nombres de trabajadores. Una publicación pública puede crear receptores armados con el archivo. El corte puede detener una autoridad dañada y herir vida de reparación. La preservación puede proteger la ecología de presión y mantener activo al viejo clasificador. Un buen registro final muestra lo salvado, el receptor, el efecto sobre la deuda, el estado de Atlas y el daño que aún se mueve por el sistema.",
        "localization_status": "draft_needs_native_review",
    },
    "fr_FR": {
        "title": "Meilleure route : résidu visible",
        "scanner": "RÈGLE DE MEILLEURE ROUTE // Sauver un résultat concret : garde de l'opérateur, dossier public, charge refusée, bassin vivant, paquet de noms travailleurs ou proof-hash Atlas. Garder les champs de dommage ouverts.",
        "field_note": "Si chaque ligne se ferme, la fin a caché la pièce.",
        "terminal": "STANDARD DE DOSSIER DE FIN\nObjet ou état sauvé requis : sortie de l'opérateur, dossier public, charge Deep Reach refusée, écologie de bassin préservée, paquet de noms travailleurs ou proof-hash Atlas.\nChamps ouverts requis : garde du récepteur, chaîne de responsabilité, noms manquants, dommage du bassin, état Atlas, résidu de dette.\nDossier invalide : tous les coûts cachés derrière paiement, secours ou clôture corporative.\nUsage : montrer ce qui a changé et ce qui a encore une partie déposante.",
        "audio": "Si chaque ligne se ferme, le dossier ment.",
        "in_game_wiki": "Résidu visible est le standard de la route la plus forte. La fin doit sauver quelque chose de concret sans transformer HECTON-8 en écran de récompense : dossier public, routage Deep Reach refusé, bassin préservé, opérateur libéré, noms de travailleurs ou proof-hash Atlas. Le dossier doit aussi garder ouverts les champs de garde du récepteur, responsabilité, noms manquants, dommage du bassin, état Atlas et résidu de dette.",
        "external_site": "Résidu visible est le standard de fin : sauver un résultat concret, puis laisser lisibles les champs récepteur, responsabilité, noms manquants, dommage du bassin, état Atlas et dette.",
        "external_site_article": "La fin la plus forte de HECTON-8 ne doit pas réparer le décor en écran de récompense. Elle doit permettre à l'opérateur d'accomplir un travail concret : sortir de la garde Black Keel, publier un dossier, refuser à Deep Reach une route de retour, préserver un bassin vivant sous quarantaine, emporter des noms de travailleurs ou sceller un proof-hash Atlas là où il ne peut pas être tarifé comme cargaison.\n\nLe dossier doit aussi garder des champs ouverts. Une sortie payée peut omettre des noms de travailleurs. Une publication publique peut créer des récepteurs armés du dossier. La coupure peut arrêter une autorité endommagée et blesser la vie de réparation. La préservation peut protéger l'écologie de pression et garder l'ancien trieur actif. Un bon dossier final montre la chose sauvée, le récepteur, l'effet sur la dette, l'état Atlas et le dommage qui circule encore dans le système.",
        "localization_status": "draft_needs_native_review",
    },
    "he_IL": {
        "title": "הנתיב הטוב ביותר: שארית גלויה",
        "scanner": "כלל הנתיב הטוב ביותר // שמור תוצאה מוחשית: משמורת המפעיל, רשומה ציבורית, מטען שנדחה, אגן חי, חבילת שמות עובדים או Atlas proof hash. השאר שדות נזק פתוחים.",
        "field_note": "אם כל השורות נסגרות, הסיום הסתיר את החדר.",
        "terminal": "תקן רשומת סיום\nאובייקט או מצב שנדרשים להישמר: יציאת המפעיל, רשומה ציבורית, מטען Deep Reach שנדחה, אקולוגיית אגן שמורה, חבילת שמות עובדים או Atlas proof hash.\nשדות שחייבים להישאר פתוחים: משמורת מקבל, שרשרת אחריות, שמות חסרים, נזק אגן, מצב Atlas, שארית שעבוד.\nרשומה פסולה: כל העלויות מוסתרות מאחורי תשלום, חילוץ או סגירה תאגידית.\nשימוש ברשומה: להראות מה השתנה ומה עדיין מחזיק צד הגשה.",
        "audio": "אם כל השורות נסגרות, הרשומה משקרת.",
        "in_game_wiki": "שארית גלויה היא התקן לנתיב החזק ביותר. הסיום צריך להציל דבר מוחשי בלי להפוך את HECTON-8 למסך פרס: רשומה ציבורית, ניתוב Deep Reach שנדחה, אגן שמור, מפעיל משוחרר, שמות עובדים או Atlas proof hash. הרשומה חייבת גם להשאיר שדות פתוחים למשמורת מקבל, אחריות, שמות חסרים, נזק אגן, מצב Atlas ושארית חוב.",
        "external_site": "שארית גלויה היא תקן הסיום: להציל תוצאה מוחשית ואז להשאיר קריאים את שדות המקבל, האחריות, השמות החסרים, נזק האגן, מצב Atlas והחוב.",
        "external_site_article": "הסיום החזק ביותר של HECTON-8 לא צריך לתקן את המקום למסך פרס. הוא צריך לאפשר למפעיל לבצע עבודה מוחשית: לצאת ממשמורת Black Keel, לפרסם רשומה, למנוע מ-Deep Reach דרך חזרה, לשמור אגן חי בהסגר, להוציא שמות עובדים או לאטום Atlas proof hash במקום שבו אי אפשר לתמחר אותו כמטען.\n\nהרשומה חייבת גם להשאיר שדות פתוחים. יציאה בתשלום יכולה להשמיט שמות עובדים. פרסום ציבורי יכול ליצור מקבלים חמושים בקובץ. ניתוק יכול לעצור סמכות פגומה ולפגוע בחיי תיקון. שימור יכול להגן על אקולוגיית לחץ ולהשאיר את הממיין הישן פעיל. רשומת סיום טובה מראה את הדבר שנשמר, את המקבל, את השפעת החוב, את מצב Atlas ואת הנזק שעדיין נע במערכת.",
        "localization_status": "draft_needs_native_review",
    },
    "id_ID": {
        "title": "Rute Terbaik: Sisa Tetap Terlihat",
        "scanner": "ATURAN RUTE TERBAIK // Selamatkan hasil konkret: kustodi operator, catatan publik, muatan ditolak, cekungan hidup, paket nama pekerja, atau Atlas proof hash. Biarkan bidang kerusakan terbuka.",
        "field_note": "Jika semua baris tertutup, ending itu menyembunyikan ruangannya.",
        "terminal": "STANDAR CATATAN ENDING\nObjek atau keadaan yang wajib terselamatkan: keluarnya operator, catatan publik, muatan Deep Reach yang ditolak, ekologi cekungan terjaga, paket nama pekerja, atau Atlas proof hash.\nBidang yang wajib terbuka: kustodi penerima, rantai tanggung jawab, nama hilang, kerusakan cekungan, keadaan Atlas, sisa utang.\nCatatan tidak valid: semua biaya disembunyikan di balik pembayaran, penyelamatan, atau penutupan korporat.\nKegunaan catatan: menunjukkan apa yang berubah dan apa yang masih punya pihak pengaju.",
        "audio": "Jika semua baris tertutup, catatannya berbohong.",
        "in_game_wiki": "Sisa Tetap Terlihat adalah standar untuk rute terkuat. Ending harus menyelamatkan sesuatu yang konkret tanpa mengubah HECTON-8 menjadi layar hadiah: catatan publik, rute Deep Reach yang ditolak, cekungan yang dipertahankan, operator yang bebas, nama pekerja, atau Atlas proof hash. Catatan juga harus menjaga bidang terbuka untuk kustodi penerima, tanggung jawab, nama hilang, kerusakan cekungan, keadaan Atlas, dan sisa utang.",
        "external_site": "Sisa Tetap Terlihat adalah standar ending: selamatkan hasil konkret, lalu biarkan bidang penerima, tanggung jawab, nama hilang, kerusakan cekungan, keadaan Atlas, dan utang tetap terbaca.",
        "external_site_article": "Ending HECTON-8 yang paling kuat tidak boleh memperbaiki latar menjadi layar hadiah. Ending itu harus memberi operator pekerjaan konkret: keluar dari kustodi Black Keel, menerbitkan catatan, menolak rute kembali Deep Reach, menjaga cekungan hidup dalam karantina, membawa keluar nama pekerja, atau menyegel Atlas proof hash di tempat yang tidak bisa dihargai sebagai kargo.\n\nCatatan juga harus menjaga bidang terbuka. Keluar dengan pembayaran dapat menghilangkan nama pekerja. Rilis publik dapat menciptakan penerima yang mempersenjatai berkas. Pemutusan dapat menghentikan otoritas rusak dan melukai kehidupan perbaikan. Preservasi dapat melindungi ekologi tekanan dan menjaga penyortir lama tetap aktif. Catatan akhir yang baik menunjukkan benda yang diselamatkan, penerima, efek utang, keadaan Atlas, dan kerusakan yang masih bergerak di sistem.",
        "localization_status": "draft_needs_native_review",
    },
    "ja_JP": {
        "title": "最良ルート：残留を見えるままに",
        "scanner": "最良ルート規則 // 具体的な成果を救う。オペレーター保管権、公開記録、拒否されたペイロード、生きた盆地、作業員名パケット、Atlas proof hash。損害欄は開いたままにする。",
        "field_note": "すべての行が閉じているなら、その結末は部屋を隠した。",
        "terminal": "エンディング記録標準\n保存必須の物体または状態: オペレーター脱出、公開記録、Deep Reachペイロード拒否、保存された盆地生態、作業員名パケット、Atlas proof hash。\n未解決必須欄: 受信者保管権、責任連鎖、欠落名、盆地損害、Atlas状態、債務残留。\n無効記録: 支払い、救助、企業処理の裏に全コストを隠したもの。\n記録用途: 変わったことと、まだ提出側が残るものを示す。",
        "audio": "すべての行が閉じるなら、記録が嘘をついている。",
        "in_game_wiki": "残留を見えるままにすることが、最も強いルートの基準だ。結末はHECTON-8を報酬画面に変えず、具体的なものを救うべきだ。公開記録、拒否されたDeep Reach経路、保存された盆地、解放されたオペレーター、作業員名、Atlas proof hash。記録には受信者保管権、責任、欠落名、盆地損害、Atlas状態、債務残留の未解決欄も残さなければならない。",
        "external_site": "残留を見えるままにすることがエンディング基準だ。具体的な成果を救い、受信者、責任、欠落名、盆地損害、Atlas状態、債務欄を読めるまま残す。",
        "external_site_article": "HECTON-8で最も強い結末は、舞台を報酬画面へ修理してはいけない。オペレーターに具体的な仕事を達成させるべきだ。Black Keel保管から出る、記録を公開する、Deep Reachの戻り道を拒む、生きた盆地を隔離下で保存する、作業員名を持ち出す、あるいはAtlas proof hashを貨物として値付けできない場所に封じる。\n\n記録には未解決欄も残るべきだ。支払い済みの出口は作業員名を省ける。公開リリースはファイルを武器にする受信者を生む。切断は損傷した権限を止め、修復生命を傷つける。保存は圧力生態を守り、古い分類器を動かし続ける。良い最終記録は、救われたもの、受信者、債務効果、Atlas状態、そしてまだシステム内を動く被害を示す。",
        "localization_status": "draft_needs_native_review",
    },
    "ko_KR": {
        "title": "최선 경로: 잔여를 보이게 남김",
        "scanner": "최선 경로 규칙 // 구체적 결과를 구한다. 운영자 보관권, 공개 기록, 거부된 페이로드, 살아 있는 분지, 노동자 이름 패킷, Atlas proof hash. 손상 필드는 열어 둔다.",
        "field_note": "모든 행이 닫혀 있다면 그 엔딩은 방을 숨긴 것이다.",
        "terminal": "엔딩 기록 기준\n필수 보존 대상 또는 상태: 운영자 탈출, 공개 기록, 거부된 Deep Reach 페이로드, 보존된 분지 생태, 노동자 이름 패킷, Atlas proof hash.\n필수 미해결 필드: 수신자 보관권, 책임 사슬, 누락 이름, 분지 손상, Atlas 상태, 채무 잔여.\n무효 기록: 지급, 구조, 기업 종결 뒤에 모든 비용을 숨긴 기록.\n기록 용도: 무엇이 바뀌었고 무엇에 아직 제출 주체가 남았는지 표시.",
        "audio": "모든 행이 닫히면 그 기록은 거짓말이다.",
        "in_game_wiki": "잔여를 보이게 남기는 것이 가장 강한 경로의 기준이다. 엔딩은 HECTON-8을 보상 화면으로 바꾸지 않고 구체적인 것을 구해야 한다. 공개 기록, 차단된 Deep Reach 경로, 보존된 분지, 해방된 운영자, 노동자 이름, Atlas proof hash 같은 것들이다. 기록은 수신자 보관권, 책임, 누락 이름, 분지 손상, Atlas 상태, 채무 잔여의 열린 필드도 유지해야 한다.",
        "external_site": "잔여를 보이게 남기는 것이 엔딩 기준이다. 구체적 결과를 구한 뒤 수신자, 책임, 누락 이름, 분지 손상, Atlas 상태, 채무 필드를 읽을 수 있게 남긴다.",
        "external_site_article": "가장 강한 HECTON-8 엔딩은 세계를 보상 화면으로 수리해서는 안 된다. 운영자가 구체적 일을 해내게 해야 한다. Black Keel 보관에서 벗어나고, 기록을 공개하고, Deep Reach의 복귀 경로를 거부하고, 살아 있는 분지를 격리 상태로 보존하고, 노동자 이름을 밖으로 가져가거나, Atlas proof hash를 화물로 가격 매길 수 없는 곳에 봉인하는 일이다.\n\n기록은 열린 필드도 유지해야 한다. 지급된 탈출은 노동자 이름을 생략할 수 있다. 공개 릴리스는 파일을 무기화하는 수신자를 만든다. 절단은 손상된 권한을 멈추고 수리 생명을 다치게 할 수 있다. 보존은 압력 생태를 지키고 낡은 분류기를 계속 작동시킬 수 있다. 좋은 최종 기록은 구한 것, 수신자, 채무 효과, Atlas 상태, 그리고 아직 시스템 안에서 움직이는 피해를 보여 준다.",
        "localization_status": "draft_needs_native_review",
    },
    "nl_NL": {
        "title": "Beste route: residu zichtbaar houden",
        "scanner": "REGEL BESTE ROUTE // Red een concreet resultaat: operatorbewaring, publiek record, geweigerde payload, levend bekken, arbeidersnamenpakket of Atlas proof hash. Laat schadevelden open.",
        "field_note": "Als elke rij sluit, heeft het einde de kamer verborgen.",
        "terminal": "STANDAARD VOOR EINDRECORD\nVereist gered object of staat: operatoruitgang, publiek record, geweigerde Deep Reach-payload, bewaarde bekkenecologie, arbeidersnamenpakket of Atlas proof hash.\nVereiste open velden: receiverbewaring, aansprakelijkheidsketen, ontbrekende namen, bekkenschade, Atlas-staat, schuldresidu.\nOngeldig record: alle kosten verborgen achter uitbetaling, redding of bedrijfssluiting.\nGebruik: tonen wat veranderde en waar nog een indienende partij aan hangt.",
        "audio": "Als elke rij sluit, liegt het record.",
        "in_game_wiki": "Residu zichtbaar houden is de norm voor de sterkste route. Het einde moet iets concreets redden zonder HECTON-8 in een beloningsscherm te veranderen: een publiek record, geweigerde Deep Reach-routing, een bewaard bekken, een vrije operator, arbeidersnamen of een Atlas proof hash. Het record moet ook open velden houden voor receiverbewaring, aansprakelijkheid, ontbrekende namen, bekkenschade, Atlas-staat en schuldresidu.",
        "external_site": "Residu zichtbaar houden is de eindstandaard: red een concreet resultaat en houd receiver-, aansprakelijkheids-, ontbrekende-naam-, bekkenschade-, Atlas-staat- en schuldvelden leesbaar.",
        "external_site_article": "Het sterkste HECTON-8-einde mag de wereld niet repareren tot een beloningsscherm. Het moet de operator concreet werk laten doen: Black Keel-bewaring verlaten, een record publiceren, Deep Reach een terugweg ontzeggen, een levend bekken onder quarantaine bewaren, arbeidersnamen naar buiten dragen of een Atlas proof hash verzegelen waar hij niet als vracht geprijsd kan worden.\n\nHet record moet ook open velden houden. Een betaalde uitgang kan arbeidersnamen weglaten. Publieke vrijgave kan receivers maken die het dossier als wapen gebruiken. Severance kan beschadigde autoriteit stoppen en reparatieleven verwonden. Bewaren kan drukecologie beschermen en de oude sorteerder actief houden. Een goed eindrecord toont wat gered is, de receiver, het schuldeffect, de Atlas-staat en de schade die nog door het systeem beweegt.",
        "localization_status": "draft_needs_native_review",
    },
    "pl_PL": {
        "title": "Najlepsza trasa: widoczny osad",
        "scanner": "REGUŁA NAJLEPSZEJ TRASY // Zachowaj konkretny wynik: depozyt operatora, publiczny zapis, odrzucony ładunek, żywy basen, pakiet nazwisk pracowników albo Atlas proof hash. Pola szkód pozostają otwarte.",
        "field_note": "Jeśli każdy wiersz się zamyka, finał ukrył pomieszczenie.",
        "terminal": "STANDARD ZAPISU FINAŁU\nWymagany zachowany obiekt lub stan: wyjście operatora, publiczny zapis, odrzucony ładunek Deep Reach, zachowana ekologia basenu, pakiet nazwisk pracowników albo Atlas proof hash.\nWymagane pola otwarte: depozyt odbiorcy, łańcuch odpowiedzialności, brakujące nazwiska, szkoda basenu, stan Atlasa, osad długu.\nZapis nieważny: wszystkie koszty ukryte za wypłatą, ratunkiem albo zamknięciem korporacyjnym.\nUżycie zapisu: pokazać, co się zmieniło i co nadal ma stronę składającą.",
        "audio": "Jeśli każdy wiersz się zamyka, zapis kłamie.",
        "in_game_wiki": "Widoczny osad to standard najmocniejszej trasy. Finał ma uratować coś konkretnego bez zmiany HECTON-8 w ekran nagrody: publiczny zapis, odciętą trasę Deep Reach, zachowany basen, uwolnionego operatora, nazwiska pracowników albo Atlas proof hash. Zapis musi też zostawić otwarte pola depozytu odbiorcy, odpowiedzialności, brakujących nazwisk, szkody basenu, stanu Atlasa i osadu długu.",
        "external_site": "Widoczny osad jest standardem finału: zachować konkretny wynik, a potem zostawić czytelne pola odbiorcy, odpowiedzialności, brakujących nazwisk, szkody basenu, stanu Atlasa i długu.",
        "external_site_article": "Najmocniejszy finał HECTON-8 nie powinien naprawiać świata do ekranu nagrody. Powinien pozwolić operatorowi wykonać konkretną pracę: opuścić depozyt Black Keel, opublikować zapis, odmówić Deep Reach drogi powrotnej, zachować żywy basen w kwarantannie, wynieść nazwiska pracowników albo zapieczętować Atlas proof hash tam, gdzie nie da się go wycenić jak ładunku.\n\nZapis musi też zostawić otwarte pola. Płatne wyjście może pominąć nazwiska pracowników. Publiczna publikacja może stworzyć odbiorców uzbrojonych w plik. Odcięcie może zatrzymać uszkodzoną władzę i zranić życie naprawcze. Zachowanie może chronić ekologię ciśnienia i utrzymać stary sorter przy pracy. Dobry zapis finałowy pokazuje uratowaną rzecz, odbiorcę, efekt długu, stan Atlasa i szkodę, która nadal porusza się przez system.",
        "localization_status": "draft_needs_native_review",
    },
    "pt_BR": {
        "title": "Melhor rota: resíduo visível",
        "scanner": "REGRA DA MELHOR ROTA // Salve um resultado concreto: custódia do operador, registro público, payload negado, bacia viva, pacote de nomes de trabalhadores ou Atlas proof hash. Deixe campos de dano abertos.",
        "field_note": "Se todas as linhas fecham, o final escondeu a sala.",
        "terminal": "PADRÃO DE REGISTRO DE FINAL\nObjeto ou estado salvo obrigatório: saída do operador, registro público, payload da Deep Reach negado, ecologia de bacia preservada, pacote de nomes de trabalhadores ou Atlas proof hash.\nCampos abertos obrigatórios: custódia do receptor, cadeia de responsabilidade, nomes faltantes, dano da bacia, estado de Atlas, resíduo de dívida.\nRegistro inválido: todos os custos escondidos atrás de pagamento, resgate ou encerramento corporativo.\nUso do registro: mostrar o que mudou e o que ainda tem parte de protocolo.",
        "audio": "Se todas as linhas fecham, o registro mente.",
        "in_game_wiki": "Resíduo visível é o padrão da rota mais forte. O final deve salvar algo concreto sem transformar HECTON-8 em tela de recompensa: registro público, rota Deep Reach negada, bacia preservada, operador livre, nomes de trabalhadores ou Atlas proof hash. O registro também precisa manter campos abertos para custódia do receptor, responsabilidade, nomes faltantes, dano da bacia, estado de Atlas e resíduo de dívida.",
        "external_site": "Resíduo visível é o padrão de final: salvar um resultado concreto e deixar legíveis os campos de receptor, responsabilidade, nomes faltantes, dano da bacia, estado de Atlas e dívida.",
        "external_site_article": "O final mais forte de HECTON-8 não deve consertar o cenário até virar tela de recompensa. Ele deve permitir que o operador cumpra trabalho concreto: sair da custódia da Black Keel, publicar um registro, negar à Deep Reach uma rota de retorno, preservar uma bacia viva em quarentena, levar nomes de trabalhadores para fora ou selar um Atlas proof hash onde ele não possa ser precificado como carga.\n\nO registro também deve manter campos abertos. Uma saída paga pode omitir nomes de trabalhadores. Uma liberação pública pode criar receptores que usam o arquivo como arma. O corte pode parar autoridade danificada e ferir vida de reparo. A preservação pode proteger a ecologia de pressão e manter o classificador antigo ativo. Um bom registro final mostra o que foi salvo, o receptor, o efeito da dívida, o estado de Atlas e o dano que ainda se move pelo sistema.",
        "localization_status": "draft_needs_native_review",
    },
    "ru_RU": {
        "title": "Лучший маршрут: видимый остаток",
        "scanner": "ПРАВИЛО ЛУЧШЕГО МАРШРУТА // Сохрани конкретный результат: хранение оператора, публичную запись, отклоненный груз, живой бассейн, пакет имен рабочих или Atlas proof hash. Поля ущерба оставь открытыми.",
        "field_note": "Если закрыты все строки, финал спрятал комнату.",
        "terminal": "СТАНДАРТ ЗАПИСИ ФИНАЛА\nОбязательный спасенный объект или статус: выход оператора, публичная запись, отклоненный груз Deep Reach, сохраненная экология бассейна, пакет имен рабочих или Atlas proof hash.\nОбязательные открытые поля: хранение получателя, цепочка ответственности, пропавшие имена, ущерб бассейна, состояние Atlas, остаток долга.\nНедействительная запись: все издержки спрятаны за выплатой, спасением или корпоративным закрытием.\nНазначение записи: показать, что изменилось и где еще есть сторона подачи.",
        "audio": "Если закрыты все строки, запись врет.",
        "in_game_wiki": "Видимый остаток - стандарт самого сильного маршрута. Финал должен спасать что-то конкретное, не превращая HECTON-8 в экран награды: публичную запись, закрытый маршрут Deep Reach, сохраненный бассейн, освобожденного оператора, имена рабочих или Atlas proof hash. Запись также должна оставить открытые поля для хранения получателя, ответственности, пропавших имен, ущерба бассейна, состояния Atlas и остатка долга.",
        "external_site": "Видимый остаток - стандарт финала: спасти конкретный результат, а затем оставить читаемыми поля получателя, ответственности, пропавших имен, ущерба бассейна, состояния Atlas и долга.",
        "external_site_article": "Самый сильный финал HECTON-8 не должен чинить мир до экрана награды. Он должен дать оператору сделать конкретную работу: выйти из хранения Black Keel, опубликовать запись, закрыть Deep Reach дорогу назад, сохранить живой бассейн под карантином, вынести имена рабочих или запечатать Atlas proof hash там, где его нельзя оценить как груз.\n\nЗапись должна оставить и открытые поля. Оплаченный выход может пропустить имена рабочих. Публичная публикация может создать получателей, которые используют файл как оружие. Отсечение может остановить поврежденную власть и ранить ремонтную жизнь. Сохранение может защитить напорную экологию и оставить старый сортировщик активным. Хорошая финальная запись показывает спасенную вещь, получателя, эффект долга, состояние Atlas и ущерб, который все еще движется по системе.",
        "localization_status": "draft_needs_native_review",
    },
    "uk_UA": {
        "title": "Найкращий маршрут: видимий залишок",
        "scanner": "ПРАВИЛО НАЙКРАЩОГО МАРШРУТУ // Збережи конкретний результат: зберігання оператора, публічний запис, відхилений вантаж, живий басейн, пакет імен працівників або Atlas proof hash. Поля шкоди лиши відкритими.",
        "field_note": "Якщо закриті всі рядки, фінал сховав кімнату.",
        "terminal": "СТАНДАРТ ЗАПИСУ ФІНАЛУ\nОбов'язковий врятований об'єкт або стан: вихід оператора, публічний запис, відхилений вантаж Deep Reach, збережена екологія басейну, пакет імен працівників або Atlas proof hash.\nОбов'язкові відкриті поля: зберігання отримувача, ланцюг відповідальності, зниклі імена, шкода басейну, стан Atlas, залишок боргу.\nНедійсний запис: усі витрати сховані за виплатою, порятунком або корпоративним закриттям.\nПризначення запису: показати, що змінилося і де ще є сторона подання.",
        "audio": "Якщо закриті всі рядки, запис бреше.",
        "in_game_wiki": "Видимий залишок - стандарт найсильнішого маршруту. Фінал має рятувати щось конкретне, не перетворюючи HECTON-8 на екран винагороди: публічний запис, закритий маршрут Deep Reach, збережений басейн, звільненого оператора, імена працівників або Atlas proof hash. Запис також має лишити відкриті поля для зберігання отримувача, відповідальності, зниклих імен, шкоди басейну, стану Atlas і залишку боргу.",
        "external_site": "Видимий залишок - стандарт фіналу: врятувати конкретний результат, а потім лишити читабельними поля отримувача, відповідальності, зниклих імен, шкоди басейну, стану Atlas і боргу.",
        "external_site_article": "Найсильніший фінал HECTON-8 не має лагодити світ до екрана винагороди. Він має дати оператору зробити конкретну роботу: вийти зі зберігання Black Keel, опублікувати запис, закрити Deep Reach дорогу назад, зберегти живий басейн під карантином, винести імена працівників або запечатати Atlas proof hash там, де його не можна оцінити як вантаж.\n\nЗапис має лишити й відкриті поля. Оплачений вихід може пропустити імена працівників. Публічна публікація може створити отримувачів, які використовують файл як зброю. Відсікання може зупинити пошкоджену владу і поранити ремонтне життя. Збереження може захистити екологію тиску і лишити старий сортувальник активним. Добрий фінальний запис показує врятовану річ, отримувача, ефект боргу, стан Atlas і шкоду, що досі рухається системою.",
        "localization_status": "draft_needs_native_review",
    },
    "zh_CN": {
        "title": "最佳路线：让残余可见",
        "scanner": "最佳路线规则 // 保存一个具体结果：操作者保管、公共记录、被拒载荷、活体盆地、工人姓名包，或 Atlas proof hash。损害字段保持开启。",
        "field_note": "如果每一行都关闭，这个结局藏起了房间。",
        "terminal": "结局记录标准\n必须保存的对象或状态：操作者离开、公共记录、被拒 Deep Reach 载荷、保留的盆地生态、工人姓名包，或 Atlas proof hash。\n必须开启的字段：接收方保管、责任链、缺失姓名、盆地损害、Atlas 状态、债务残余。\n无效记录：所有代价都被付款、救援或公司结案掩盖。\n记录用途：显示什么改变了，以及什么仍有提交方。",
        "audio": "如果每一行都关闭，记录就在说谎。",
        "in_game_wiki": "让残余可见是最强路线的标准。结局应该保存一个具体结果，而不是把 HECTON-8 变成奖励界面：公共记录、被拒绝的 Deep Reach 路由、保留下来的盆地、获释的操作者、工人姓名，或 Atlas proof hash。记录还必须保留接收方保管、责任、缺失姓名、盆地损害、Atlas 状态和债务残余等开启字段。",
        "external_site": "让残余可见是结局标准：保存一个具体结果，然后让接收方、责任、缺失姓名、盆地损害、Atlas 状态和债务字段保持可读。",
        "external_site_article": "HECTON-8 最强的结局不应该把场景修成奖励界面。它应该让操作者完成具体工作：离开 Black Keel 保管，发布记录，拒绝 Deep Reach 的返回路，在隔离下保存一个活体盆地，带出工人姓名，或把 Atlas proof hash 封存在无法按货物定价的位置。\n\n记录也必须保留开启字段。付费离开可能省略工人姓名。公开发布可能制造把文件武器化的接收方。切断可以停止受损权威，也可以伤害修复生命。保留可以保护压力生态，也会让旧分类器继续活动。一份好的最终记录会显示被救下的东西、接收方、债务效果、Atlas 状态，以及仍在系统里移动的损害。",
        "localization_status": "draft_needs_native_review",
    },
}

data = json.loads(packet_path.read_text(encoding="utf-8"))
for packet in data["packets"]:
    if packet.get("packet_id") == "P195_BEST_ENDING_NO_CLEAN_HANDS":
        packet["localized"] = texts
        break
else:
    raise SystemExit("P195 packet not found")

packet_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
