#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using Hecton8.EditorTools;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

namespace Hecton8.Editor
{
    /// <summary>
    /// Enforces HECTON-8 managed model import policy and exposes bulk reimport actions for legacy content.
    /// </summary>
    internal sealed class HectonFBXPostprocessor : AssetPostprocessor
    {
        internal const string ProjectArtRoot = "Assets/_Project/Art";
        internal const string PrologueModelRoot = "Assets/_Project/_PROLOGUE_CONTENT/Models";
        internal const string ScifiFacilityRoot = "Assets/ScifiFacility";
        internal static readonly string[] ManagedFbxRoots =
        {
            ProjectArtRoot,
            PrologueModelRoot,
            ScifiFacilityRoot
        };
        private const float ScifiFacilityNormalSmoothingAngle = 60f;
        private const float DeterministicSecondaryUvHardAngle = 88f;
        private const float DeterministicSecondaryUvAngleDistortion = 8f;
        private const float DeterministicSecondaryUvAreaDistortion = 15f;
        private const int DeterministicSecondaryUvPackMargin = 4;
        private const int AutoLodTriangleThreshold = 2000;
        private const float AutoGeneratedLod0ScreenRelativeHeight = 0.6f;
        private const float AutoGeneratedLod1ScreenRelativeHeight = 0.15f;
        private const float AutoGeneratedLod2ScreenRelativeHeight = 0.04f;
        private const float AutoGeneratedLodFadeWidth = 0.12f;
        private const float AutoGeneratedLod1TriangleRatio = 0.5f;
        private const float AutoGeneratedLod2TriangleRatio = 0.1f;

        private static readonly List<Vector3> EmptyVertices = new List<Vector3>(0);
        private static readonly List<Vector4> EmptyTangents = new List<Vector4>(0);

        [MenuItem("Hecton/Validation/Asset Pipeline/Reimport FBX - Assets Project Art", priority = 180)]
        private static void ReimportProjectArtFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(new[] { ProjectArtRoot });
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under '{ProjectArtRoot}'.");
        }

        [MenuItem("Hecton/Validation/Asset Pipeline/Reimport FBX - ScifiFacility", priority = 181)]
        private static void ReimportScifiFacilityFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(new[] { ScifiFacilityRoot });
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under '{ScifiFacilityRoot}'.");
        }

        [MenuItem("Hecton/Validation/Asset Pipeline/Reimport FBX - Managed Roots", priority = 182)]
        private static void ReimportManagedRootsFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(ManagedFbxRoots);
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under the managed roots.");
        }

        [MenuItem("Hecton/Validation/Asset Pipeline/Validate FBX - ScifiFacility", priority = 183)]
        private static void ValidateScifiFacilityFbxPolicy()
        {
            List<string> fbxPaths = CollectFbxPaths(new[] { ScifiFacilityRoot });
            int mismatchCount = 0;

            for (int i = 0; i < fbxPaths.Count; i++)
            {
                ModelImporter importer = AssetImporter.GetAtPath(fbxPaths[i]) as ModelImporter;
                if (!ImporterMatchesScifiFacilityPolicy(importer))
                {
                    mismatchCount++;
                    Debug.LogError($"[HectonFBXPostprocessor] ScifiFacility importer policy drift: '{fbxPaths[i]}'.");
                }
            }

            if (mismatchCount <= 0)
            {
                Debug.Log($"[HectonFBXPostprocessor] Validated {fbxPaths.Count} ScifiFacility FBX assets. No importer drift detected.");
                return;
            }

            Debug.LogError($"[HectonFBXPostprocessor] Found {mismatchCount} ScifiFacility FBX assets with importer drift.");
        }

        internal static List<string> CollectFbxPaths(string[] searchRoots)
        {
            string[] modelGuids = AssetDatabase.FindAssets("t:Model", searchRoots);
            List<string> paths = new List<string>(modelGuids.Length);
            HashSet<string> uniquePaths = new HashSet<string>(modelGuids.Length, StringComparer.Ordinal);

            for (int i = 0; i < modelGuids.Length; i++)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(modelGuids[i]);
                if (!IsManagedModelAsset(assetPath) || !uniquePaths.Add(assetPath))
                    continue;

                paths.Add(assetPath);
            }

            paths.Sort(StringComparer.Ordinal);
            return paths;
        }

        internal static List<string> ReimportFbxAssets(string[] searchRoots)
        {
            List<string> fbxPaths = CollectFbxPaths(searchRoots);

            try
            {
                for (int i = 0; i < fbxPaths.Count; i++)
                {
                    string assetPath = fbxPaths[i];
                    EditorUtility.DisplayProgressBar(
                        "HECTON-8 Model Reimport",
                        assetPath,
                        fbxPaths.Count > 0 ? (i + 1f) / fbxPaths.Count : 1f);
                    AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
                }
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            return fbxPaths;
        }

        private void OnPreprocessModel()
        {
            ModelImporter importer = assetImporter as ModelImporter;
            if (importer == null || !IsManagedModelAsset(assetPath))
                return;

            ApplyImporterPolicy(importer);
        }

        private void OnPostprocessModel(GameObject importedRoot)
        {
            if (importedRoot == null || !IsManagedModelAsset(assetPath))
                return;

            NormalizeImportedRootName(importedRoot);

            MeshFilter[] meshFilters = importedRoot.GetComponentsInChildren<MeshFilter>(true);
            int totalTriangles = 0;
            for (int i = 0; i < meshFilters.Length; i++)
            {
                Mesh mesh = meshFilters[i] != null ? meshFilters[i].sharedMesh : null;
                if (mesh != null)
                {
                    for (int subMeshIndex = 0; subMeshIndex < mesh.subMeshCount; subMeshIndex++)
                        totalTriangles += (int)(mesh.GetIndexCount(subMeshIndex) / 3);
                }
                RepairMesh(mesh);
            }

            if (totalTriangles > AutoLodTriangleThreshold && importedRoot.GetComponentInChildren<LODGroup>(true) == null)
            {
                if (TryCreateFallbackLodGroup(importedRoot))
                {
                    Debug.LogWarning($"[HectonFBXPostprocessor] Auto-generated LOD1/LOD2 fallback for high-poly model: {assetPath} (Tris: {totalTriangles}).");
                }
                else
                {
                    Debug.LogWarning($"[CRITICAL WARNING] High-poly mesh (>{AutoLodTriangleThreshold} tris) without LOD Group and no valid renderers for fallback authoring: {assetPath} (Tris: {totalTriangles})");
                }
            }

            SkinnedMeshRenderer[] skinnedRenderers = importedRoot.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            for (int i = 0; i < skinnedRenderers.Length; i++)
                RepairMesh(skinnedRenderers[i] != null ? skinnedRenderers[i].sharedMesh : null);

            if (HectonBakeryUvAudit.TryValidateImportedModelUv2(importedRoot, assetPath, out string uvFailure))
            {
                throw new InvalidOperationException("[HectonFBXPostprocessor] " + uvFailure);
            }
        }

        private static bool TryCreateFallbackLodGroup(GameObject importedRoot)
        {
            if (importedRoot == null)
                return false;

            MeshFilter[] meshFilters = importedRoot.GetComponentsInChildren<MeshFilter>(true);
            List<Renderer> lod0Renderers = new List<Renderer>(meshFilters.Length);
            List<Renderer> lod1Renderers = new List<Renderer>(meshFilters.Length);
            List<Renderer> lod2Renderers = new List<Renderer>(meshFilters.Length);

            for (int i = 0; i < meshFilters.Length; i++)
            {
                MeshFilter sourceFilter = meshFilters[i];
                if (sourceFilter == null || sourceFilter.sharedMesh == null)
                    continue;

                MeshRenderer sourceRenderer = sourceFilter.GetComponent<MeshRenderer>();
                if (sourceRenderer == null || !sourceRenderer.enabled)
                    continue;

                lod0Renderers.Add(sourceRenderer);
                Mesh lod1Mesh = HectonEditorMeshUtility.BuildDecimatedMesh(
                    sourceFilter.sharedMesh,
                    AutoGeneratedLod1TriangleRatio,
                    0,
                    sourceFilter.sharedMesh.name + "_AUTO_LOD1");
                Mesh lod2Mesh = HectonEditorMeshUtility.BuildDecimatedMesh(
                    sourceFilter.sharedMesh,
                    AutoGeneratedLod2TriangleRatio,
                    0,
                    sourceFilter.sharedMesh.name + "_AUTO_LOD2");

                if (lod1Mesh != null)
                    lod1Renderers.Add(CreateLodRenderer(sourceFilter, sourceRenderer, lod1Mesh, "__AUTO_LOD1"));
                if (lod2Mesh != null)
                    lod2Renderers.Add(CreateLodRenderer(sourceFilter, sourceRenderer, lod2Mesh, "__AUTO_LOD2"));
            }

            if (lod0Renderers.Count <= 0 || lod1Renderers.Count <= 0 || lod2Renderers.Count <= 0)
                return false;

            LODGroup lodGroup = importedRoot.GetComponent<LODGroup>();
            if (lodGroup == null)
                lodGroup = importedRoot.AddComponent<LODGroup>();

            LOD[] lods =
            {
                new LOD(AutoGeneratedLod0ScreenRelativeHeight, lod0Renderers.ToArray())
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                },
                new LOD(AutoGeneratedLod1ScreenRelativeHeight, lod1Renderers.ToArray())
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                },
                new LOD(AutoGeneratedLod2ScreenRelativeHeight, lod2Renderers.ToArray())
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                }
            };
            lodGroup.fadeMode = LODFadeMode.CrossFade;
            lodGroup.animateCrossFading = false;
            lodGroup.SetLODs(lods);
            lodGroup.RecalculateBounds();
            EditorUtility.SetDirty(importedRoot);
            return true;
        }

        private static MeshRenderer CreateLodRenderer(
            MeshFilter sourceFilter,
            MeshRenderer sourceRenderer,
            Mesh mesh,
            string suffix)
        {
            GameObject lodObject = new GameObject(sourceFilter.gameObject.name + suffix);
            Transform sourceTransform = sourceFilter.transform;
            Transform lodTransform = lodObject.transform;
            if (sourceTransform.parent != null)
            {
                lodTransform.SetParent(sourceTransform.parent, false);
                lodTransform.localPosition = sourceTransform.localPosition;
                lodTransform.localRotation = sourceTransform.localRotation;
                lodTransform.localScale = sourceTransform.localScale;
            }
            else
            {
                lodTransform.SetParent(sourceTransform, false);
                lodTransform.localPosition = Vector3.zero;
                lodTransform.localRotation = Quaternion.identity;
                lodTransform.localScale = Vector3.one;
            }

            MeshFilter lodFilter = lodObject.AddComponent<MeshFilter>();
            lodFilter.sharedMesh = mesh;

            MeshRenderer lodRenderer = lodObject.AddComponent<MeshRenderer>();
            lodRenderer.sharedMaterials = sourceRenderer.sharedMaterials;
            lodRenderer.lightProbeUsage = sourceRenderer.lightProbeUsage;
            lodRenderer.reflectionProbeUsage = sourceRenderer.reflectionProbeUsage;
            lodRenderer.shadowCastingMode = sourceRenderer.shadowCastingMode;
            lodRenderer.receiveShadows = sourceRenderer.receiveShadows;
            lodRenderer.motionVectorGenerationMode = sourceRenderer.motionVectorGenerationMode;
            return lodRenderer;
        }

        internal static bool ApplyImporterPolicy(ModelImporter importer)
        {
            if (importer == null)
                return false;

            bool changed = false;
            bool isScifiFacilityModel = IsUnderRoot(importer.assetPath, ScifiFacilityRoot);
            if (importer.materialLocation != ModelImporterMaterialLocation.InPrefab)
            {
                importer.materialLocation = ModelImporterMaterialLocation.InPrefab;
                changed = true;
            }

            if (importer.isReadable)
            {
                importer.isReadable = false;
                changed = true;
            }

            if (importer.importBlendShapes)
            {
                importer.importBlendShapes = false;
                changed = true;
            }

            if (importer.importVisibility)
            {
                importer.importVisibility = false;
                changed = true;
            }

            if (importer.importCameras)
            {
                importer.importCameras = false;
                changed = true;
            }

            if (isScifiFacilityModel)
            {
                if (importer.importNormals != ModelImporterNormals.Calculate)
                {
                    importer.importNormals = ModelImporterNormals.Calculate;
                    changed = true;
                }
                if (!Mathf.Approximately(importer.normalSmoothingAngle, ScifiFacilityNormalSmoothingAngle))
                {
                    importer.normalSmoothingAngle = ScifiFacilityNormalSmoothingAngle;
                    changed = true;
                }
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
                if (!importer.weldVertices)
                {
                    importer.weldVertices = true;
                    changed = true;
                }
            }
            else
            {
                if (importer.importNormals != ModelImporterNormals.Calculate)
                {
                    importer.importNormals = ModelImporterNormals.Calculate;
                    changed = true;
                }
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
            }

            if (importer.generateSecondaryUV)
            {
                if (!Mathf.Approximately(importer.secondaryUVHardAngle, DeterministicSecondaryUvHardAngle))
                {
                    importer.secondaryUVHardAngle = DeterministicSecondaryUvHardAngle;
                    changed = true;
                }

                if (!Mathf.Approximately(importer.secondaryUVAngleDistortion, DeterministicSecondaryUvAngleDistortion))
                {
                    importer.secondaryUVAngleDistortion = DeterministicSecondaryUvAngleDistortion;
                    changed = true;
                }

                if (!Mathf.Approximately(importer.secondaryUVAreaDistortion, DeterministicSecondaryUvAreaDistortion))
                {
                    importer.secondaryUVAreaDistortion = DeterministicSecondaryUvAreaDistortion;
                    changed = true;
                }

                if (importer.secondaryUVPackMargin != DeterministicSecondaryUvPackMargin)
                {
                    importer.secondaryUVPackMargin = DeterministicSecondaryUvPackMargin;
                    changed = true;
                }
            }

            if (isScifiFacilityModel && importer.meshCompression != ModelImporterMeshCompression.Medium)
            {
                importer.meshCompression = ModelImporterMeshCompression.Medium;
                changed = true;
            }

            return changed;
        }

        private void NormalizeImportedRootName(GameObject importedRoot)
        {
            if (importedRoot == null || !IsUnderRoot(assetPath, ScifiFacilityRoot))
                return;

            string assetName = System.IO.Path.GetFileNameWithoutExtension(assetPath);
            if (string.IsNullOrEmpty(assetName) ||
                string.Equals(importedRoot.name, assetName, StringComparison.Ordinal))
            {
                return;
            }

            importedRoot.name = assetName;
            EditorUtility.SetDirty(importedRoot);
        }

        private static void RepairMesh(Mesh mesh)
        {
            if (mesh == null)
                return;

            int vertexCount = mesh.vertexCount;
            if (vertexCount <= 0)
            {
                mesh.SetNormals(EmptyVertices);
                mesh.SetTangents(EmptyTangents);
                EditorUtility.SetDirty(mesh);
                return;
            }

            bool missingNormals = !mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.Normal);
            if (missingNormals)
                mesh.RecalculateNormals();

            bool missingTangents = !mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.Tangent);
            bool hasUv0 = mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.TexCoord0);
            if (missingTangents && hasUv0)
                mesh.RecalculateTangents();

            if (missingNormals || (missingTangents && hasUv0))
                EditorUtility.SetDirty(mesh);
        }

        private static bool IsManagedModelAsset(string path)
        {
            if (string.IsNullOrEmpty(path))
                return false;

            string normalizedPath = path.Replace('\\', '/');
            for (int i = 0; i < ManagedFbxRoots.Length; i++)
            {
                if (IsUnderRoot(normalizedPath, ManagedFbxRoots[i]))
                    return true;
            }

            return false;
        }

        private static bool ImporterMatchesScifiFacilityPolicy(ModelImporter importer)
        {
            if (importer == null || !IsUnderRoot(importer.assetPath, ScifiFacilityRoot))
                return false;

            return !importer.isReadable &&
                   !importer.importBlendShapes &&
                   !importer.importVisibility &&
                   !importer.importCameras &&
                   importer.materialLocation == ModelImporterMaterialLocation.InPrefab &&
                   importer.importNormals == ModelImporterNormals.Calculate &&
                   Mathf.Approximately(importer.normalSmoothingAngle, ScifiFacilityNormalSmoothingAngle) &&
                   importer.importTangents == ModelImporterTangents.CalculateMikk &&
                   importer.weldVertices &&
                   importer.meshCompression == ModelImporterMeshCompression.Medium;
        }

        private static bool IsUnderRoot(string path, string root)
        {
            if (string.IsNullOrEmpty(path) || string.IsNullOrEmpty(root))
                return false;

            string normalizedPath = path.Replace('\\', '/');
            string normalizedRoot = root.Replace('\\', '/');
            return normalizedPath.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase);
        }
    }
}
#endif
