#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Hecton8.Editor
{
    /// <summary>
    /// Enforces HECTON-8 managed model import policy and exposes bulk reimport actions for legacy content.
    /// </summary>
    internal sealed class HectonFBXPostprocessor : AssetPostprocessor
    {
        internal const string ProjectArtRoot = "Assets/_Project/Art";
        internal const string PrologueModelRoot = "Assets/_Project/_PROLOGUE_CONTENT/Models";
        internal const string ScifiFacilityRoot = "Assets/ScifiFacility";
        internal static readonly string[] ManagedFbxRoots =
        {
            ProjectArtRoot,
            PrologueModelRoot,
            ScifiFacilityRoot
        };
        private const float ScifiFacilityNormalSmoothingAngle = 60f;
        private const float DeterministicSecondaryUvHardAngle = 88f;
        private const float DeterministicSecondaryUvAngleDistortion = 8f;
        private const float DeterministicSecondaryUvAreaDistortion = 15f;
        private const int DeterministicSecondaryUvPackMargin = 4;
        private const int AutoLodTriangleThreshold = 50000;
        private const float AutoGeneratedLod0ScreenRelativeHeight = 0.6f;
        private const float AutoGeneratedLodFadeWidth = 0.15f;

        private static readonly Vector3[] EmptyVertices = Array.Empty<Vector3>();
        private static readonly Vector2[] EmptyUv = Array.Empty<Vector2>();
        private static readonly Vector4[] EmptyTangents = Array.Empty<Vector4>();

        [MenuItem("Hecton/Validation/Asset Pipeline/Reimport FBX - Assets Project Art", priority = 180)]
        private static void ReimportProjectArtFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(new[] { ProjectArtRoot });
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under '{ProjectArtRoot}'.");
        }

        [MenuItem("Hecton/Validation/Asset Pipeline/Reimport FBX - ScifiFacility", priority = 181)]
        private static void ReimportScifiFacilityFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(new[] { ScifiFacilityRoot });
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under '{ScifiFacilityRoot}'.");
        }

        [MenuItem("Hecton/Validation/Asset Pipeline/Reimport FBX - Managed Roots", priority = 182)]
        private static void ReimportManagedRootsFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(ManagedFbxRoots);
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under the managed roots.");
        }

        [MenuItem("Hecton/Validation/Asset Pipeline/Validate FBX - ScifiFacility", priority = 183)]
        private static void ValidateScifiFacilityFbxPolicy()
        {
            List<string> fbxPaths = CollectFbxPaths(new[] { ScifiFacilityRoot });
            int mismatchCount = 0;

            for (int i = 0; i < fbxPaths.Count; i++)
            {
                ModelImporter importer = AssetImporter.GetAtPath(fbxPaths[i]) as ModelImporter;
                if (!ImporterMatchesScifiFacilityPolicy(importer))
                {
                    mismatchCount++;
                    Debug.LogError($"[HectonFBXPostprocessor] ScifiFacility importer policy drift: '{fbxPaths[i]}'.");
                }
            }

            if (mismatchCount <= 0)
            {
                Debug.Log($"[HectonFBXPostprocessor] Validated {fbxPaths.Count} ScifiFacility FBX assets. No importer drift detected.");
                return;
            }

            Debug.LogError($"[HectonFBXPostprocessor] Found {mismatchCount} ScifiFacility FBX assets with importer drift.");
        }

        internal static List<string> CollectFbxPaths(string[] searchRoots)
        {
            string[] modelGuids = AssetDatabase.FindAssets("t:Model", searchRoots);
            List<string> paths = new List<string>(modelGuids.Length);
            HashSet<string> uniquePaths = new HashSet<string>(StringComparer.Ordinal);

            for (int i = 0; i < modelGuids.Length; i++)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(modelGuids[i]);
                if (!IsManagedModelAsset(assetPath) || !uniquePaths.Add(assetPath))
                    continue;

                paths.Add(assetPath);
            }

            paths.Sort(StringComparer.Ordinal);
            return paths;
        }

        internal static List<string> ReimportFbxAssets(string[] searchRoots)
        {
            List<string> fbxPaths = CollectFbxPaths(searchRoots);

            try
            {
                for (int i = 0; i < fbxPaths.Count; i++)
                {
                    string assetPath = fbxPaths[i];
                    EditorUtility.DisplayProgressBar(
                        "HECTON-8 Model Reimport",
                        assetPath,
                        fbxPaths.Count > 0 ? (i + 1f) / fbxPaths.Count : 1f);
                    AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
                }
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            return fbxPaths;
        }

        private void OnPreprocessModel()
        {
            ModelImporter importer = assetImporter as ModelImporter;
            if (importer == null || !IsManagedModelAsset(assetPath))
                return;

            ApplyImporterPolicy(importer);
        }

        private void OnPostprocessModel(GameObject importedRoot)
        {
            if (importedRoot == null || !IsManagedModelAsset(assetPath))
                return;

            NormalizeImportedRootName(importedRoot);

            MeshFilter[] meshFilters = importedRoot.GetComponentsInChildren<MeshFilter>(true);
            int totalTriangles = 0;
            for (int i = 0; i < meshFilters.Length; i++)
            {
                Mesh mesh = meshFilters[i] != null ? meshFilters[i].sharedMesh : null;
                if (mesh != null)
                {
                    for (int subMeshIndex = 0; subMeshIndex < mesh.subMeshCount; subMeshIndex++)
                        totalTriangles += (int)(mesh.GetIndexCount(subMeshIndex) / 3);
                }
                RepairMesh(mesh);
            }

            if (totalTriangles > AutoLodTriangleThreshold && importedRoot.GetComponentInChildren<LODGroup>(true) == null)
            {
                if (TryCreateFallbackLodGroup(importedRoot))
                {
                    Debug.LogWarning($"[HectonFBXPostprocessor] Auto-generated fallback LODGroup for high-poly model: {assetPath} (Tris: {totalTriangles}).");
                }
                else
                {
                    Debug.LogWarning($"[CRITICAL WARNING] High-poly mesh (>{AutoLodTriangleThreshold} tris) without LOD Group and no valid renderers for fallback authoring: {assetPath} (Tris: {totalTriangles})");
                }
            }

            SkinnedMeshRenderer[] skinnedRenderers = importedRoot.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            for (int i = 0; i < skinnedRenderers.Length; i++)
                RepairMesh(skinnedRenderers[i] != null ? skinnedRenderers[i].sharedMesh : null);
        }

        private static bool TryCreateFallbackLodGroup(GameObject importedRoot)
        {
            if (importedRoot == null)
                return false;

            MeshRenderer[] meshRenderers = importedRoot.GetComponentsInChildren<MeshRenderer>(true);
            SkinnedMeshRenderer[] skinnedMeshRenderers = importedRoot.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            int rendererCount = 0;

            for (int i = 0; i < meshRenderers.Length; i++)
            {
                if (meshRenderers[i] != null && meshRenderers[i].enabled)
                    rendererCount++;
            }

            for (int i = 0; i < skinnedMeshRenderers.Length; i++)
            {
                if (skinnedMeshRenderers[i] != null && skinnedMeshRenderers[i].enabled)
                    rendererCount++;
            }

            if (rendererCount <= 0)
                return false;

            Renderer[] lod0Renderers = new Renderer[rendererCount];
            int writeIndex = 0;

            for (int i = 0; i < meshRenderers.Length; i++)
            {
                MeshRenderer renderer = meshRenderers[i];
                if (renderer == null || !renderer.enabled)
                    continue;

                lod0Renderers[writeIndex++] = renderer;
            }

            for (int i = 0; i < skinnedMeshRenderers.Length; i++)
            {
                SkinnedMeshRenderer renderer = skinnedMeshRenderers[i];
                if (renderer == null || !renderer.enabled)
                    continue;

                lod0Renderers[writeIndex++] = renderer;
            }

            if (writeIndex <= 0)
                return false;

            LODGroup lodGroup = importedRoot.GetComponent<LODGroup>();
            if (lodGroup == null)
                lodGroup = importedRoot.AddComponent<LODGroup>();

            LOD[] lods =
            {
                new LOD(AutoGeneratedLod0ScreenRelativeHeight, lod0Renderers)
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                }
            };
            lodGroup.fadeMode = LODFadeMode.CrossFade;
            lodGroup.animateCrossFading = false;
            lodGroup.SetLODs(lods);
            lodGroup.RecalculateBounds();
            EditorUtility.SetDirty(importedRoot);
            return true;
        }

        internal static bool ApplyImporterPolicy(ModelImporter importer)
        {
            if (importer == null)
                return false;

            bool changed = false;
            bool isScifiFacilityModel = IsUnderRoot(importer.assetPath, ScifiFacilityRoot);
            if (importer.materialLocation != ModelImporterMaterialLocation.InPrefab)
            {
                importer.materialLocation = ModelImporterMaterialLocation.InPrefab;
                changed = true;
            }

            if (isScifiFacilityModel)
            {
                if (importer.importNormals != ModelImporterNormals.Calculate)
                {
                    importer.importNormals = ModelImporterNormals.Calculate;
                    changed = true;
                }
                if (!Mathf.Approximately(importer.normalSmoothingAngle, ScifiFacilityNormalSmoothingAngle))
                {
                    importer.normalSmoothingAngle = ScifiFacilityNormalSmoothingAngle;
                    changed = true;
                }
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
                if (!importer.weldVertices)
                {
                    importer.weldVertices = true;
                    changed = true;
                }
            }
            else
            {
                if (importer.importNormals != ModelImporterNormals.Calculate)
                {
                    importer.importNormals = ModelImporterNormals.Calculate;
                    changed = true;
                }
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
            }

            if (importer.generateSecondaryUV)
            {
                if (!Mathf.Approximately(importer.secondaryUVHardAngle, DeterministicSecondaryUvHardAngle))
                {
                    importer.secondaryUVHardAngle = DeterministicSecondaryUvHardAngle;
                    changed = true;
                }

                if (!Mathf.Approximately(importer.secondaryUVAngleDistortion, DeterministicSecondaryUvAngleDistortion))
                {
                    importer.secondaryUVAngleDistortion = DeterministicSecondaryUvAngleDistortion;
                    changed = true;
                }

                if (!Mathf.Approximately(importer.secondaryUVAreaDistortion, DeterministicSecondaryUvAreaDistortion))
                {
                    importer.secondaryUVAreaDistortion = DeterministicSecondaryUvAreaDistortion;
                    changed = true;
                }

                if (importer.secondaryUVPackMargin != DeterministicSecondaryUvPackMargin)
                {
                    importer.secondaryUVPackMargin = DeterministicSecondaryUvPackMargin;
                    changed = true;
                }
            }

            if (isScifiFacilityModel && importer.meshCompression != ModelImporterMeshCompression.Medium)
            {
                importer.meshCompression = ModelImporterMeshCompression.Medium;
                changed = true;
            }

            return changed;
        }

        private void NormalizeImportedRootName(GameObject importedRoot)
        {
            if (importedRoot == null || !IsUnderRoot(assetPath, ScifiFacilityRoot))
                return;

            string assetName = System.IO.Path.GetFileNameWithoutExtension(assetPath);
            if (string.IsNullOrEmpty(assetName) ||
                string.Equals(importedRoot.name, assetName, StringComparison.Ordinal))
            {
                return;
            }

            importedRoot.name = assetName;
            EditorUtility.SetDirty(importedRoot);
        }

        private static void RepairMesh(Mesh mesh)
        {
            if (mesh == null)
                return;

            int vertexCount = mesh.vertexCount;
            if (vertexCount <= 0)
            {
                mesh.SetNormals(EmptyVertices);
                mesh.tangents = EmptyTangents;
                EditorUtility.SetDirty(mesh);
                return;
            }

            bool missingNormals = !mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.Normal);
            if (missingNormals)
                mesh.RecalculateNormals();

            Vector4[] tangents = mesh.tangents;
            Vector2[] uv = mesh.uv ?? EmptyUv;
            bool missingTangents = tangents == null || tangents.Length != vertexCount;
            if (missingTangents && uv.Length == vertexCount)
                mesh.RecalculateTangents();

            if (missingNormals || (missingTangents && uv.Length == vertexCount))
                EditorUtility.SetDirty(mesh);
        }

        private static bool IsManagedModelAsset(string path)
        {
            if (string.IsNullOrEmpty(path))
                return false;

            string normalizedPath = path.Replace('\\', '/');
            for (int i = 0; i < ManagedFbxRoots.Length; i++)
            {
                if (IsUnderRoot(normalizedPath, ManagedFbxRoots[i]))
                    return true;
            }

            return false;
        }

        private static bool ImporterMatchesScifiFacilityPolicy(ModelImporter importer)
        {
            if (importer == null || !IsUnderRoot(importer.assetPath, ScifiFacilityRoot))
                return false;

            return importer.importNormals == ModelImporterNormals.Calculate &&
                   Mathf.Approximately(importer.normalSmoothingAngle, ScifiFacilityNormalSmoothingAngle) &&
                   importer.importTangents == ModelImporterTangents.CalculateMikk &&
                   importer.weldVertices;
        }

        private static bool IsUnderRoot(string path, string root)
        {
            if (string.IsNullOrEmpty(path) || string.IsNullOrEmpty(root))
                return false;

            string normalizedPath = path.Replace('\\', '/');
            string normalizedRoot = root.Replace('\\', '/');
            return normalizedPath.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase);
        }
    }
}
#endif
