#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using Hecton8.Editor;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

namespace Hecton8.Editor
{
    /// <summary>
    /// Enforces HECTON-8 managed model import policy and exposes bulk reimport actions for legacy content.
    /// </summary>
    internal sealed class HectonFBXPostprocessor : AssetPostprocessor
    {
        internal const string ProjectArtRoot = "Assets/_Project/Art";
        internal const string PrologueModelRoot = "Assets/_Project/_PROLOGUE_CONTENT/Models";
        internal const string ScifiFacilityRoot = "Assets/ScifiFacility";
        internal static readonly string[] ManagedFbxRoots =
        {
            ProjectArtRoot,
            PrologueModelRoot,
            ScifiFacilityRoot
        };
        private const float ScifiFacilityNormalSmoothingAngle = 60f;
        private const float DeterministicSecondaryUvHardAngle = 88f;
        private const float DeterministicSecondaryUvAngleDistortion = 8f;
        private const float DeterministicSecondaryUvAreaDistortion = 15f;
        private const int DeterministicSecondaryUvPackMargin = 4;
        private const int AutoLodTriangleThreshold = 2000;
        private const float AutoGeneratedLod0ScreenRelativeHeight = 0.6f;
        private const float AutoGeneratedLod1ScreenRelativeHeight = 0.15f;
        private const float AutoGeneratedLod2ScreenRelativeHeight = 0.04f;
        private const float AutoGeneratedLodFadeWidth = 0.12f;
        private const float AutoGeneratedLod1TriangleRatio = 0.5f;
        private const float AutoGeneratedLod2TriangleRatio = 0.1f;

        /// <summary>
        /// Manifest schema id written by the offline Blender forge
        /// (<c>Tools/Blender/h8forge/export_unity.py</c> <c>MANIFEST_SCHEMA</c>). A sibling JSON must declare
        /// this literal before any part of the managed import policy is relaxed for the FBX beside it.
        /// </summary>
        internal const string ForgeManifestSchema = "h8forge.manifest/1";
        /// <summary>
        /// Forge FBX file-name prefix from <c>law.NAME_MESH</c> ("MESH_{family}_{name}_LOD{lod}"); the
        /// generators write the package file as <c>MESH_{family}_{name}.fbx</c>. The trailing underscore is
        /// load-bearing: it is what separates a forge package from an unrelated name such as
        /// <c>Meshy_AI_Alien_barnacles_clust_0301230506_texture.fbx</c>.
        /// </summary>
        private const string ForgeMeshFilePrefix = "MESH_";
        /// <summary>Forge manifest file-name prefix from <c>law.NAME_MANIFEST</c>.</summary>
        private const string ForgeManifestFilePrefix = "MANIFEST_";
        private const string ForgeFbxExtension = ".fbx";
        private const string ForgeManifestExtension = ".json";
        private const string ForgeImportNormalsImportToken = "Import";
        private const string ForgeMaterialImportModeNoneToken = "None";
        private const float ForgeMinNormalSmoothingAngle = 0f;
        private const float ForgeMaxNormalSmoothingAngle = 180f;

        private static readonly List<Vector3> EmptyVertices = new List<Vector3>(0);
        private static readonly List<Vector4> EmptyTangents = new List<Vector4>(0);

        [MenuItem("Hecton8/Validation/Asset Pipeline/Reimport FBX - Assets Project Art", priority = 180)]
        private static void ReimportProjectArtFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(new[] { ProjectArtRoot });
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under '{ProjectArtRoot}'.");
        }

        [MenuItem("Hecton8/Validation/Asset Pipeline/Reimport FBX - ScifiFacility", priority = 181)]
        private static void ReimportScifiFacilityFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(new[] { ScifiFacilityRoot });
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under '{ScifiFacilityRoot}'.");
        }

        [MenuItem("Hecton8/Validation/Asset Pipeline/Reimport FBX - Managed Roots", priority = 182)]
        private static void ReimportManagedRootsFbx()
        {
            List<string> reimportedPaths = ReimportFbxAssets(ManagedFbxRoots);
            Debug.Log($"[HectonFBXPostprocessor] Reimported {reimportedPaths.Count} FBX assets under the managed roots.");
        }

        [MenuItem("Hecton8/Validation/Asset Pipeline/Validate FBX - ScifiFacility", priority = 183)]
        private static void ValidateScifiFacilityFbxPolicy()
        {
            List<string> fbxPaths = CollectFbxPaths(new[] { ScifiFacilityRoot });
            int mismatchCount = 0;

            for (int i = 0; i < fbxPaths.Count; i++)
            {
                ModelImporter importer = AssetImporter.GetAtPath(fbxPaths[i]) as ModelImporter;
                if (!ImporterMatchesScifiFacilityPolicy(importer))
                {
                    mismatchCount++;
                    Debug.LogError($"[HectonFBXPostprocessor] ScifiFacility importer policy drift: '{fbxPaths[i]}'.");
                }
            }

            if (mismatchCount <= 0)
            {
                Debug.Log($"[HectonFBXPostprocessor] Validated {fbxPaths.Count} ScifiFacility FBX assets. No importer drift detected.");
                return;
            }

            Debug.LogError($"[HectonFBXPostprocessor] Found {mismatchCount} ScifiFacility FBX assets with importer drift.");
        }

        internal static List<string> CollectFbxPaths(string[] searchRoots)
        {
            string[] modelGuids = AssetDatabase.FindAssets("t:Model", searchRoots);
            List<string> paths = new List<string>(modelGuids.Length);
            HashSet<string> uniquePaths = new HashSet<string>(modelGuids.Length, StringComparer.Ordinal);

            for (int i = 0; i < modelGuids.Length; i++)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(modelGuids[i]);
                if (!IsManagedModelAsset(assetPath) || !uniquePaths.Add(assetPath))
                    continue;

                paths.Add(assetPath);
            }

            paths.Sort(StringComparer.Ordinal);
            return paths;
        }

        internal static List<string> ReimportFbxAssets(string[] searchRoots)
        {
            List<string> fbxPaths = CollectFbxPaths(searchRoots);

            try
            {
                for (int i = 0; i < fbxPaths.Count; i++)
                {
                    string assetPath = fbxPaths[i];
                    EditorUtility.DisplayProgressBar(
                        "HECTON-8 Model Reimport",
                        assetPath,
                        fbxPaths.Count > 0 ? (i + 1f) / fbxPaths.Count : 1f);
                    AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
                }
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            return fbxPaths;
        }

        private void OnPreprocessModel()
        {
            ModelImporter importer = assetImporter as ModelImporter;
            if (importer == null || !IsManagedModelAsset(assetPath))
                return;

            ApplyImporterPolicy(importer);
        }

        private void OnPostprocessModel(GameObject importedRoot)
        {
            if (importedRoot == null || !IsManagedModelAsset(assetPath))
                return;

            NormalizeImportedRootName(importedRoot);

            MeshFilter[] meshFilters = importedRoot.GetComponentsInChildren<MeshFilter>(true);
            int totalTriangles = 0;
            for (int i = 0; i < meshFilters.Length; i++)
            {
                Mesh mesh = meshFilters[i] != null ? meshFilters[i].sharedMesh : null;
                if (mesh != null)
                {
                    for (int subMeshIndex = 0; subMeshIndex < mesh.subMeshCount; subMeshIndex++)
                        totalTriangles += (int)(mesh.GetIndexCount(subMeshIndex) / 3);
                }
                RepairMesh(mesh);
            }

            if (totalTriangles > AutoLodTriangleThreshold && importedRoot.GetComponentInChildren<LODGroup>(true) == null)
            {
                bool hasForgeContract = TryResolveForgeImportContract(assetPath, out ForgeImportContract forgeContract);
                if (hasForgeContract && forgeContract.AuthoredLodLevelCount > 1)
                {
                    // The package already authored its own chain, so decimating LOD0 into __AUTO_LOD1/
                    // __AUTO_LOD2 would ship five LODs where the manifest declares three, and would decimate
                    // the COL_ collision proxy along with them. 3dmodel.md section 7 owns the chain; the
                    // Unity-side authoring pass owns binding it to an LODGroup, which no importer can do from
                    // the FBX alone. LogError, not throw: the asset must still import so that pass can run.
                    Debug.LogError(
                        "[HectonFBXPostprocessor] Forge package '" + assetPath + "' declares " +
                        forgeContract.AuthoredLodLevelCount + " authored LOD levels in manifest '" +
                        forgeContract.ManifestPath + "' but imported without an LODGroup (Tris: " +
                        totalTriangles + "). The auto-decimation fallback is SUPPRESSED so the authored chain " +
                        "is not duplicated. Bind the _LOD<n> children to an LODGroup with fadeMode=CrossFade " +
                        "and animateCrossFading=false through the Unity-side authoring pass, per 3dmodel.md " +
                        "section 7.");
                }
                else if (TryCreateFallbackLodGroup(importedRoot))
                {
                    Debug.LogWarning($"[HectonFBXPostprocessor] Auto-generated LOD1/LOD2 fallback for high-poly model: {assetPath} (Tris: {totalTriangles}).");
                }
                else
                {
                    Debug.LogWarning($"[CRITICAL WARNING] High-poly mesh (>{AutoLodTriangleThreshold} tris) without LOD Group and no valid renderers for fallback authoring: {assetPath} (Tris: {totalTriangles})");
                }
            }

            SkinnedMeshRenderer[] skinnedRenderers = importedRoot.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            for (int i = 0; i < skinnedRenderers.Length; i++)
                RepairMesh(skinnedRenderers[i] != null ? skinnedRenderers[i].sharedMesh : null);

            if (HectonBakeryUvAudit.TryValidateImportedModelUv2(importedRoot, assetPath, out string uvFailure))
            {
                throw new InvalidOperationException("[HectonFBXPostprocessor] " + uvFailure);
            }
        }

        private static bool TryCreateFallbackLodGroup(GameObject importedRoot)
        {
            if (importedRoot == null)
                return false;

            MeshFilter[] meshFilters = importedRoot.GetComponentsInChildren<MeshFilter>(true);
            List<Renderer> lod0Renderers = new List<Renderer>(meshFilters.Length);
            List<Renderer> lod1Renderers = new List<Renderer>(meshFilters.Length);
            List<Renderer> lod2Renderers = new List<Renderer>(meshFilters.Length);

            for (int i = 0; i < meshFilters.Length; i++)
            {
                MeshFilter sourceFilter = meshFilters[i];
                if (sourceFilter == null || sourceFilter.sharedMesh == null)
                    continue;

                MeshRenderer sourceRenderer = sourceFilter.GetComponent<MeshRenderer>();
                if (sourceRenderer == null || !sourceRenderer.enabled)
                    continue;

                lod0Renderers.Add(sourceRenderer);
                Mesh lod1Mesh = HectonEditorMeshUtility.BuildDecimatedMesh(
                    sourceFilter.sharedMesh,
                    AutoGeneratedLod1TriangleRatio,
                    0,
                    sourceFilter.sharedMesh.name + "_AUTO_LOD1");
                Mesh lod2Mesh = HectonEditorMeshUtility.BuildDecimatedMesh(
                    sourceFilter.sharedMesh,
                    AutoGeneratedLod2TriangleRatio,
                    0,
                    sourceFilter.sharedMesh.name + "_AUTO_LOD2");

                if (lod1Mesh != null)
                    lod1Renderers.Add(CreateLodRenderer(sourceFilter, sourceRenderer, lod1Mesh, "__AUTO_LOD1"));
                if (lod2Mesh != null)
                    lod2Renderers.Add(CreateLodRenderer(sourceFilter, sourceRenderer, lod2Mesh, "__AUTO_LOD2"));
            }

            if (lod0Renderers.Count <= 0 || lod1Renderers.Count <= 0 || lod2Renderers.Count <= 0)
                return false;

            LODGroup lodGroup = importedRoot.GetComponent<LODGroup>();
            if (lodGroup == null)
                lodGroup = importedRoot.AddComponent<LODGroup>();

            LOD[] lods =
            {
                new LOD(AutoGeneratedLod0ScreenRelativeHeight, lod0Renderers.ToArray())
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                },
                new LOD(AutoGeneratedLod1ScreenRelativeHeight, lod1Renderers.ToArray())
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                },
                new LOD(AutoGeneratedLod2ScreenRelativeHeight, lod2Renderers.ToArray())
                {
                    fadeTransitionWidth = AutoGeneratedLodFadeWidth
                }
            };
            lodGroup.fadeMode = LODFadeMode.CrossFade;
            lodGroup.animateCrossFading = false;
            lodGroup.SetLODs(lods);
            lodGroup.RecalculateBounds();
            EditorUtility.SetDirty(importedRoot);
            return true;
        }

        private static MeshRenderer CreateLodRenderer(
            MeshFilter sourceFilter,
            MeshRenderer sourceRenderer,
            Mesh mesh,
            string suffix)
        {
            GameObject lodObject = new GameObject(sourceFilter.gameObject.name + suffix);
            Transform sourceTransform = sourceFilter.transform;
            Transform lodTransform = lodObject.transform;
            if (sourceTransform.parent != null)
            {
                lodTransform.SetParent(sourceTransform.parent, false);
                lodTransform.localPosition = sourceTransform.localPosition;
                lodTransform.localRotation = sourceTransform.localRotation;
                lodTransform.localScale = sourceTransform.localScale;
            }
            else
            {
                lodTransform.SetParent(sourceTransform, false);
                lodTransform.localPosition = Vector3.zero;
                lodTransform.localRotation = Quaternion.identity;
                lodTransform.localScale = Vector3.one;
            }

            MeshFilter lodFilter = lodObject.AddComponent<MeshFilter>();
            lodFilter.sharedMesh = mesh;

            MeshRenderer lodRenderer = lodObject.AddComponent<MeshRenderer>();
            lodRenderer.sharedMaterials = sourceRenderer.sharedMaterials;
            lodRenderer.lightProbeUsage = sourceRenderer.lightProbeUsage;
            lodRenderer.reflectionProbeUsage = sourceRenderer.reflectionProbeUsage;
            lodRenderer.shadowCastingMode = sourceRenderer.shadowCastingMode;
            lodRenderer.receiveShadows = sourceRenderer.receiveShadows;
            lodRenderer.motionVectorGenerationMode = sourceRenderer.motionVectorGenerationMode;
            return lodRenderer;
        }

        internal static bool ApplyImporterPolicy(ModelImporter importer)
        {
            if (importer == null)
                return false;

            bool changed = false;
            bool isScifiFacilityModel = IsUnderRoot(importer.assetPath, ScifiFacilityRoot);
            bool hasForgeContract = TryResolveForgeImportContract(importer.assetPath, out ForgeImportContract forgeContract);
            if (importer.materialLocation != ModelImporterMaterialLocation.InPrefab)
            {
                importer.materialLocation = ModelImporterMaterialLocation.InPrefab;
                changed = true;
            }

            // The forge ships shared MAT_* assets and strips every texture path out of the FBX
            // (Tools/Blender/generators/kelp.py path_mode="STRIP"; manifest materialSlots names
            // MAT_Flora_tissue and siblings), so letting Unity build materials from the file would create
            // per-model materials and break the shared-material rule in 3dmodel.md section 8. materialLocation
            // above is deliberately left exactly as the project policy sets it: with materialImportMode None
            // there are no imported materials for it to place, so ImporterMatchesScifiFacilityPolicy keeps
            // asserting InPrefab and stays true by construction.
            if (hasForgeContract &&
                forgeContract.SuppressMaterialImport &&
                importer.materialImportMode != ModelImporterMaterialImportMode.None)
            {
                importer.materialImportMode = ModelImporterMaterialImportMode.None;
                changed = true;
            }

            // isReadable was forced false UNCONDITIONALLY here, with no comment stating why. A readable mesh
            // keeps a CPU-side copy resident, so false is the right default across 2740+ FBX and that default
            // is preserved exactly: for every asset that is not a declared VAT source this evaluates to
            // `if (importer.isReadable) importer.isReadable = false;`, which is what the line did before.
            //
            // The carve-out exists because a VAT source is the one case where the CPU copy is the POINT.
            // FaunaHeadlessBake1610 reads Mesh.vertices to build the position/normal pages, and a mesh whose
            // vertex array reads back empty would produce a full-size VAT page of zeros that looks like a
            // successful bake on disk (AbyssalAnatomyStudio1610.VerifyMeshIsReadable refuses exactly that).
            //
            // FAIL CLOSED: `hasForgeContract` is false when no sibling manifest exists, when it cannot be
            // parsed, or when it is under ScifiFacilityRoot (TryResolveForgeManifestPath:715). IsVatSource is
            // granted only by a tier-1 `h8forge.manifest/1` manifest carrying a vatReadiness block with a
            // positive vertexCountLOD0. Any doubt anywhere in that chain lands on today's behaviour.
            //
            // ImporterMatchesScifiFacilityPolicy asserts !isReadable, but that assertion is scoped to
            // ScifiFacilityRoot (:559-561) and the forge carve-out can never apply under that root, so the two
            // sets are disjoint by construction and the vendor policy cannot be weakened from here.
            bool vatSourceNeedsReadableGeometry = hasForgeContract && forgeContract.IsVatSource;
            if (importer.isReadable != vatSourceNeedsReadableGeometry)
            {
                importer.isReadable = vatSourceNeedsReadableGeometry;
                changed = true;
            }

            if (importer.importBlendShapes)
            {
                importer.importBlendShapes = false;
                changed = true;
            }

            if (importer.importVisibility)
            {
                importer.importVisibility = false;
                changed = true;
            }

            if (importer.importCameras)
            {
                importer.importCameras = false;
                changed = true;
            }

            if (isScifiFacilityModel)
            {
                if (importer.importNormals != ModelImporterNormals.Calculate)
                {
                    importer.importNormals = ModelImporterNormals.Calculate;
                    changed = true;
                }
                if (!Mathf.Approximately(importer.normalSmoothingAngle, ScifiFacilityNormalSmoothingAngle))
                {
                    importer.normalSmoothingAngle = ScifiFacilityNormalSmoothingAngle;
                    changed = true;
                }
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
                if (!importer.weldVertices)
                {
                    importer.weldVertices = true;
                    changed = true;
                }
            }
            else if (hasForgeContract && forgeContract.ImportAuthoredNormals)
            {
                // THE conflict this carve-out exists for. mesh_ops.apply_shading_basis bakes 3dmodel.md
                // section 4's weightedNormal(v, group) formula into custom split normals and the generator
                // applies the modifier before export, so the FBX carries an authored basis. Section 3:
                // "RecalculateNormals, RecalculateTangents, and RecalculateBounds are allowed only as editor
                // fallback after a documented failure, never as the default strategy. A generator owns
                // normals, tangents, UVs, and bounds because it owns the geometry." Calculate re-derives them
                // from a single angle and throws every bevel-shading decision away.
                if (importer.importNormals != ModelImporterNormals.Import)
                {
                    importer.importNormals = ModelImporterNormals.Import;
                    changed = true;
                }

                // Inert while importNormals is Import. It is still written when the manifest declares one, so
                // that a forced fallback to Calculate reproduces the authored split from the same dihedral
                // angle the generator used instead of an unrelated one.
                if (forgeContract.NormalSmoothingAngle > ForgeMinNormalSmoothingAngle &&
                    !Mathf.Approximately(importer.normalSmoothingAngle, forgeContract.NormalSmoothingAngle))
                {
                    importer.normalSmoothingAngle = forgeContract.NormalSmoothingAngle;
                    changed = true;
                }

                // Unchanged from the project default on purpose: the forge's own import contract asks for
                // CalculateMikk too, because under MikkTSpace the tangent is fully determined by position,
                // normal and UV0, and no Blender-side round trip can prove the handedness w survives Unity's
                // left-handed flip. This is not one of the conflicts.
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
            }
            else
            {
                if (importer.importNormals != ModelImporterNormals.Calculate)
                {
                    importer.importNormals = ModelImporterNormals.Calculate;
                    changed = true;
                }
                if (importer.importTangents != ModelImporterTangents.CalculateMikk)
                {
                    importer.importTangents = ModelImporterTangents.CalculateMikk;
                    changed = true;
                }
            }

            // Unity's secondary-UV generator OVERWRITES UV1, and 3dmodel.md section 3 makes TexCoord1
            // authored data: "Lightmap, detail, atlas remap, or packed baked masks when required." Forcing it
            // back off here also repairs a package that an earlier HectonBakeryUvAudit pass flipped on, because
            // the FBX still carries the authored channel and the next import reads it again. Only a manifest
            // that explicitly declares generateSecondaryUV=false reaches this branch.
            if (hasForgeContract && forgeContract.SuppressSecondaryUv && importer.generateSecondaryUV)
            {
                importer.generateSecondaryUV = false;
                changed = true;
            }

            if (importer.generateSecondaryUV)
            {
                if (!Mathf.Approximately(importer.secondaryUVHardAngle, DeterministicSecondaryUvHardAngle))
                {
                    importer.secondaryUVHardAngle = DeterministicSecondaryUvHardAngle;
                    changed = true;
                }

                if (!Mathf.Approximately(importer.secondaryUVAngleDistortion, DeterministicSecondaryUvAngleDistortion))
                {
                    importer.secondaryUVAngleDistortion = DeterministicSecondaryUvAngleDistortion;
                    changed = true;
                }

                if (!Mathf.Approximately(importer.secondaryUVAreaDistortion, DeterministicSecondaryUvAreaDistortion))
                {
                    importer.secondaryUVAreaDistortion = DeterministicSecondaryUvAreaDistortion;
                    changed = true;
                }

                if (importer.secondaryUVPackMargin != DeterministicSecondaryUvPackMargin)
                {
                    importer.secondaryUVPackMargin = DeterministicSecondaryUvPackMargin;
                    changed = true;
                }
            }

            // Scoped to the vendor tree ON PURPOSE, and left that way after review. Position quantisation on a
            // VAT source would perturb the very positions the bake samples, but forge assets never reach this
            // line: the guard is isScifiFacilityModel, and MESH_Fauna_Fish_2207_00.fbx.meta:41 carries
            // meshCompression: 0 (Off) on disk, matching its own manifest's declared "meshCompression": "Off".
            // A report that Medium is applied to forge assets is incorrect - there is nothing to carve out.
            if (isScifiFacilityModel && importer.meshCompression != ModelImporterMeshCompression.Medium)
            {
                importer.meshCompression = ModelImporterMeshCompression.Medium;
                changed = true;
            }

            // VAT DURABILITY CONTRACT. Both fields below are declared by every h8forge manifest and, until
            // now, applied by nothing - the manifest's own note says "the importer block disables vertex
            // optimisation and welding", while Unity's defaults (weldVertices true, meshOptimizationFlags
            // Everything) did the opposite. A declared parameter that nothing enforces is the same defect
            // class as a gate that cannot fire.
            //
            // Both change per-vertex IDENTITY, and a baked VAT is indexed by vertexID
            // (BoidFishInstanced.shader:493), so applying either AFTER a VAT exists desynchronises the texture
            // from the mesh and the swarm animates as noise while every null check passes. That is why this is
            // safe to land now and expensive to land later: no VAT has ever been baked in this project.
            //
            // Deliberately NOT inside the isScifiFacilityModel branch above: that root can never hold a forge
            // contract, and ImporterMatchesScifiFacilityPolicy requires weldVertices TRUE for it (:571). The
            // two policies are opposites and must stay on disjoint asset sets.
            if (hasForgeContract && forgeContract.IsVatSource)
            {
                if (importer.weldVertices)
                {
                    importer.weldVertices = false;
                    changed = true;
                }

                // PolygonOrder reorders triangles only, which touches no per-vertex identity. The default
                // Everything additionally reorders VERTICES, which is the one thing a VAT cannot survive.
                if (importer.meshOptimizationFlags != MeshOptimizationFlags.PolygonOrder)
                {
                    importer.meshOptimizationFlags = MeshOptimizationFlags.PolygonOrder;
                    changed = true;
                }
            }

            if (hasForgeContract)
                LogForgeCarveOut(importer.assetPath, forgeContract);

            return changed;
        }

        private void NormalizeImportedRootName(GameObject importedRoot)
        {
            if (importedRoot == null || !IsUnderRoot(assetPath, ScifiFacilityRoot))
                return;

            string assetName = System.IO.Path.GetFileNameWithoutExtension(assetPath);
            if (string.IsNullOrEmpty(assetName) ||
                string.Equals(importedRoot.name, assetName, StringComparison.Ordinal))
            {
                return;
            }

            importedRoot.name = assetName;
            EditorUtility.SetDirty(importedRoot);
        }

        private static void RepairMesh(Mesh mesh)
        {
            if (mesh == null)
                return;

            int vertexCount = mesh.vertexCount;
            if (vertexCount <= 0)
            {
                mesh.SetNormals(EmptyVertices);
                mesh.SetTangents(EmptyTangents);
                EditorUtility.SetDirty(mesh);
                return;
            }

            bool missingNormals = !mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.Normal);
            if (missingNormals)
                mesh.RecalculateNormals();

            bool missingTangents = !mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.Tangent);
            bool hasUv0 = mesh.HasVertexAttribute(UnityEngine.Rendering.VertexAttribute.TexCoord0);
            if (missingTangents && hasUv0)
                mesh.RecalculateTangents();

            if (missingNormals || (missingTangents && hasUv0))
                EditorUtility.SetDirty(mesh);
        }

        private static bool IsManagedModelAsset(string path)
        {
            if (string.IsNullOrEmpty(path))
                return false;

            string normalizedPath = path.Replace('\\', '/');
            for (int i = 0; i < ManagedFbxRoots.Length; i++)
            {
                if (IsUnderRoot(normalizedPath, ManagedFbxRoots[i]))
                    return true;
            }

            return false;
        }

        private static bool ImporterMatchesScifiFacilityPolicy(ModelImporter importer)
        {
            if (importer == null || !IsUnderRoot(importer.assetPath, ScifiFacilityRoot))
                return false;

            return !importer.isReadable &&
                   !importer.importBlendShapes &&
                   !importer.importVisibility &&
                   !importer.importCameras &&
                   importer.materialLocation == ModelImporterMaterialLocation.InPrefab &&
                   importer.importNormals == ModelImporterNormals.Calculate &&
                   Mathf.Approximately(importer.normalSmoothingAngle, ScifiFacilityNormalSmoothingAngle) &&
                   importer.importTangents == ModelImporterTangents.CalculateMikk &&
                   importer.weldVertices &&
                   importer.meshCompression == ModelImporterMeshCompression.Medium;
        }

        /// <summary>
        /// Editor-only carve-out record for one offline Blender forge package. This is not a runtime DTO and it
        /// crosses no native/Burst/persistence/GPU boundary, so managed fields are allowed on it.
        /// </summary>
        internal readonly struct ForgeImportContract
        {
            /// <summary>Project-relative path of the manifest that authorised the carve-out.</summary>
            internal readonly string ManifestPath;
            /// <summary>
            /// True when the manifest carried an explicit <c>unityImport.modelImporter</c> block
            /// (<c>h8forge.manifest/1</c> from <c>h8forge.export_unity.write_manifest</c>). False when
            /// provenance was established from the generator-local manifest shape instead, in which case every
            /// relaxation is derived from a field that manifest genuinely carries and nothing is assumed.
            /// </summary>
            internal readonly bool DeclaredImportContract;
            internal readonly bool ImportAuthoredNormals;
            /// <summary>Authored dihedral smoothing angle, or 0 when the manifest declared none.</summary>
            internal readonly float NormalSmoothingAngle;
            internal readonly bool SuppressSecondaryUv;
            internal readonly bool SuppressMaterialImport;
            internal readonly int AuthoredLodLevelCount;
            /// <summary>
            /// True only when a tier-1 manifest declares a <c>vatReadiness</c> block with a positive
            /// <c>vertexCountLOD0</c>. Gates BOTH the isReadable carve-out and the vertex-identity settings,
            /// because those are the two things a Vertex Animation Texture source needs and nothing else does.
            /// Tier 2 always passes false: a generator-local manifest declares no importer contract at all, so
            /// granting a relaxation from it would be an assumption rather than a reading.
            /// </summary>
            internal readonly bool IsVatSource;

            internal ForgeImportContract(
                string manifestPath,
                bool declaredImportContract,
                bool importAuthoredNormals,
                float normalSmoothingAngle,
                bool suppressSecondaryUv,
                bool suppressMaterialImport,
                int authoredLodLevelCount,
                bool isVatSource)
            {
                ManifestPath = manifestPath;
                DeclaredImportContract = declaredImportContract;
                ImportAuthoredNormals = importAuthoredNormals;
                NormalSmoothingAngle = normalSmoothingAngle;
                SuppressSecondaryUv = suppressSecondaryUv;
                SuppressMaterialImport = suppressMaterialImport;
                AuthoredLodLevelCount = authoredLodLevelCount;
                IsVatSource = isVatSource;
            }
        }

        [Serializable]
        private sealed class ForgeManifestModelImporterBlock
        {
            public string importNormals;
            public float normalSmoothingAngle;
            public bool generateSecondaryUV;
            public string materialImportMode;
        }

        [Serializable]
        private sealed class ForgeManifestUnityImportBlock
        {
            public ForgeManifestModelImporterBlock modelImporter;
        }

        [Serializable]
        private sealed class ForgeManifestExportBlock
        {
            public bool hasCustomNormals;
        }

        [Serializable]
        private sealed class ForgeManifestLodBlock
        {
            public int[] levels;
        }

        [Serializable]
        private sealed class ForgeManifestIdentityBlock
        {
            public string generator;
            public string forgeVersion;
        }

        [Serializable]
        private sealed class ForgeManifestFilesBlock
        {
            public string fbx;
        }

        [Serializable]
        private sealed class ForgeManifestLodEntry
        {
            public int lod;
            public string mesh;
        }

        [Serializable]
        private sealed class ForgeManifestMaterialSlotEntry
        {
            public int slot;
            public string material;
        }

        [Serializable]
        private sealed class ForgeManifestValidationBlock
        {
            public bool allPassed;
        }

        /// <summary>
        /// Union of both manifest shapes the forge writes today. Tier 1 is
        /// <c>h8forge.export_unity.write_manifest</c> (<c>schema</c>, <c>unityImport</c>, <c>export</c>,
        /// <c>lod</c>). Tier 2 is the generator-local shape <c>generators/kelp.py</c> and
        /// <c>generators/rock.py</c> actually emit (<c>identity</c>, <c>files</c>, <c>lods</c>,
        /// <c>materialSlots</c>, <c>validation.allPassed</c>) because neither generator has been migrated onto
        /// the shared exporter yet. The two shapes share no field name, so one reader covers both.
        /// </summary>
        [Serializable]
        private sealed class ForgeManifestFile
        {
            public string schema;
            public ForgeManifestUnityImportBlock unityImport;
            public ForgeManifestExportBlock export;
            public ForgeManifestLodBlock lod;
            public ForgeManifestIdentityBlock identity;
            public ForgeManifestFilesBlock files;
            public ForgeManifestLodEntry[] lods;
            public ForgeManifestMaterialSlotEntry[] materialSlots;
            public ForgeManifestValidationBlock validation;
            public ForgeManifestVatReadinessBlock vatReadiness;
            public ForgeManifestExtraBlock extra;
        }

        /// <summary>
        /// The forge's <c>extra</c> payload. This is where <c>vatReadiness</c> ACTUALLY lands:
        /// <c>export_unity.write_manifest</c> takes a first-class <c>extra</c> keyword (export_unity.py:1908)
        /// and assigns it wholesale (<c>payload["extra"] = extra</c>, :2134-2135), and every family-specific
        /// block goes through it - fauna_fish.py:2214, prop_handtool.py:1682, flora_capstem.py:2611. The
        /// exporter's payload dict offers no root slot for generator blocks at all, so <c>extra</c> is the
        /// sanctioned home and the C# reader was the wrong side of this disagreement.
        /// Only <c>vatReadiness</c> is typed here; JsonUtility drops <c>extra</c>'s heterogeneous siblings
        /// (<c>bodyPlan</c>, <c>consumerContract</c>, strings, arrays) because no field claims them, which is
        /// why this needs no <c>Dictionary</c> - which JsonUtility would not support anyway.
        /// </summary>
        [Serializable]
        private sealed class ForgeManifestExtraBlock
        {
            public ForgeManifestVatReadinessBlock vatReadiness;
        }

        /// <summary>
        /// The <c>vatReadiness</c> block. Its PRESENCE is what identifies a Vertex Animation Texture
        /// source; it is written only by generators whose family animates through a baked VAT. Read it
        /// through <see cref="ResolveVatReadiness"/> rather than off a field directly - the forge nests it
        /// under <c>extra</c>, and only that helper accepts both placements.
        /// </summary>
        /// <remarks>
        /// The carve-out is deliberately NOT keyed on
        /// <c>unityImport.modelImporter.isReadable</c>: the fish manifest declares that field <c>false</c>,
        /// because the forge is describing the shipped runtime state of the asset rather than what an offline
        /// bake needs from it. Honouring that field literally would keep the mesh unreadable and leave the
        /// chain exactly as blocked as before, so the signal has to be "this is a VAT source" rather than
        /// "this asset asked to be readable". Only <c>vertexCountLOD0</c> is deserialised; the block's other
        /// keys are informational and JsonUtility drops what it has no field for.
        /// </remarks>
        [Serializable]
        private sealed class ForgeManifestVatReadinessBlock
        {
            public int vertexCountLOD0;
        }

        /// <summary>
        /// Reads the <c>vatReadiness</c> block from whichever placement the manifest uses.
        /// </summary>
        /// <remarks>
        /// The forge nests it under <c>extra</c> (export_unity.py:2134-2135, fauna_fish.py:2239) while this
        /// reader originally expected it at the root, so <c>IsVatSource</c> was always false and
        /// <c>ReimportVatSourceModel</c> exited 3 - JsonUtility leaves an unmatched field at its default
        /// rather than throwing, so the disagreement was silent rather than diagnosable. Root is preferred so
        /// any manifest already written that way keeps working; <c>extra</c> is the sanctioned home going
        /// forward and is what every current generator emits.
        /// </remarks>
        private static ForgeManifestVatReadinessBlock ResolveVatReadiness(ForgeManifestFile manifest)
        {
            if (manifest == null)
                return null;

            if (manifest.vatReadiness != null)
                return manifest.vatReadiness;

            return manifest.extra != null ? manifest.extra.vatReadiness : null;
        }

        /// <summary>
        /// Maps a managed FBX asset path to the path its sibling forge manifest must occupy, or returns false.
        /// Pure string logic with no file access, so the naming gate is provable without an import.
        /// </summary>
        internal static bool TryResolveForgeManifestPath(string assetPath, out string manifestPath)
        {
            manifestPath = string.Empty;
            if (string.IsNullOrEmpty(assetPath))
                return false;

            string normalizedPath = assetPath.Replace('\\', '/');
            if (!normalizedPath.EndsWith(ForgeFbxExtension, StringComparison.OrdinalIgnoreCase))
                return false;

            // Third-party quarantine can never earn the carve-out. ImporterMatchesScifiFacilityPolicy asserts
            // the strict vendor policy for this root, and a manifest dropped beside a vendor FBX must not be
            // able to weaken it.
            if (IsUnderRoot(normalizedPath, ScifiFacilityRoot))
                return false;

            int lastSlash = normalizedPath.LastIndexOf('/');
            string directory = lastSlash >= 0 ? normalizedPath.Substring(0, lastSlash + 1) : string.Empty;
            string fileName = normalizedPath.Substring(lastSlash + 1);

            // Ordinal and case-sensitive, and the trailing underscore is what carries the gate: law.NAME_MESH
            // writes upper-case "MESH_", so the existing
            // Assets/_Project/Art/Materials/Meshy_AI_Alien_barnacles_clust_0301230506_texture.fbx does not
            // match, and neither does any lower-case variant.
            if (!fileName.StartsWith(ForgeMeshFilePrefix, StringComparison.Ordinal))
                return false;

            int stemLength = fileName.Length - ForgeMeshFilePrefix.Length - ForgeFbxExtension.Length;
            if (stemLength <= 0)
                return false;

            string stem = fileName.Substring(ForgeMeshFilePrefix.Length, stemLength);
            manifestPath = directory + ForgeManifestFilePrefix + stem + ForgeManifestExtension;
            return true;
        }

        /// <summary>
        /// Reads one forge manifest body and derives the carve-out. Pure apart from its error logging, so the
        /// accept/reject decision is provable from a JSON string with no FBX and no import.
        /// </summary>
        internal static bool TryParseForgeImportContract(
            string manifestJson,
            string manifestPath,
            string fbxFileName,
            out ForgeImportContract contract)
        {
            contract = default;
            if (string.IsNullOrEmpty(manifestJson))
                return false;

            ForgeManifestFile manifest;
            try
            {
                manifest = JsonUtility.FromJson<ForgeManifestFile>(manifestJson);
            }
            catch (Exception error)
            {
                // Deliberately broad and deliberately loud. An unhandled exception here aborts the import of a
                // real asset, which is strictly worse than falling back to the unchanged project policy. The
                // failure is never swallowed: without this line a malformed manifest would be indistinguishable
                // from an asset that simply has no manifest.
                Debug.LogError(
                    "[HectonFBXPostprocessor] Forge manifest '" + manifestPath + "' could not be parsed, so " +
                    "the offline import contract is NOT honoured and the strict project policy applies: " +
                    error.GetType().Name + ": " + error.Message);
                return false;
            }

            if (manifest == null)
                return false;

            // -- tier 1: the manifest states the importer contract itself ------------------------------------
            if (string.Equals(manifest.schema, ForgeManifestSchema, StringComparison.Ordinal))
            {
                ForgeManifestModelImporterBlock declared =
                    manifest.unityImport != null ? manifest.unityImport.modelImporter : null;
                if (declared == null)
                {
                    Debug.LogError(
                        "[HectonFBXPostprocessor] Forge manifest '" + manifestPath + "' declares schema '" +
                        ForgeManifestSchema + "' but carries no unityImport.modelImporter block, so there is " +
                        "no import contract to honour and the strict project policy applies.");
                    return false;
                }

                // 3dmodel.md section 3 gives normals to the generator, but only a package that actually wrote
                // custom split normals has anything for Unity to import. Without them, Import would hand the
                // shader whatever the file happens to hold and Calculate is the honest strategy.
                bool authoredNormals =
                    string.Equals(declared.importNormals, ForgeImportNormalsImportToken, StringComparison.Ordinal) &&
                    manifest.export != null &&
                    manifest.export.hasCustomNormals;

                contract = new ForgeImportContract(
                    manifestPath,
                    true,
                    authoredNormals,
                    SanitizeNormalSmoothingAngle(declared.normalSmoothingAngle),
                    !declared.generateSecondaryUV,
                    string.Equals(declared.materialImportMode, ForgeMaterialImportModeNoneToken, StringComparison.Ordinal),
                    manifest.lod != null && manifest.lod.levels != null ? manifest.lod.levels.Length : 0,
                    // A positive authored LOD0 vertex count is the presence test. The block exists only on
                    // packages whose family renders through a baked VAT, and requiring a real count rather than
                    // mere non-nullness keeps an empty or default-constructed block from granting anything.
                    // ResolveVatReadiness checks both the root field (old manifests) and extra.vatReadiness
                    // (current forge output) so neither placement is silently missed.
                    ResolveVatReadiness(manifest) != null && ResolveVatReadiness(manifest).vertexCountLOD0 > 0);
                return true;
            }

            // -- tier 2: generator-local manifest, provenance only -------------------------------------------
            // No importer contract is declared here, so nothing is assumed field by field. Provenance must be
            // proven three independent ways before any relaxation applies.
            if (manifest.identity == null ||
                string.IsNullOrEmpty(manifest.identity.generator) ||
                string.IsNullOrEmpty(manifest.identity.forgeVersion))
            {
                return false;
            }

            // The manifest has to name the exact file sitting beside it. rock.py records a full path and
            // kelp.py a bare name, so the comparison is on the file name only.
            if (manifest.files == null || string.IsNullOrEmpty(manifest.files.fbx))
                return false;

            string declaredFbx = manifest.files.fbx.Replace('\\', '/');
            int declaredSlash = declaredFbx.LastIndexOf('/');
            if (declaredSlash >= 0)
                declaredFbx = declaredFbx.Substring(declaredSlash + 1);
            if (!string.Equals(declaredFbx, fbxFileName, StringComparison.OrdinalIgnoreCase))
                return false;

            // A package whose own gates failed does not get relaxed treatment. 3dmodel.md section 10: "Failure
            // aborts save."
            if (manifest.validation == null || !manifest.validation.allPassed)
                return false;

            int authoredLods = 0;
            if (manifest.lods != null)
            {
                for (int i = 0; i < manifest.lods.Length; i++)
                {
                    if (manifest.lods[i] != null && manifest.lods[i].lod >= 0)
                        authoredLods++;
                }
            }

            // Shared materials only when every declared slot names a MAT_* asset. One empty slot means the
            // package has not resolved its material contract and Unity's own import is no worse.
            bool ownsSharedMaterials = false;
            if (manifest.materialSlots != null)
            {
                for (int i = 0; i < manifest.materialSlots.Length; i++)
                {
                    if (manifest.materialSlots[i] == null ||
                        string.IsNullOrEmpty(manifest.materialSlots[i].material))
                    {
                        ownsSharedMaterials = false;
                        break;
                    }

                    ownsSharedMaterials = true;
                }
            }

            // Normals: provenance plus 3dmodel.md section 3, "A generator owns normals, tangents, UVs, and
            // bounds because it owns the geometry."
            // Secondary UV is deliberately NOT suppressed on this tier. A generator-local manifest records no
            // UV1 layer at all, so forcing Unity's generator off could leave the asset with no TexCoord1
            // whatsoever, and section 3 requires TexCoord1 only "when required".
            // normalSmoothingAngle is left at 0, meaning undeclared: the importer's angle is not touched.
            contract = new ForgeImportContract(
                manifestPath,
                false,
                true,
                ForgeMinNormalSmoothingAngle,
                false,
                ownsSharedMaterials,
                authoredLods,
                // Never a VAT source on this tier. See ForgeImportContract.IsVatSource: tier 2 proves
                // provenance only, so a readability or vertex-identity relaxation from it would be assumed.
                false);
            return true;
        }

        private static float SanitizeNormalSmoothingAngle(float declaredAngle)
        {
            // 0 means "the manifest declared none"; anything outside the legal dihedral range is treated the
            // same way rather than being written onto the importer.
            if (declaredAngle <= ForgeMinNormalSmoothingAngle || declaredAngle > ForgeMaxNormalSmoothingAngle)
                return ForgeMinNormalSmoothingAngle;

            return declaredAngle;
        }

        /// <summary>
        /// Resolves the offline forge import contract for one managed FBX, or returns false for every other
        /// asset. The manifest is re-read on every call: an import-time cache would go stale inside a session
        /// and silently apply a previous manifest's relaxations, which is the exact silent-wrong-output failure
        /// this carve-out exists to prevent.
        /// </summary>
        /// <remarks>
        /// The manifest is read with plain file IO, so it is NOT registered as an import dependency: editing a
        /// manifest does not retrigger the FBX import on its own. Use the
        /// "Hecton8/Validation/Asset Pipeline/Reimport FBX - ..." menu items after changing one.
        /// </remarks>
        internal static bool TryResolveForgeImportContract(string assetPath, out ForgeImportContract contract)
        {
            contract = default;
            if (!TryResolveForgeManifestPath(assetPath, out string manifestPath))
                return false;

            string absoluteManifestPath = ResolveProjectAbsolutePath(manifestPath);
            if (!System.IO.File.Exists(absoluteManifestPath))
                return false;

            string manifestJson;
            try
            {
                manifestJson = System.IO.File.ReadAllText(absoluteManifestPath);
            }
            catch (System.IO.IOException error)
            {
                Debug.LogError(
                    "[HectonFBXPostprocessor] Forge manifest '" + manifestPath + "' exists but could not be " +
                    "read, so the strict project policy applies to '" + assetPath + "': " + error.Message);
                return false;
            }
            catch (UnauthorizedAccessException error)
            {
                Debug.LogError(
                    "[HectonFBXPostprocessor] Forge manifest '" + manifestPath + "' is not readable, so the " +
                    "strict project policy applies to '" + assetPath + "': " + error.Message);
                return false;
            }

            string normalizedPath = assetPath.Replace('\\', '/');
            string fbxFileName = normalizedPath.Substring(normalizedPath.LastIndexOf('/') + 1);
            return TryParseForgeImportContract(manifestJson, manifestPath, fbxFileName, out contract);
        }

        private static string ResolveProjectAbsolutePath(string projectRelativePath)
        {
            // AGENTS.md Relative Path Requirement: resolve from the project root through Application.dataPath
            // rather than the process working directory, which an out-of-process asset import worker does not
            // guarantee, and never from a hardcoded developer path.
            string assetsFolder = Application.dataPath.Replace('\\', '/');
            int lastSlash = assetsFolder.LastIndexOf('/');
            string projectRoot = lastSlash > 0 ? assetsFolder.Substring(0, lastSlash) : assetsFolder;
            return projectRoot + "/" + projectRelativePath;
        }

        private static void LogForgeCarveOut(string assetPath, in ForgeImportContract contract)
        {
            // Loud on purpose, and a warning rather than a log: this is the one place the project's default
            // model-import policy is relaxed, and a plain Debug.Log is lost in Unity's import chatter. The
            // deviation must never be invisible, which is the same reason the auto-LOD fallback warns.
            Debug.LogWarning(
                "[HectonFBXPostprocessor] FORGE IMPORT CARVE-OUT applied to '" + assetPath + "' on the " +
                "authority of manifest '" + contract.ManifestPath + "' (" +
                (contract.DeclaredImportContract
                    ? "schema " + ForgeManifestSchema + ", explicit unityImport.modelImporter contract"
                    : "generator-local manifest; provenance proven by identity.generator, identity.forgeVersion, files.fbx and validation.allPassed") +
                "). importNormals=Import: " + contract.ImportAuthoredNormals +
                "; normalSmoothingAngle declared: " +
                contract.NormalSmoothingAngle.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture) +
                "; generateSecondaryUV forced off: " + contract.SuppressSecondaryUv +
                "; materialImportMode=None: " + contract.SuppressMaterialImport +
                "; authored LOD levels: " + contract.AuthoredLodLevelCount +
                (contract.IsVatSource
                    ? "; VAT SOURCE: isReadable=true, weldVertices=false, meshOptimizationFlags=PolygonOrder. " +
                      "These three keep per-vertex identity stable so a baked VAT stays synchronised with the " +
                      "mesh it indexes. Changing any of them later invalidates every VAT baked from this asset " +
                      "and requires a re-bake."
                    : "; not a VAT source: isReadable stays false and vertex identity is left at Unity defaults") +
                ". Every FBX without a matching sibling forge manifest keeps the unchanged project policy.");
        }

        private static bool IsUnderRoot(string path, string root)
        {
            if (string.IsNullOrEmpty(path) || string.IsNullOrEmpty(root))
                return false;

            string normalizedPath = path.Replace('\\', '/');
            string normalizedRoot = root.Replace('\\', '/');
            return normalizedPath.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase);
        }
    }
}
#endif
