// Crest Ocean System

// Copyright 2022 Wave Harmonic Ltd

#pragma kernel FFTBakeMultiRes

Texture2DArray<float3> _InFFTWaves;
RWTexture2D<float4> _OutDisplacements;

float _WavePatchSize;
float _BakeTime;
int _MinSlice;

[numthreads( 8, 8, 1 )]
void FFTBakeMultiRes( const uint3 id : SV_DispatchThreadID )
{
	// Read dimensions
	uint fftWidth;
	uint fftHeight;
	uint fftDepth;
	uint outWidth;
	uint outHeight;
	{
		_InFFTWaves.GetDimensions( fftWidth, fftHeight, fftDepth );
		_OutDisplacements.GetDimensions( outWidth, outHeight );
	}

	if (fftWidth == 0u || fftHeight == 0u || fftDepth == 0u || outWidth == 0u || outHeight == 0u || _MinSlice < 0)
	{
		return;
	}

	if (id.x >= outWidth || id.y >= outHeight || id.x >= fftWidth)
	{
		return;
	}

	// Compute index of current slice
	uint slice = (uint)_MinSlice + id.y / fftHeight;
	if (slice >= fftDepth)
	{
		return;
	}

	// Return displacement
	_OutDisplacements[id.xy] = float4(_InFFTWaves[uint3(id.x, id.y % fftHeight, slice)].xyz, 0.0);
}
