import pathlib
p=pathlib.Path(r"C:/hades/Hecton8/Tools/_cline_scratch/_l12_poll.py")
parts=[]
def add(s):
    parts.append(s)
add("# -*- coding: utf-8 -*-")
add("import json")
add("import os")
add("import re")
add("import subprocess")
add("import time")
add("")
add("REPO = r"C:\\hades\\Hecton8"")
add("LOG = os.path.join(REPO, "Docs", "AgentLogs", "h8_playprobe_v0_L12.log")")
add("PIDF = os.path.join(REPO, "Tools", "_cline_scratch", "v0_L12_pid.txt")")
add("OUT = os.path.join(REPO, "Tools", "_cline_scratch", "_l12_poll_out.txt")")
add("STATE = os.path.join(REPO, "Tools", "_cline_scratch", "_l12_poll_state.json")")
add("")
add("MARKERS = [")
add("    "movementIntent01max",")
add("    "INPUTHOP",")
add("    "hop2",")
add("    "Swim",")
add("    "FAIL",")
add("    "PASS",")
add("    "depth",")
add("    "lastOverride",")
add("    "PHASE",")
add("    "menu",")
add("]")
add("")
p.write_text(chr(10).join(parts)+chr(10), encoding="utf-8")
print("built", p.stat().st_size)
