L=[]
A=L.append
A("# -*- coding: utf-8 -*-")
A(""""L12 poll helper. Exit 0 always."""")
A("import json")
A("import os")
A("import re")
A("import subprocess")
A("import time")
A("")
A("REPO = r"C:\\hades\\Hecton8"")
A("LOG = os.path.join(REPO, "Docs", "AgentLogs", "h8_playprobe_v0_L12.log")")
A("PIDF = os.path.join(REPO, "Tools", "_cline_scratch", "v0_L12_pid.txt")")
A("OUT = os.path.join(REPO, "Tools", "_cline_scratch", "_l12_poll_out.txt")")
A("STATE = os.path.join(REPO, "Tools", "_cline_scratch", "_l12_poll_state.json")")
A("")
A("MARKERS = [")
A("    "movementIntent01max",")
A("    "INPUTHOP",")
A("    "hop2",")
A("    "Swim",")
A("    "FAIL",")
A("    "PASS",")
A("    "depth",")
A("    "lastOverride",")
A("    "PHASE",")
A("    "menu",")
A("]")
A("")
