from pathlib import Path 
P=chr(37) 
NL=chr(13)+chr(10) 
L=[] 
a=L.append 
a("@echo off") 
a("REM V0 allowlist commit+push. NEVER stages Tools/*cline* or remotes/tokens.") 
a("setlocal EnableExtensions") 
a("set REPO=C:\\hades\\Hecton8") 
a("set OUT="+P+"REPO"+P+"\\Tools\\_cline_scratch\\commit_v0_allowlist_out.txt") 
a("set MSGFILE="+P+"REPO"+P+"\\Tools\\_cline_scratch\\commit_v0_L06_msg.txt") 
a("") 
a("cd /d \""+P+"REPO"+P+"\"") 
a("if errorlevel 1 (") 
a("  echo FAILED_CD> \""+P+"OUT"+P+"\"") 
a("  exit /b 1") 
a(")") 
a("") 
a("echo start "+P+"DATE"+P+" "+P+"TIME"+P+"> \""+P+"OUT"+P+"\"") 
a("echo branch=>> \""+P+"OUT"+P+"\"") 
a("git rev-parse --abbrev-ref HEAD >> \""+P+"OUT"+P+"\" 2>&1") 
a("") 
a("if not exist \""+P+"MSGFILE"+P+"\" (") 
a("  echo MSGFILE_MISSING="+P+"MSGFILE"+P+">> \""+P+"OUT"+P+"\"") 
a("  echo Create Tools\\_cline_scratch\\commit_v0_L06_msg.txt with the commit body first.") 
a("  exit /b 4") 
a(")") 
a("") 
a("echo ---STATUS_BEFORE--->> \""+P+"OUT"+P+"\"") 
a("git status -sb >> \""+P+"OUT"+P+"\" 2>&1") 
a("") 
a("if exist \"Docs\\PLAYTEST\" (") 
a("  git add -- \"Docs/PLAYTEST\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_PLAYTEST="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("") 
a("if exist \"Docs\\Screenshots\\V0_Playtest\" (") 
a("  git add -f -- \"Docs/Screenshots/V0_Playtest\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_V0_Playtest_shots="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("") 
a("if exist \"Docs\\AgentLogs\\H8_V0_PLAYTEST_SMOKE_GATE.json\" (") 
a("  git add -f -- \"Docs/AgentLogs/H8_V0_PLAYTEST_SMOKE_GATE.json\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_smoke_gate_json="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("if exist \"Docs\\AgentLogs\\v0_kcc_gate_2026-07-30.log\" (") 
a("  git add -f -- \"Docs/AgentLogs/v0_kcc_gate_2026-07-30.log\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_kcc_gate_log="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("if exist \"Docs\\AgentLogs\\h8_playprobe_v0_L06.json\" (") 
a("  git add -f -- \"Docs/AgentLogs/h8_playprobe_v0_L06.json\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_L06_json="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("if exist \"Docs\\AgentLogs\\h8_playprobe_v0_L06.log\" (") 
a("  git add -f -- \"Docs/AgentLogs/h8_playprobe_v0_L06.log\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_L06_log="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("if exist \"Docs\\AgentLogs\\V0_L06_PROBE_RUNBOOK.md\" (") 
a("  git add -f -- \"Docs/AgentLogs/V0_L06_PROBE_RUNBOOK.md\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("  echo add_L06_runbook="+P+"ERRORLEVEL"+P+">> \""+P+"OUT"+P+"\"") 
a(")") 
a("") 
a("for %%%%F in (\"Docs\\AgentLogs\\V0_*\" \"Docs\\AgentLogs\\v0_*\" \"Docs\\AgentLogs\\H8_V0_*\" \"Docs\\AgentLogs\\h8_playprobe_v0_*\") do (") 
a("  if exist %%%%F (") 
a("    git add -f -- %%%%F >> \""+P+"OUT"+P+"\" 2>&1") 
a("  )") 
a(")") 
a("") 
a("echo ---CACHED_NAMES--->> \""+P+"OUT"+P+"\"") 
a("git diff --cached --name-only >> \""+P+"OUT"+P+"\" 2>&1") 
a("") 
a("git diff --cached --name-only | findstr /i /c:\"Tools/_cline\" /c:\"Tools\\_cline\" /c:\"_cline_scratch\" /c:\".env\" /c:\"token\" /c:\"credentials\" > \""+P+"REPO"+P+"\\Tools\\_cline_scratch\\commit_v0_allowlist_deny.txt\" 2>nul") 
a("for /f \"usebackq delims=\" %%%%Q in (\""+P+"REPO"+P+"\\Tools\\_cline_scratch\\commit_v0_allowlist_deny.txt\") do (") 
a("  echo DENY_UNSTAGE=%%%%Q>> \""+P+"OUT"+P+"\"") 
a("  git reset HEAD -- \"%%%%Q\" >> \""+P+"OUT"+P+"\" 2>&1") 
a(")") 
a("") 
a("echo ---CACHED_AFTER_DENY--->> \""+P+"OUT"+P+"\"") 
a("git diff --cached --name-only >> \""+P+"OUT"+P+"\" 2>&1") 
a("git diff --cached --stat >> \""+P+"OUT"+P+"\" 2>&1") 
a("") 
a("git diff --cached --quiet") 
a("if not errorlevel 1 (") 
a("  echo NOTHING_STAGED>> \""+P+"OUT"+P+"\"") 
a("  echo Nothing allowlisted to commit.") 
a("  exit /b 0") 
a(")") 
a("") 
a("git commit --no-verify -F \""+P+"MSGFILE"+P+"\" >> \""+P+"OUT"+P+"\" 2>&1") 
a("set COMMIT_EC="+P+"ERRORLEVEL"+P) 
a("echo commit_ec="+P+"COMMIT_EC"+P+">> \""+P+"OUT"+P+"\"") 
a("if not \""+P+"COMMIT_EC"+P+"\"==\"0\" (") 
a("  echo COMMIT_FAILED>> \""+P+"OUT"+P+"\"") 
a("  exit /b 5") 
a(")") 
a("") 
a("git log -1 --oneline >> \""+P+"OUT"+P+"\" 2>&1") 
a("") 
a("echo PULL_BEFORE_PUSH>> \""+P+"OUT"+P+"\"") 
a("git pull --no-rebase gitlab main >> \""+P+"OUT"+P+"\" 2>&1") 
a("set PULL_EC="+P+"ERRORLEVEL"+P) 
a("echo pull_ec="+P+"PULL_EC"+P+">> \""+P+"OUT"+P+"\"") 
a("") 
a("echo PUSH>> \""+P+"OUT"+P+"\"") 
a("git push gitlab main >> \""+P+"OUT"+P+"\" 2>&1") 
a("set PUSH_EC="+P+"ERRORLEVEL"+P) 
a("echo push_ec="+P+"PUSH_EC"+P+">> \""+P+"OUT"+P+"\"") 
a("") 
a("echo PULL_AFTER_PUSH>> \""+P+"OUT"+P+"\"") 
a("git pull --no-rebase gitlab main >> \""+P+"OUT"+P+"\" 2>&1") 
a("set PULL2_EC="+P+"ERRORLEVEL"+P) 
a("echo pull2_ec="+P+"PULL2_EC"+P+">> \""+P+"OUT"+P+"\"") 
a("") 
a("git status -sb >> \""+P+"OUT"+P+"\" 2>&1") 
a("git log -3 --oneline >> \""+P+"OUT"+P+"\" 2>&1") 
a("echo done "+P+"DATE"+P+" "+P+"TIME"+P+">> \""+P+"OUT"+P+"\"") 
a("type \""+P+"OUT"+P+"\"") 
a("exit /b 0") 
text=NL.join(L)+NL 
p=Path(r"C:/hades/Hecton8/Tools/_cline_scratch/commit_v0_allowlist.bat") 
p.write_bytes(text.encode("ascii")) 
raw=p.read_bytes() 
print("size", len(raw)) 
print("el", raw.count((P+"ERRORLEVEL"+P).encode())) 
print("bad", b"set COMMIT_EC=0" in raw) 
print("good", (b"set COMMIT_EC="+(P+"ERRORLEVEL"+P).encode()) in raw) 
