using Hecton8.Construction;
using Hecton8.Core;
using Hecton8.Economy;
using Hecton8.Power;
using UnityEngine;

namespace Hecton8.World
{
    /// <summary>
    /// Aggregates industrial pollution generated by powered base infrastructure and feeds the shared environmental strain owner.
    /// </summary>
    [DisallowMultipleComponent]
    [DefaultExecutionOrder(-6450)]
    [AddComponentMenu("Hecton8/World/Base Pollution Manager")]
    public sealed class BasePollutionManager : MonoBehaviour, ISlowTickable, IServiceHeartbeat, IServiceShutdown, IGlobalRegistryHotSwapListener
    {
        [Header("── Power Noise ─────────────────────────")]
        [Tooltip("Local acoustic noise emitted per watt of active base consumption during one slow-tick window.")]
        [SerializeField, Range(0f, 0.01f)] private float powerNoisePerWattTick = 0.0012f;

        [Tooltip("Additional local noise emitted by each deficit grid struggling under overload.")]
        [SerializeField, Range(0f, 10f)] private float deficitGridNoise = 1.2f;

        [Tooltip("Fraction of local power-noise output that becomes persistent global pollution strain.")]
        [SerializeField, Range(0f, 1f)] private float powerNoiseStrainLeak = 0.08f;

        [Header("── Drone Emissions ─────────────────────")]
        [Tooltip("Local noise emitted per active repair drone during one slow-tick window.")]
        [SerializeField, Range(0f, 10f)] private float activeDroneNoise = 0.85f;

        [Tooltip("Local noise spike emitted each time a repair drone launches.")]
        [SerializeField, Range(0f, 20f)] private float droneLaunchNoise = 2.5f;

        [Tooltip("Microplastic residue emitted per active repair drone during one slow-tick window.")]
        [SerializeField, Range(0f, 5f)] private float activeDroneMicroplastic = 0.22f;

        [Tooltip("Microplastic spike emitted each time a repair drone launches with repair scrap.")]
        [SerializeField, Range(0f, 10f)] private float droneLaunchMicroplastic = 0.9f;

        [Header("── Recycler Emissions ──────────────────")]
        [Tooltip("Local noise emitted per active recycler during one slow-tick window.")]
        [SerializeField, Range(0f, 10f)] private float activeRecyclerNoise = 1.15f;

        [Tooltip("Microplastic residue emitted per successfully processed recycle batch.")]
        [SerializeField, Range(0f, 10f)] private float recycledBatchMicroplastic = 0.75f;

        [Tooltip("Local noise emitted per active deep drill during one slow-tick window.")]
        [SerializeField, Range(0f, 40f)] private float activeDrillNoise = 6.5f;

        [Tooltip("Noise spike emitted each time a deep drill completes one extraction cycle.")]
        [SerializeField, Range(0f, 80f)] private float drillCycleNoise = 14f;

        [Header("── Local Retention ─────────────────────")]
        [Tooltip("Retention factor applied to the local acoustic signature each slow tick.")]
        [SerializeField, Range(0f, 0.999f)] private float noiseRetention = 0.91f;

        [Tooltip("Retention factor applied to the local microplastic cloud each slow tick.")]
        [SerializeField, Range(0f, 0.999f)] private float microplasticRetention = 0.965f;

        [Header("── Diagnostics ─────────────────────────")]
        [SerializeField] private float _debugCurrentNoiseLevel;
        [SerializeField] private float _debugCurrentMicroplasticLevel;
        [SerializeField] private float _debugTotalConsumption;
        [SerializeField] private int _debugDeficitGridCount;
        [SerializeField] private int _debugActiveDroneCount;
        [SerializeField] private int _debugDroneLaunchDelta;
        [SerializeField] private int _debugActiveRecyclerCount;
        [SerializeField] private int _debugRecyclerBatchDelta;
        [SerializeField] private int _debugActiveDrillCount;
        [SerializeField] private int _debugDrillCycleDelta;

        private bool _registeredToTick;
        private bool _serviceRegistered;
        private float _currentNoiseLevel;
        private float _currentMicroplasticLevel;
        private int _lastDroneLaunchTotal;
        private int _lastProcessedRecycleTotal;
        private int _lastCompletedDrillCycles;
        private EnvironmentalStrainManager _cachedEnvironmentalStrain;
        private bool _hotSwapRegistered;
        private static BasePollutionManager s_activeRuntime;

        /// <summary>Current local acoustic signature emitted by the base cluster.</summary>
        public static float CurrentNoiseLevel
        {
            get
            {
                BasePollutionManager runtime = s_activeRuntime;
                return runtime != null ? runtime._currentNoiseLevel : 0f;
            }
        }

        /// <summary>Current local microplastic cloud emitted by the base cluster.</summary>
        public static float CurrentMicroplasticLevel
        {
            get
            {
                BasePollutionManager runtime = s_activeRuntime;
                return runtime != null ? runtime._currentMicroplasticLevel : 0f;
            }
        }

        /// <inheritdoc />
        public ServiceHeartbeatState HeartbeatState => _serviceRegistered ? ServiceHeartbeatState.Ready : ServiceHeartbeatState.NotStarted;

        /// <inheritdoc />
        public bool IsServiceReady => _serviceRegistered;

        private void Awake()
        {
            BasePollutionManager registered = GlobalRegistry.BasePollution;
            if (registered != null && registered != this)
            {
                Destroy(gameObject);
                return;
            }
        }

        private void OnEnable()
        {
            TryRegisterService();
            if (Application.isPlaying && !_serviceRegistered)
                return;

            TryRegister();
            CacheEnvironmentalStrain(GlobalRegistry.EnvironmentalStrain);
            TryRegisterHotSwapListener();
        }

        private void OnDisable()
        {
            OnServiceShutdown();
        }

        private void OnDestroy()
        {
            OnServiceShutdown();
        }

        /// <inheritdoc />
        public void OnServiceShutdown()
        {
            TryUnregister();
            TryUnregisterHotSwapListener();
            CacheEnvironmentalStrain(null);
            TryUnregisterService();
        }

        private void TryRegisterService()
        {
            if (_serviceRegistered || !Application.isPlaying)
                return;

            BasePollutionManager registered = GlobalRegistry.BasePollution;
            if (registered != null && registered != this)
            {
                Destroy(gameObject);
                return;
            }

            GlobalRegistry.RegisterBasePollutionRuntime(this);
            _serviceRegistered = ReferenceEquals(GlobalRegistry.BasePollution, this);
            if (_serviceRegistered)
                s_activeRuntime = this;
        }

        private void TryUnregisterService()
        {
            if (!_serviceRegistered)
                return;

            GlobalRegistry.UnregisterBasePollutionRuntime(this);
            _serviceRegistered = false;
            if (ReferenceEquals(s_activeRuntime, this))
                s_activeRuntime = null;
        }

        public void SlowTick()
        {
            float totalConsumption = 0f;
            int deficitGridCount = 0;
            CollectPowerTelemetry(ref totalConsumption, ref deficitGridCount);

            int activeDroneCount = 0;
            int totalDroneLaunches = 0;
            CollectRepairDroneTelemetry(ref activeDroneCount, ref totalDroneLaunches);

            int activeRecyclerCount = 0;
            int totalProcessedRecycleBatches = 0;
            CollectRecyclerTelemetry(ref activeRecyclerCount, ref totalProcessedRecycleBatches);

            int activeDrillCount = 0;
            int totalCompletedDrillCycles = 0;
            CollectDeepDrillTelemetry(ref activeDrillCount, ref totalCompletedDrillCycles);

            int droneLaunchDelta = totalDroneLaunches - _lastDroneLaunchTotal;
            if (droneLaunchDelta < 0)
                droneLaunchDelta = totalDroneLaunches;
            _lastDroneLaunchTotal = totalDroneLaunches;

            int recyclerBatchDelta = totalProcessedRecycleBatches - _lastProcessedRecycleTotal;
            if (recyclerBatchDelta < 0)
                recyclerBatchDelta = totalProcessedRecycleBatches;
            _lastProcessedRecycleTotal = totalProcessedRecycleBatches;

            int drillCycleDelta = totalCompletedDrillCycles - _lastCompletedDrillCycles;
            if (drillCycleDelta < 0)
                drillCycleDelta = totalCompletedDrillCycles;
            _lastCompletedDrillCycles = totalCompletedDrillCycles;

            float emittedNoise =
                totalConsumption * powerNoisePerWattTick +
                deficitGridCount * deficitGridNoise +
                activeDroneCount * activeDroneNoise +
                droneLaunchDelta * droneLaunchNoise +
                activeRecyclerCount * activeRecyclerNoise +
                activeDrillCount * activeDrillNoise +
                drillCycleDelta * drillCycleNoise;

            float emittedMicroplastic =
                activeDroneCount * activeDroneMicroplastic +
                droneLaunchDelta * droneLaunchMicroplastic +
                recyclerBatchDelta * recycledBatchMicroplastic;

            _currentNoiseLevel = _currentNoiseLevel * noiseRetention + emittedNoise;
            _currentMicroplasticLevel = _currentMicroplasticLevel * microplasticRetention + emittedMicroplastic;

            EnvironmentalStrainManager strainManager = _cachedEnvironmentalStrain;
            if (strainManager != null)
            {
                strainManager.AccumulateIndustrialStrain(
                    emittedNoise * powerNoiseStrainLeak,
                    emittedMicroplastic);
            }

            _debugCurrentNoiseLevel = _currentNoiseLevel;
            _debugCurrentMicroplasticLevel = _currentMicroplasticLevel;
            _debugTotalConsumption = totalConsumption;
            _debugDeficitGridCount = deficitGridCount;
            _debugActiveDroneCount = activeDroneCount;
            _debugDroneLaunchDelta = droneLaunchDelta;
            _debugActiveRecyclerCount = activeRecyclerCount;
            _debugRecyclerBatchDelta = recyclerBatchDelta;
            _debugActiveDrillCount = activeDrillCount;
            _debugDrillCycleDelta = drillCycleDelta;
        }

        public void OnGlobalRegistryServiceReplaced(
            GlobalRegistryServiceSlot serviceSlot,
            object previousService,
            object currentService)
        {
            if (serviceSlot == GlobalRegistryServiceSlot.EnvironmentalStrainRuntime)
                CacheEnvironmentalStrain(currentService as EnvironmentalStrainManager);
        }

        private void CacheEnvironmentalStrain(EnvironmentalStrainManager strainManager)
        {
            _cachedEnvironmentalStrain = strainManager;
        }

        private void TryRegisterHotSwapListener()
        {
            if (_hotSwapRegistered)
                return;

            _hotSwapRegistered = GlobalRegistry.TryRegisterHotSwapListener(this);
        }

        private void TryUnregisterHotSwapListener()
        {
            if (!_hotSwapRegistered)
                return;

            GlobalRegistry.TryUnregisterHotSwapListener(this);
            _hotSwapRegistered = false;
        }

        private void TryRegister()
        {
            if (_registeredToTick || !Application.isPlaying || GlobalRegistry.Dispatcher == null)
                return;

            GlobalRegistry.RegisterSlowTickable(this, PriorityLayer.Environment);
            _registeredToTick = GlobalRegistry.SlowTickables.Contains(this);
        }

        private void TryUnregister()
        {
            if (!_registeredToTick)
                return;

            GlobalRegistry.UnregisterSlowTickable(this, PriorityLayer.Environment);
            _registeredToTick = false;
        }

        private static void CollectPowerTelemetry(ref float totalConsumption, ref int deficitGridCount)
        {
            int gridCount = PowerGridManager.RuntimeGridCount;
            for (int i = 0; i < gridCount; i++)
            {
                PowerGrid grid = PowerGridManager.GetRuntimeGridAt(i);
                if (grid == null || grid.NodeCount <= 0)
                    continue;

                totalConsumption += Mathf.Max(0f, grid.TotalConsumption);
                if (grid.HasPowerDeficit)
                    deficitGridCount++;
            }
        }

        private static void CollectRepairDroneTelemetry(ref int activeDroneCount, ref int totalLaunchCount)
        {
            int hubCount = RepairDroneHub.ActiveHubCount;
            for (int i = 0; i < hubCount; i++)
            {
                RepairDroneHub hub = RepairDroneHub.GetActiveHubAt(i);
                if (hub == null || !hub.isActiveAndEnabled)
                    continue;

                activeDroneCount += hub.ActiveDroneCount;
                totalLaunchCount += hub.TotalLaunchCount;
            }
        }

        private static void CollectRecyclerTelemetry(ref int activeRecyclerCount, ref int totalProcessedRecycleBatches)
        {
            int recyclerCount = ResourceRecyclerModule.ActiveModuleCount;
            for (int i = 0; i < recyclerCount; i++)
            {
                ResourceRecyclerModule recycler = ResourceRecyclerModule.GetActiveModuleAt(i);
                if (recycler == null || !recycler.isActiveAndEnabled)
                    continue;

                if (recycler.IsProcessing)
                    activeRecyclerCount++;

                totalProcessedRecycleBatches += recycler.TotalProcessedBatchCount;
            }
        }

        private static void CollectDeepDrillTelemetry(ref int activeDrillCount, ref int totalCompletedDrillCycles)
        {
            int drillCount = DeepDrillModule.ActiveModuleCount;
            for (int i = 0; i < drillCount; i++)
            {
                DeepDrillModule drill = DeepDrillModule.GetActiveModuleAt(i);
                if (drill == null || !drill.isActiveAndEnabled)
                    continue;

                if (drill.IsOperating)
                    activeDrillCount++;

                totalCompletedDrillCycles += drill.CompletedCycleCount;
            }
        }
    }
}
