using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

namespace Hecton8.World
{
    /// <summary>
    /// Spawn-ready brine pool bounds resolved from a basin mask.
    /// </summary>
    public struct AnomalyBrinePoolBounds
    {
        /// <summary>One-based basin identifier.</summary>
        public int BasinId;

        /// <summary>Inclusive minimum X sample.</summary>
        public int MinX;

        /// <summary>Inclusive minimum Z sample.</summary>
        public int MinZ;

        /// <summary>Inclusive maximum X sample.</summary>
        public int MaxX;

        /// <summary>Inclusive maximum Z sample.</summary>
        public int MaxZ;

        /// <summary>Masked cell count in bounds.</summary>
        public int MaskedCount;

        /// <summary>Brine surface height in meters.</summary>
        public float LipHeight;

        /// <summary>One when valid.</summary>
        public byte Valid;
    }

    /// <summary>
    /// Burst job that resolves brine pool spawn bounds from basin records and mask cells.
    /// </summary>
    [BurstCompile(FloatPrecision.Standard, FloatMode.Deterministic, CompileSynchronously = true)]
    public struct ResolveBrinePoolBoundsJob : IJobParallelFor
    {
        /// <summary>Basin mask generated by the anomaly detector.</summary>
        [ReadOnly] public NativeArray<byte> BasinMask;

        /// <summary>Basin records generated by the anomaly detector.</summary>
        [ReadOnly] public NativeArray<AnomalyBasinRecord> BasinRecords;

        /// <summary>Resolved brine bounds indexed by basin record index.</summary>
        [WriteOnly] public NativeArray<AnomalyBrinePoolBounds> Bounds;

        /// <summary>Heightmap width.</summary>
        public int Width;

        /// <summary>Heightmap height.</summary>
        public int Height;

        /// <inheritdoc />
        public void Execute(int index)
        {
            Bounds[index] = default;
            AnomalyBasinRecord record = BasinRecords[index];
            if (record.Valid == 0)
                return;

            int minX = Width;
            int minZ = Height;
            int maxX = 0;
            int maxZ = 0;
            int maskedCount = 0;
            int startX = math.clamp(record.MinX, 0, Width - 1);
            int startZ = math.clamp(record.MinZ, 0, Height - 1);
            int endX = math.clamp(record.MaxX, 0, Width - 1);
            int endZ = math.clamp(record.MaxZ, 0, Height - 1);

            for (int z = startZ; z <= endZ; z++)
            {
                int row = z * Width;
                for (int x = startX; x <= endX; x++)
                {
                    if (BasinMask[x + row] == 0)
                        continue;

                    minX = math.min(minX, x);
                    minZ = math.min(minZ, z);
                    maxX = math.max(maxX, x);
                    maxZ = math.max(maxZ, z);
                    maskedCount++;
                }
            }

            if (maskedCount <= 0)
                return;

            Bounds[index] = new AnomalyBrinePoolBounds
            {
                BasinId = record.BasinId,
                MinX = minX,
                MinZ = minZ,
                MaxX = maxX,
                MaxZ = maxZ,
                MaskedCount = maskedCount,
                LipHeight = record.LipHeight,
                Valid = 1
            };
        }
    }
}
