using System.Runtime.InteropServices;
using Unity.Burst;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Jobs;
using Unity.Mathematics;

namespace Hecton8.World
{
    internal static class HectonAnomalyBrineJobsLayout
    {
        public const int AnomalyBrinePoolBoundsStrideBytes = 32;
    }

    /// <summary>
    /// Spawn-ready brine pool bounds resolved from a basin mask.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = HectonAnomalyBrineJobsLayout.AnomalyBrinePoolBoundsStrideBytes)]
    public struct AnomalyBrinePoolBounds
    {
        /// <summary>One-based basin identifier.</summary>
        [FieldOffset(0)]
        public int BasinId;

        /// <summary>Inclusive minimum X sample.</summary>
        [FieldOffset(4)]
        public int MinX;

        /// <summary>Inclusive minimum Z sample.</summary>
        [FieldOffset(8)]
        public int MinZ;

        /// <summary>Inclusive maximum X sample.</summary>
        [FieldOffset(12)]
        public int MaxX;

        /// <summary>Inclusive maximum Z sample.</summary>
        [FieldOffset(16)]
        public int MaxZ;

        /// <summary>Masked cell count in bounds.</summary>
        [FieldOffset(20)]
        public int MaskedCount;

        /// <summary>Brine surface height in meters.</summary>
        [FieldOffset(24)]
        public float LipHeight;

        /// <summary>One when valid.</summary>
        [FieldOffset(28)]
        public byte Valid;
        [FieldOffset(29)]
        private byte _pad0;
        [FieldOffset(30)]
        private ushort _pad1;
    }

    /// <summary>
    /// Burst job that resolves brine pool spawn bounds from basin records and mask cells.
    /// </summary>
    [BurstCompile(CompileSynchronously = true, FloatPrecision = FloatPrecision.Standard, FloatMode = FloatMode.Deterministic)]
    public struct ResolveBrinePoolBoundsJob : IJobParallelFor
    {
        /// <summary>Basin mask generated by the anomaly detector.</summary>
        [ReadOnly, NoAlias] public NativeArray<byte> BasinMask;

        /// <summary>Basin records generated by the anomaly detector.</summary>
        [ReadOnly, NoAlias] public NativeArray<AnomalyBasinRecord> BasinRecords;

        /// <summary>Resolved brine bounds indexed by basin record index.</summary>
        [WriteOnly, NoAlias] public NativeArray<AnomalyBrinePoolBounds> Bounds;

        /// <summary>Heightmap width.</summary>
        public int Width;

        /// <summary>Heightmap height.</summary>
        public int Height;

        /// <inheritdoc />
        public void Execute(int index)
        {
            Bounds[index] = default;
            if (Width <= 0 || Height <= 0)
                return;

            AnomalyBasinRecord record = BasinRecords[index];
            if (!IsValidRecordHeader(record, Width, Height))
                return;

            int minX = Width;
            int minZ = Height;
            int maxX = 0;
            int maxZ = 0;
            int maskedCount = 0;
            int startX = math.clamp(record.MinX, 0, Width - 1);
            int startZ = math.clamp(record.MinZ, 0, Height - 1);
            int endX = math.clamp(record.MaxX, 0, Width - 1);
            int endZ = math.clamp(record.MaxZ, 0, Height - 1);

            for (int z = startZ; z <= endZ; z++)
            {
                int row = z * Width;
                for (int x = startX; x <= endX; x++)
                {
                    if (BasinMask[x + row] == 0)
                        continue;

                    minX = math.min(minX, x);
                    minZ = math.min(minZ, z);
                    maxX = math.max(maxX, x);
                    maxZ = math.max(maxZ, z);
                    maskedCount++;
                }
            }

            if (maskedCount <= 0 || maskedCount != record.CellCount)
                return;

            Bounds[index] = new AnomalyBrinePoolBounds
            {
                BasinId = record.BasinId,
                MinX = minX,
                MinZ = minZ,
                MaxX = maxX,
                MaxZ = maxZ,
                MaskedCount = maskedCount,
                LipHeight = record.LipHeight,
                Valid = 1
            };
        }

        private static bool IsValidRecordHeader(AnomalyBasinRecord record, int width, int height)
        {
            if (record.Valid == 0 || record.BasinId <= 0 || record.CellCount <= 0)
                return false;
            if (!math.isfinite(record.DeepestHeight) || !math.isfinite(record.LipHeight) || record.LipHeight <= record.DeepestHeight)
                return false;
            if (record.MinX < 0 || record.MinZ < 0 || record.MaxX >= width || record.MaxZ >= height)
                return false;
            if (record.MinX > record.MaxX || record.MinZ > record.MaxZ)
                return false;

            int boundsWidth = record.MaxX - record.MinX + 1;
            int boundsHeight = record.MaxZ - record.MinZ + 1;
            long boundsCells = (long)boundsWidth * boundsHeight;
            return record.CellCount <= boundsCells;
        }
    }
}
