using System.Runtime.InteropServices;
using Hecton8.Core.Contracts.Signals;
using Unity.Mathematics;

namespace Hecton8.Physics.Exosuit
{
    /// <summary>
    /// Bit fields for the single exosuit kinematic authority state.
    /// </summary>
    public static class ExosuitStateFlags
    {
        public const uint Active = 1u << 0;
        public const uint Grounded = 1u << 1;
        public const uint Clamped = 1u << 2;
        public const uint PurgeLatched = 1u << 3;
        public const uint NaNDetected = 1u << 4;
        public const uint LowProbeBudget = 1u << 5;
        public const uint SecondaryProbeBlend = 1u << 6;
        public const uint EmergencyMockData = 1u << 7;
    }

    /// <summary>
    /// Mock input action bits consumed by the blind exosuit solver.
    /// </summary>
    public static class ExosuitInputActions
    {
        public const uint Grab = 1u << 0;
        public const uint Purge = 1u << 1;
        public const uint Jump = 1u << 2;
    }

    /// <summary>
    /// 64-byte ARM64-safe exosuit authority state. Raw fields only; no C# properties.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitStateDTO
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float3 Velocity;
        [FieldOffset(36)] public float HydraulicPressure;
        [FieldOffset(40)] public float3 AnchorNormal;
        [FieldOffset(52)] public uint StateMask;
        [FieldOffset(56)] public ulong _pad0;
    }

    /// <summary>
    /// 16-byte unmanaged haptic event generated by kinematic SDF impacts.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public partial struct MechHapticSignalDTO : ISignal
    {
        [FieldOffset(0)] public float Amplitude;
        [FieldOffset(4)] public float Frequency;
        [FieldOffset(8)] public float Duration;
        [FieldOffset(12)] public uint MotorMask;
    }

    /// <summary>
    /// Blind pressure signal used until hull-integrity pressure authority is wired.
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Size = 16)]
    public partial struct MockCrushDepthSignal
    {
        public float DepthMeters;
        public float ExternalPressure01;
        public uint Frame;
        private uint _pad0;
    }

    /// <summary>
    /// Ballast purge packet for silt and emergency-ascent presentation owners.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public partial struct SiltExplosionSignal : ISignal
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float Intensity01;
        [FieldOffset(28)] public uint SourceHash;
    }

    /// <summary>
    /// Low-frequency acoustic stomp or scrape tap from heavy exosuit contact.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public partial struct ExosuitAcousticEchoTap : ISignal
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float Intensity01;
        [FieldOffset(28)] public uint EchoHash;
    }

    /// <summary>
    /// 16-byte diegetic cockpit data export.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct ExoScreenDTO
    {
        [FieldOffset(0)] public float HydraulicPressure;
        [FieldOffset(4)] public float DepthMeters;
        [FieldOffset(8)] public uint StateMask;
        [FieldOffset(12)] public uint Frame;
    }

    /// <summary>
    /// 64-byte telemetry entry for the 300-frame exosuit black box.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitTelemetryEntry
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float3 Velocity;
        [FieldOffset(36)] public float HydraulicPressure;
        [FieldOffset(40)] public float SdfPushOutMagnitude;
        [FieldOffset(44)] public float SolverComputeTimeMs;
        [FieldOffset(48)] public uint Frame;
        [FieldOffset(52)] public uint StateMask;
        [FieldOffset(56)] public uint ErrorFlags;
        [FieldOffset(60)] public uint StateHash;
    }

    /// <summary>
    /// Runtime tuning scalars for the exosuit solver. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitTuningDTO
    {
        [FieldOffset(0)] public float BaseMass;
        [FieldOffset(4)] public float CurrentMass;
        [FieldOffset(8)] public float Drag;
        [FieldOffset(12)] public float ThrusterForce;
        [FieldOffset(16)] public float Radius;
        [FieldOffset(20)] public float ClampRange;
        [FieldOffset(24)] public float HydraulicLatencySeconds;
        [FieldOffset(28)] public float PurgeImpulse;
        [FieldOffset(32)] public float GlobalQualityWeight;
        [FieldOffset(36)] public float FootstepStrideMeters;
        [FieldOffset(40)] public float MaxSpeedMetersPerSecond;
        [FieldOffset(44)] public float CrushDepthMeters;
        [FieldOffset(48)] public uint CsvVersion;
        [FieldOffset(52)] public uint StateHash;
        [FieldOffset(56)] public uint Flags;
        [FieldOffset(60)] private uint _pad0;
    }

    /// <summary>
    /// Mock input buffer used by the blind solver. Size: 32 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct MockInputBuffer
    {
        [FieldOffset(0)] public float2 MoveAxis;
        [FieldOffset(8)] public float VerticalAxis;
        [FieldOffset(12)] public float DesiredYawRadians;
        [FieldOffset(16)] public uint ActionMask;
        [FieldOffset(20)] public uint Frame;
        [FieldOffset(24)] public float GlobalQualityWeight;
        [FieldOffset(28)] private uint _pad0;
    }

    /// <summary>
    /// Analytic cave SDF mock: floor, ceiling, and round shaft wall. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct MockTerrainSDF
    {
        [FieldOffset(0)] public double3 CameraAup;
        [FieldOffset(24)] public float CaveRadius;
        [FieldOffset(28)] public float FloorY;
        [FieldOffset(32)] public float CeilingY;
        [FieldOffset(36)] public float WallSoftnessMeters;
        [FieldOffset(40)] public float3 CaveCenterLocal;
        [FieldOffset(52)] public uint Flags;
        [FieldOffset(56)] private ulong _pad0;
    }

    /// <summary>
    /// Mock abyssal current field for clamp-vs-swim proof. Size: 32 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct MockFlowField
    {
        [FieldOffset(0)] public float3 FlowVelocity;
        [FieldOffset(12)] public float Intensity01;
        [FieldOffset(16)] public float3 ReservedVector;
        [FieldOffset(28)] private uint _pad0;
    }

    /// <summary>
    /// Solver readback packet consumed by late-frame signal emission and gizmos. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitSolverOutput
    {
        public const uint FlagCollision = 1u << 0;
        public const uint FlagHaptic = 1u << 1;
        public const uint FlagSilt = 1u << 2;
        public const uint FlagAcousticTap = 1u << 3;
        public const uint FlagFault = 1u << 4;

        [FieldOffset(0)] public float3 LocalPosition;
        [FieldOffset(12)] public float3 DesiredVelocity;
        [FieldOffset(24)] public float3 PushNormal;
        [FieldOffset(36)] public float PushOutMagnitude;
        [FieldOffset(40)] public float LostVelocityMagnitude;
        [FieldOffset(44)] public float Speed;
        [FieldOffset(48)] public uint Flags;
        [FieldOffset(52)] public uint Frame;
        [FieldOffset(56)] public uint StateHash;
        [FieldOffset(60)] private uint _pad0;
    }
}
