using System.Runtime.InteropServices;
using Hecton8.Core.Contracts;
using Hecton8.Core.Contracts.Signals;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Mathematics;

namespace Hecton8.Physics.Exosuit
{
    /// <summary>
    /// Bit fields for the single exosuit kinematic authority state.
    /// </summary>
    public static class ExosuitStateFlags
    {
        public const uint Active = 1u << 0;
        public const uint Grounded = 1u << 1;
        public const uint Clamped = 1u << 2;
        public const uint PurgeLatched = 1u << 3;
        public const uint NaNDetected = 1u << 4;
        public const uint ReducedProbeBudget = 1u << 5;
        public const uint SecondaryProbeBlend = 1u << 6;
        public const uint EmergencyMockData = 1u << 7;
        public const uint ThrusterActive = 1u << 8;
        public const uint Overheated = 1u << 9;
        public const uint SdfContact = 1u << 10;
        public const uint VoxelSdfSampled = 1u << 11;
        public const uint BudgetExceeded = 1u << 12;
    }

    /// <summary>
    /// 64-byte ARM64-safe exosuit authority state. Raw fields only; no C# properties.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitStateDTO
    {
        [FieldOffset(0)] public double3 AUP_Position;
        [FieldOffset(24)] public float3 Velocity;
        [FieldOffset(36)] public float3 AngularVelocity;
        [FieldOffset(48)] public float ThrusterHeat;
        [FieldOffset(52)] public uint Flags;
        [FieldOffset(56)] public uint ReservedLock;
        [FieldOffset(60)] private uint _pad0;
    }

    /// <summary>
    /// 16-byte unmanaged haptic event generated by kinematic SDF impacts.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public partial struct MechHapticSignalDTO : ISignal
    {
        [FieldOffset(0)] public float Amplitude;
        [FieldOffset(4)] public float Frequency;
        [FieldOffset(8)] public float Duration;
        [FieldOffset(12)] public uint MotorMask;
    }

    /// <summary>
    /// Blind pressure signal used until hull-integrity pressure authority is wired.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public partial struct MockCrushDepthSignal
    {
        [FieldOffset(0)] public float DepthMeters;
        [FieldOffset(4)] public float ExternalPressure01;
        [FieldOffset(8)] public uint Frame;
        [FieldOffset(12)] private uint _pad0;
    }

    /// <summary>
    /// Ballast purge packet for silt and emergency-ascent presentation owners.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public partial struct SiltExplosionSignal : ISignal
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float Intensity01;
        [FieldOffset(28)] public uint SourceHash;
    }

    /// <summary>
    /// Low-frequency acoustic stomp or scrape tap from heavy exosuit contact.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public partial struct ExosuitAcousticEchoTap : ISignal
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float Intensity01;
        [FieldOffset(28)] public uint EchoHash;
    }

    /// <summary>
    /// 16-byte diegetic cockpit data export.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct ExoScreenDTO
    {
        [FieldOffset(0)] public float HydraulicPressure;
        [FieldOffset(4)] public float DepthMeters;
        [FieldOffset(8)] public uint Flags;
        [FieldOffset(12)] public uint Frame;
    }

    /// <summary>
    /// 64-byte telemetry entry for the 300-frame exosuit black box.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitTelemetryEntry
    {
        [FieldOffset(0)] public double3 AUP;
        [FieldOffset(24)] public float3 Velocity;
        [FieldOffset(36)] public float ThrusterHeat;
        [FieldOffset(40)] public float HydraulicPressure;
        [FieldOffset(44)] public float SdfPushOutMagnitude;
        [FieldOffset(48)] public float SolverComputeTimeMs;
        [FieldOffset(52)] public uint Frame;
        [FieldOffset(56)] public uint Flags;
        [FieldOffset(60)] public uint StateHash;
    }

    /// <summary>
    /// Runtime tuning scalars for the exosuit solver. Size: 80 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 80)]
    public struct ExosuitTuningDTO
    {
        [FieldOffset(0)] public float BaseMass;
        [FieldOffset(4)] public float CurrentMass;
        [FieldOffset(8)] public float Drag;
        [FieldOffset(12)] public float ThrusterForce;
        [FieldOffset(16)] public float Radius;
        [FieldOffset(20)] public float ClampRange;
        [FieldOffset(24)] public float HydraulicLatencySeconds;
        [FieldOffset(28)] public float PurgeImpulse;
        [FieldOffset(32)] public float GlobalQualityWeight;
        [FieldOffset(36)] public float FootstepStrideMeters;
        [FieldOffset(40)] public float MaxSpeedMetersPerSecond;
        [FieldOffset(44)] public float CrushDepthMeters;
        [FieldOffset(48)] public float SdfEpsilonMeters;
        [FieldOffset(52)] public float GravityMultiplier;
        [FieldOffset(56)] public uint MaxSubsteps;
        [FieldOffset(60)] public uint CsvVersion;
        [FieldOffset(64)] public uint StateHash;
        [FieldOffset(68)] public uint Flags;
        [FieldOffset(72)] private ulong _pad0;
    }

    /// <summary>
    /// Analytic cave SDF mock: floor, ceiling, and round shaft wall. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct MockTerrainSDF
    {
        [FieldOffset(0)] public double3 CameraAup;
        [FieldOffset(24)] public float CaveRadius;
        [FieldOffset(28)] public float FloorY;
        [FieldOffset(32)] public float CeilingY;
        [FieldOffset(36)] public float WallSoftnessMeters;
        [FieldOffset(40)] public float3 CaveCenterLocal;
        [FieldOffset(52)] public uint Flags;
        [FieldOffset(56)] private ulong _pad0;
    }

    /// <summary>
    /// Mock abyssal current field for clamp-vs-swim proof. Size: 32 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct MockFlowField
    {
        [FieldOffset(0)] public float3 FlowVelocity;
        [FieldOffset(12)] public float Intensity01;
        [FieldOffset(16)] public float3 ReservedVector;
        [FieldOffset(28)] private uint _pad0;
    }

    /// <summary>
    /// Solver readback packet consumed by late-frame signal emission and gizmos. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct ExosuitSolverOutput
    {
        public const uint FlagCollision = 1u << 0;
        public const uint FlagHaptic = 1u << 1;
        public const uint FlagSilt = 1u << 2;
        public const uint FlagAcousticTap = 1u << 3;
        public const uint FlagFault = 1u << 4;

        [FieldOffset(0)] public float3 LocalPosition;
        [FieldOffset(12)] public float3 DesiredVelocity;
        [FieldOffset(24)] public float3 PushNormal;
        [FieldOffset(36)] public float PushOutMagnitude;
        [FieldOffset(40)] public float LostVelocityMagnitude;
        [FieldOffset(44)] public float Speed;
        [FieldOffset(48)] public uint Flags;
        [FieldOffset(52)] public uint Frame;
        [FieldOffset(56)] public uint StateHash;
        [FieldOffset(60)] private uint _pad0;
    }

    public static class ExosuitLayoutVerifier
    {
        public static bool ValidateRuntimeLayouts()
        {
            bool sizeOk =
                UnsafeUtility.SizeOf<ExosuitStateDTO>() == 64 &&
                UnsafeUtility.SizeOf<ExosuitFrameInputDTO>() == 32 &&
                UnsafeUtility.SizeOf<MechHapticSignalDTO>() == 16 &&
                UnsafeUtility.SizeOf<MockCrushDepthSignal>() == 16 &&
                UnsafeUtility.SizeOf<SiltExplosionSignal>() == 32 &&
                UnsafeUtility.SizeOf<ExosuitAcousticEchoTap>() == 32 &&
                UnsafeUtility.SizeOf<ExoScreenDTO>() == 16 &&
                UnsafeUtility.SizeOf<ExosuitTuningDTO>() == 80 &&
                UnsafeUtility.SizeOf<MockTerrainSDF>() == 64 &&
                UnsafeUtility.SizeOf<MockFlowField>() == 32 &&
                UnsafeUtility.SizeOf<ExosuitSolverOutput>() == 64 &&
                UnsafeUtility.SizeOf<ExosuitTelemetryEntry>() == 64;

#if UNITY_EDITOR
            return sizeOk &&
                   GetOffset<ExosuitStateDTO>(nameof(ExosuitStateDTO.AUP_Position)) == 0 &&
                   GetOffset<ExosuitStateDTO>(nameof(ExosuitStateDTO.Velocity)) == 24 &&
                   GetOffset<ExosuitStateDTO>(nameof(ExosuitStateDTO.AngularVelocity)) == 36 &&
                   GetOffset<ExosuitStateDTO>(nameof(ExosuitStateDTO.ThrusterHeat)) == 48 &&
                   GetOffset<ExosuitStateDTO>(nameof(ExosuitStateDTO.Flags)) == 52 &&
                   GetOffset<ExosuitStateDTO>(nameof(ExosuitStateDTO.ReservedLock)) == 56 &&
                   GetOffset<ExosuitStateDTO>("_pad0") == 60 &&
                   GetOffset<ExosuitFrameInputDTO>(nameof(ExosuitFrameInputDTO.MoveAxis)) == 0 &&
                   GetOffset<ExosuitFrameInputDTO>(nameof(ExosuitFrameInputDTO.VerticalAxis)) == 8 &&
                   GetOffset<ExosuitFrameInputDTO>(nameof(ExosuitFrameInputDTO.DesiredYawRadians)) == 12 &&
                   GetOffset<ExosuitFrameInputDTO>(nameof(ExosuitFrameInputDTO.ActionMask)) == 16 &&
                   GetOffset<ExosuitFrameInputDTO>(nameof(ExosuitFrameInputDTO.Frame)) == 20 &&
                   GetOffset<ExosuitFrameInputDTO>(nameof(ExosuitFrameInputDTO.GlobalQualityWeight)) == 24 &&
                   GetOffset<ExosuitTuningDTO>(nameof(ExosuitTuningDTO.SdfEpsilonMeters)) == 48 &&
                   GetOffset<ExosuitTuningDTO>(nameof(ExosuitTuningDTO.GravityMultiplier)) == 52 &&
                   GetOffset<ExosuitTuningDTO>(nameof(ExosuitTuningDTO.MaxSubsteps)) == 56 &&
                   GetOffset<ExosuitTuningDTO>(nameof(ExosuitTuningDTO.StateHash)) == 64;
#else
            return sizeOk;
#endif
        }

#if UNITY_EDITOR
        private static int GetOffset<T>(string fieldName) where T : struct
        {
            return Marshal.OffsetOf<T>(fieldName).ToInt32();
        }
#endif
    }
}
