using System.IO;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using MapMagic.Core;

namespace Hecton8.Diagnostics
{
    /// <summary>
    /// TASK 5: Compare raw graph heightmap vs eroded tile (Task D).
    /// Reads the live terrain from 020_RENDER_SANDBOX_V2 (already generated by Task 1)
    /// and the archived eroded asset from Task 3.
    /// Outputs: mean, std (in meters), min, max for both.
    /// </summary>
    public static class CompareErosionTask
    {
        public static void Run()
        {
            Debug.Log("[TASK_5] Starting erosion comparison (TASK_D)...");

            // --- A: Live terrain (generated by Task 1 / already in scene) ---
            var allTerrains = UnityEngine.Object.FindObjectsByType<Terrain>(FindObjectsInactive.Include);
            if (allTerrains == null || allTerrains.Length == 0)
            {
                Debug.LogError("[TASK_5][ERROR] No Terrain found in scene. Skipping comparison.");
                HeadlessRunAll.NextTask();
                return;
            }

            // Pick the MapMagic-owned terrain (first available)
            Terrain liveTerrain = allTerrains[0];
            PrintStats("[TASK_5][RAW]", liveTerrain.terrainData);

            // --- B: Archived eroded asset ---
            string erodedPath = "Assets/_Project/Data/World/Archive/ErodedTile_0_0.asset";
            var erodedData = AssetDatabase.LoadAssetAtPath<TerrainData>(erodedPath);
            if (erodedData == null)
            {
                Debug.LogError($"[TASK_5][ERROR] Eroded asset not found at '{erodedPath}'. Run Task 3 (OfflineErosionBakePipeline) first.");
            }
            else
            {
                PrintStats("[TASK_5][ERODED]", erodedData);
            }

            Debug.Log("[TASK_5] Erosion comparison complete.");
            HeadlessRunAll.NextTask();
        }

        private static void PrintStats(string tag, TerrainData data)
        {
            int w = data.heightmapResolution;
            float[,] h = data.GetHeights(0, 0, w, w);
            float sizeY = data.size.y;
            int count = w * w;

            float sum = 0f, sumSq = 0f, min = float.MaxValue, max = float.MinValue;
            for (int y = 0; y < w; y++)
            for (int x = 0; x < w; x++)
            {
                float v = h[y, x];
                sum   += v;
                sumSq += v * v;
                if (v < min) min = v;
                if (v > max) max = v;
            }

            float mean     = sum / count;
            float variance = (sumSq / count) - (mean * mean);
            float std      = Mathf.Sqrt(Mathf.Max(0f, variance));

            Debug.Log($"{tag} res={w}x{w} sizeY={sizeY}m | " +
                      $"mean={mean * sizeY:F2}m  std={std * sizeY:F2}m  " +
                      $"min={min * sizeY:F2}m  max={max * sizeY:F2}m  " +
                      $"range={(max - min) * sizeY:F2}m");
        }
    }
}
