using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Unity.Mathematics;

namespace Hecton8.Habitat.Deformation.Contracts
{
    /// <summary>
    /// Stable baked mesh state selected by structural pressure truth.
    /// </summary>
    public enum HabitatDamageMeshState : byte
    {
        Intact = 0,
        Stressed = 1,
        Ruptured = 2,
        Collapsed = 3
    }

    /// <summary>
    /// Aligned hash map from pristine habitat module geometry to baked static damage states. Size: 32 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct ModuleDamageStateMappingDTO
    {
        [FieldOffset(0)] public uint PristineMeshHash;
        [FieldOffset(4)] public uint StressedMeshHash;
        [FieldOffset(8)] public uint RupturedMeshHash;
        [FieldOffset(12)] public uint CollapsedMeshHash;
        [FieldOffset(16)] public uint _pad0;
        [FieldOffset(20)] public uint _pad1;
        [FieldOffset(24)] public uint _pad2;
        [FieldOffset(28)] public uint _pad3;
    }

    /// <summary>
    /// Primitive collision proxy generated by the offline baker. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct HabitatDamageHullDTO
    {
        [FieldOffset(0)] public float3 Center;
        [FieldOffset(12)] public byte Shape;
        [FieldOffset(13)] public byte State;
        [FieldOffset(14)] public ushort Flags;
        [FieldOffset(16)] public float3 Size;
        [FieldOffset(28)] public float Radius;
        [FieldOffset(32)] public quaternion Rotation;
        [FieldOffset(48)] public uint ModuleHash;
        [FieldOffset(52)] public uint HullHash;
        [FieldOffset(56)] public uint _pad0;
        [FieldOffset(60)] public uint _pad1;
    }

    /// <summary>
    /// Editor/CI telemetry row for the offline habitat damage baker. Size: 64 bytes.
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct HabitatDamageBakeTelemetryEntry
    {
        [FieldOffset(0)] public uint Frame;
        [FieldOffset(4)] public uint ModuleHash;
        [FieldOffset(8)] public uint StateHash;
        [FieldOffset(12)] public int SourceTriangleCount;
        [FieldOffset(16)] public int OutputTriangleCount;
        [FieldOffset(20)] public int TornTriangleCount;
        [FieldOffset(24)] public int HullCount;
        [FieldOffset(28)] public float GlobalQualityWeight;
        [FieldOffset(32)] public float BurstJobMilliseconds;
        [FieldOffset(36)] public uint FaultFlags;
        [FieldOffset(40)] public uint OutputMeshHash;
        [FieldOffset(44)] public uint _pad0;
        [FieldOffset(48)] public ulong _pad1;
        [FieldOffset(56)] public ulong _pad2;
    }

    /// <summary>
    /// Owner-local reserved IDs for consumers that import baked habitat damage data into GlobalDataVault.
    /// </summary>
    public static class HabitatDamageBakeVaultContract
    {
        public const int MappingBufferId = 73320;
        public const int HullBufferId = 73321;
        public const int TelemetryRingBufferId = 73322;
        public const int TelemetryCursorBufferId = 73323;
        public const int MaxMappingCount = 4096;
        public const int MaxHullCount = 32768;
        public const int TelemetryFrameCount = 300;
    }

    /// <summary>
    /// Branch-light selector for immutable baked mesh hashes. No UnityEngine object reference crosses this contract.
    /// Pressure reaches all baked states; visual buckling scalar stays continuous between thresholds.
    /// </summary>
    public static class HabitatDamageMeshStateResolver
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte ResolveStateIndex(float pressure01)
        {
            float p = math.saturate(math.isfinite(pressure01) ? pressure01 : 0f);
            float stressed = math.step(0.33333334f, p);
            float ruptured = math.step(0.6666667f, p);
            float collapsed = math.step(0.95f, p);
            return (byte)(stressed + ruptured + collapsed);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float ResolveVisualBuckling01(float pressure01)
        {
            float p = math.saturate(math.isfinite(pressure01) ? pressure01 : 0f);
            return math.smoothstep(0.33333334f, 0.95f, p);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint ResolveMeshHash(in ModuleDamageStateMappingDTO mapping, byte stateIndex)
        {
            int state = math.clamp((int)stateIndex, 0, 3);
            uint hash = mapping.PristineMeshHash;
            hash = math.select(hash, mapping.StressedMeshHash, state >= 1);
            hash = math.select(hash, mapping.RupturedMeshHash, state >= 2);
            hash = math.select(hash, mapping.CollapsedMeshHash, state >= 3);
            return hash;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint ResolveMeshHash(in ModuleDamageStateMappingDTO mapping, float pressure01)
        {
            return ResolveMeshHash(in mapping, ResolveStateIndex(pressure01));
        }
    }
}
