Date: 2026-05-18
Agent: SHINOBU_22
Domain: DIEGETIC_TOOL_KINEMATICS
Status: CORE TASKS COMPLETE / DOMAIN STATIC PASS / PROJECT COMPILE WALL OUTSIDE DOMAIN / RUNTIME PROOF PENDING

## Initial Boundary
Problem: VR held tools need stable hand IK, hit testing, recoil, and feedback without Unity Rigging, Raycast, FixedJoint, or LineRenderer dependency.
Solution: Build a vault-backed tool kinematics lane with Burst analytical two-bone IK, analytic mock SDF raymarch, trigonometric collision/recoil fake, fixed-size DTOs, and editor facade.
Rejected Alternatives: Unity Animator IK and Unity Rigging require main-thread object synchronization; Physics.Raycast/FixedJoint would reintroduce VR jitter and collision spikes; LineRenderer is a renderer-side GameObject path.
Scalability potential: Low snaps tool to controller and throttles ray steps; Middle keeps raymarch + heat; High enables recoil and beam tube; Ultra spends saved cycles on dense beam vertices and lower jitter.
Hardware Impact: Expected low-end i3/MX350 savings are from removing physics queries and rigging graph sync from held-tool hot paths; budget target remains under 0.1 ms for active tool math, pending profiler proof.

## Decision 01 - Mock Tool Archaeology Fallback
Problem: Required legacy tool_specifications/equipment_recoil binary files were not present in Docs/Archive, StreamingAssets, or Assets/StreamingAssets; existing rationale logs did not define a usable byte layout.
Solution: Seed GlobalDataVault ToolKinematicsStates with emergency mock tools and default tuning; keep data unmanaged and deterministic.
Rejected Alternatives: Blocking on Inventory/Voxel agents or inventing direct dependencies on terrain/inventory runtime.
Scalability potential: Low uses two seeded tools and low ray steps; Middle keeps heat/energy; High enables recoil and beam tube; Ultra spends budget on dense beam vertices.
Hardware Impact: i3/MX350 avoids binary loader stalls and gets deterministic startup; cold seed estimate 3.0 us per slot.

## Decision 02 - Analytical IK Instead Of Animator/Rigging
Problem: VR hands jitter when held tools are driven through Animator IK or Unity Rigging sync points.
Solution: Added Burst TwoBoneIKJob that computes shoulder/elbow/wrist via law of cosines from camera-relative controller data.
Rejected Alternatives: Animator.SetIKPosition, Unity Rigging constraints, FABRIK refactor of unrelated legacy job.
Scalability potential: Low tier snaps tool to controller; Middle/High/Ultra use analytical elbow solve with pole vector.
Hardware Impact: i3/MX350 avoids main-thread rig graph work; estimate 1.5 us low, 8.0 us normal per arm.

## Decision 03 - SDF Raymarch Instead Of PhysX Query
Problem: Held tools need hit detection and collision feel without Physics.Raycast or wall collision spikes.
Solution: SdfRaymarchJob samples a local MockSDF, steps by distance, returns ToolHitResultDTO, and applies a spring recoil fake when the tip penetrates.
Rejected Alternatives: Physics.Raycast, RaycastAll, FixedJoint, Rigidbody collision, complex contact solver.
Scalability potential: Low 24 steps; Middle 40; High 56; Ultra 72 with stronger beam detail.
Hardware Impact: i3/MX350 pays bounded L1 math only; estimate 6.0 us low, 14.0 us ultra for raymarch path.

## Decision 04 - Direct DTO Mutation And ARM64 Layout
Problem: CS1612 copy-back and bad padding would corrupt hot path state and break ARM64 SIMD/cache alignment.
Solution: Explicit-layout DTOs: ToolStateDTO 56 bytes, ToolHitResultDTO 32 bytes, ScreenExport 16 bytes, Recoil/IK/Telemetry 64 bytes; runtime validates sizes and exposes ref access through VaultBufferHandle.GetElementAsRef.
Rejected Alternatives: get/set properties, Pack=1 structs, managed class wrappers.
Scalability potential: All tiers share one ABI; high-tier only adds more work in separate buffers.
Hardware Impact: i3/MX350 gets predictable cache lines; estimated 0.2-0.4 us saved per state/hit mutation lane.

## Decision 05 - Decoupled Signals For Heat, Sparks, And Carving
Problem: Tool runtime is blind to VFX, terrain modifier, and inventory domains.
Solution: Added MockTriggerPullSignal, MockCarveRequestSignal, ToolHeatSignal, and VfxSparkRequestSignal; runtime publishes after the post-fixed job swap.
Rejected Alternatives: Direct calls to Agent 05/18/19 systems, Instantiate sparks, inventory SOA writes from kinematics.
Scalability potential: Low sheds visual consumers externally; Middle/High/Ultra keep richer spark/beam data without changing kinematics authority.
Hardware Impact: i3/MX350 pays queue push only when needed; estimate 0.8-1.0 us per active signal batch.

## Decision 06 - Procedural Beam And Recoil
Problem: Tool heft must read as physical without animation clips, LineRenderer, or physics impulses.
Solution: Recoil uses a damped spring in ToolRecoilStateDTO; beam tube vertices are generated by Burst into a vault buffer with LOD ring counts.
Rejected Alternatives: Pre-baked recoil clips, LineRenderer, mesh GameObject construction, rigidbody kick.
Scalability potential: Low disables detail and writes minimal beam vertices; Middle/High/Ultra raise tube sides from 4 to 8.
Hardware Impact: i3/MX350 avoids renderer/object churn; estimate 4.0 us low and 12.0 us ultra beam generation.

## Decision 07 - Human Control Facade And CSV Override
Problem: Binary tuning data must remain editable by humans without managed per-frame parsing.
Solution: Added Tool Kinematics Tuner EditorWindow plus a SlowTick fixed-buffer CSV parser for equipment_stats.csv.
Rejected Alternatives: ScriptableObject tuning layer, CsvHelper/string.Split parser, per-frame file polling.
Scalability potential: Low/Middle/High/Ultra can be forced by SystemHealthIndex slider or CSV key without code reload.
Hardware Impact: i3/MX350 has zero hot-frame CSV cost; file read is cold and capped at 4096 bytes.

## Decision 08 - Black Box Failure Evidence
Problem: NaN or stuck raymarch must leave forensic state, not chat guesses.
Solution: 300-frame ToolKinematicsTelemetryEntry ring records heat, energy, hit distance, raymarch steps, flags, local tool position, and hit point; fault/NaN path dumps Docs/AgentLogs/Dump_TOOL_KINEMATICS.h8dump.
Rejected Alternatives: Debug.Log-only telemetry or frame debugger dependency.
Scalability potential: Same black box across tiers; high-tier writes richer visual data in parallel buffers.
Hardware Impact: i3/MX350 telemetry write estimate 1.2 us per active tool; crash dump is fault-only.

<SELF_AUDIT>
  <Question id="1" topic="Forbidden Unity APIs">No Physics.Raycast, RaycastAll, LineRenderer, FixedJoint, ConfigurableJoint, SpringJoint, Animator.SetIKPosition, Unity Rigging, GetComponent, FindObject, GameObject.Find, Update, FixedUpdate, or LateUpdate exists under Assets/_Project/Scripts/Tools/ToolKinematics. Verified by rg scan.</Question>
  <Question id="2" topic="ARM64 Layout">ToolStateDTO byte layout: double3 AUP offset 0 size 24; float3 Forward offset 24 size 12; float HeatLevel offset 36 size 4; uint ToolTypeHash offset 40 size 4; float EnergyRemaining offset 44 size 4; uint _pad0 offset 48 size 4; uint _pad1 offset 52 size 4; total 56 bytes. ToolHitResultDTO total 32 bytes.</Question>
  <Question id="3" topic="CS1612">Tool DTOs use raw public fields, not properties. Runtime uses NativeArray writes and ToolKinematicsVaultAccess ref returns through VaultBufferHandle.GetElementAsRef for direct unmanaged mutation.</Question>
  <Question id="4" topic="Mocks">MockSDF sampler, MockTriggerPullSignal, and MockCarveRequestSignal are local to the contracts assembly and require no inventory, terrain, VFX, or voxel-delta runtime dependency.</Question>
  <Question id="5" topic="Human Facade">Tool Kinematics Tuner EditorWindow writes tuning values to GlobalDataVault and visualizes raymarch hits/beam vertices via SceneView Handles.</Question>
  <Result>PASS_WITH_PROJECT_COMPILE_BLOCKED_BY_UNRELATED_EXISTING_ERRORS</Result>
</SELF_AUDIT>

## Ultra Polish Decision 17 - Signal Lane Prewarm
Problem: Local SHINOBU_22 signal DTOs were pushed through `SignalBus<T>` but their typed lanes were not configured before gameplay. That means the first `PostFixedTick` push could allocate NativeQueue/NativeList storage, violating the zero-GC hot-path intent.
Solution: Added `EnsureSignalLanesReady()` during `OnEnable()`. It configures and initializes `MockTriggerPullSignal`, `ToolHeatSignal`, `VfxSparkRequestSignal`, and `MockCarveRequestSignal` lanes with fixed capacities and SHINOBU_22 lane hashes before ticks begin.
Rejected Alternatives: Trusting `SignalBus<T>.TryPush()` lazy initialization, or moving signal storage into private NativeArrays.
Scalability potential: Low tier limits spark/carve frame signals to two while keeping trigger/heat lanes at full tool capacity; high/ultra keep richer visual routing without changing gameplay truth.
Hardware Impact: Removes first-use signal allocation from the active frame; cold OnEnable allocation only.

## Ultra Polish Decision 18 - Existing Tool Signal Bridge
Problem: The assignment required local mock/proof signals, but the project already has existing global tool lanes. Leaving all state only in SHINOBU-local signals would fragment the nervous system.
Solution: Kept the prompt-mandated mock DTOs and added a bridge into existing lanes that do not require World/Voxel/VFX runtime references: `ToolTriggerSignal`, `ToolStateChangedSignal`, and `ToolAcousticSignal` through `GlobalSignals.Publish`. Voxel carve and spark remain local mock/proof DTOs because the existing global carve/spark paths require AUP/World payloads and a foreign terrain/VFX authority.
Rejected Alternatives: Direct voxel/VFX class calls, adding `Hecton8.World` references back into the tool runtime, or deleting the prompt-mandated mock signals.
Scalability potential: Existing diegetic UI/audio consumers can observe tool state now; low tier still sheds cosmetic spark/carve traffic.
Hardware Impact: Expected cost remains queue push level, about 0.8 us per active signal batch when global lanes are already initialized; no managed allocation in the tick path.

## Ultra Polish Decision 19 - R4 Verification Boundary
Problem: A fresh verification pass was required after the signal-lane polish, and stale R2/R3 compile claims are not current truth.
Solution: Re-ran `dotnet restore Hecton8.Core.csproj`, `dotnet build Hecton8.Core.csproj --no-restore`, Unity batchmode R4, forbidden API scans, hot-path scans, BufferID collision audit, and CSV hash recomputation. Restore passed. CLI build is blocked outside ToolKinematics by missing UI/input/physics types (`ISignal`, `WakeRequestSignal`, `InputStateDTO`, `InputProfileDTO`, `MockCollisionSignal`). Unity R4 log did not reach meaningful script compile and contains startup return-code text `1`; it has no ToolKinematics compiler-error match.
Rejected Alternatives: Claiming a clean Unity compile from a startup-only log, or fixing unrelated UI/Input/Physics ownership from this domain.
Scalability potential: Domain remains isolated; compile-wall blast radius is not expanded.
Hardware Impact: No runtime impact; verification-only.

<SELF_AUDIT>
  <TwentyTaskCheck>
    <Task id="01" status="PASS">Binary archaeology and emergency mock seeding remain in place.</Task>
    <Task id="02" status="PASS">Unity IK/Rigging path remains absent; Burst two-bone IK remains authority.</Task>
    <Task id="03" status="PASS">DTOs remain raw-field/ref-capable; no property copy-back path.</Task>
    <Task id="04" status="PASS">ToolHitResultDTO remains explicit 32 bytes; ToolStateDTO remains explicit 56 bytes.</Task>
    <Task id="05" status="PASS">Prompt-mandated mock trigger/carve/SDF contracts remain, now with prewarmed SignalBus lanes.</Task>
    <Task id="06" status="PASS">TwoBoneIKJob still computes analytical elbow/wrist math.</Task>
    <Task id="07" status="PASS">SDF penetration still drives wrist-pivot Dear Lie recoil.</Task>
    <Task id="08" status="PASS">SdfRaymarchJob remains bounded and no Raycast path exists.</Task>
    <Task id="09" status="PASS">Heat/cooling/overheat still update in DTO and bridge to tool state lanes.</Task>
    <Task id="10" status="PASS">Energy drains locally and low power disables Active/BeamActive.</Task>
    <Task id="11" status="PASS">Procedural recoil remains code-driven and Low tier zeros it.</Task>
    <Task id="12" status="PASS">Beam vertex tube remains vault-generated, no LineRenderer.</Task>
    <Task id="13" status="PASS">SystemHealthIndex still maps Low/Middle/High/Ultra.</Task>
    <Task id="14" status="PASS">AUP remains double3; math consumes camera-relative float3 deltas.</Task>
    <Task id="15" status="PASS">ToolScreenExportDTO remains 16 bytes and feeds bridge distance/material.</Task>
    <Task id="16" status="PASS">Spark intent remains SignalBus DTO, not Instantiate; low-tier lane cap is two.</Task>
    <Task id="17" status="PASS">300-frame telemetry ring and .h8dump fatal path remain active.</Task>
    <Task id="18" status="PASS">Editor tuner facade remains live and runtime no longer overwrites valid vault tuning.</Task>
    <Task id="19" status="PASS">CSV parser hashes rechecked and constants match live parser output.</Task>
    <Task id="20" status="PASS">SceneView gizmo remains local-space and AUP-safe.</Task>
  </TwentyTaskCheck>
  <ARM64Check>Runtime DTO layout unchanged and explicit: ToolStateDTO 56; ToolHitResultDTO 32; ToolScreenExportDTO 16; ToolKinematicsTuningDTO 48; FrameInput 96; IkOutput 64; RecoilState 64; BeamVertex 32; PoseOutput 96; TelemetryEntry 64; MockSdfSample 8; local signal DTOs 16/48/24/40. No ToolKinematics struct uses Pack=1.</ARM64Check>
  <ZeroGCCheck>SignalBus local lanes are configured/initialized in OnEnable before gameplay pushes. FixedTick/PostFixedTick code uses value DTOs, for-loops, vault NativeArrays, and typed queues; static scan remains clean for LINQ, foreach, new NativeArray, Allocator.Temp, Raycast, LineRenderer, GetComponent, Find, and Unity Update methods.</ZeroGCCheck>
  <AUPCheck>AUP is stored as double3 and only local deltas are downcast after subtracting CameraAup. Global bridges intentionally avoid AUP-carrying global carve/spark signals to prevent adding World dependency.</AUPCheck>
  <DearLieCheck>Low tier snaps to controller and sheds recoil. Higher tiers fake contact through SDF penetration, damped spring recoil, and wrist-pivot pose matrices.</DearLieCheck>
  <DependencyCheck>Runtime still has no `Hecton8.World` import and no sibling voxel/VFX/inventory dependency. Existing global tool lanes are used through `GlobalSignals`/typed signals; local mock lanes are assignment proof lanes.</DependencyCheck>
  <HPhiCheck>All hot arrays remain GlobalDataVault buffers. Local signal queues are SignalBus-managed native lanes, prewarmed outside gameplay ticks.</HPhiCheck>
  <BlackboxCheck>300-frame vault telemetry ring remains active; fatal dump target is Docs/AgentLogs/Dump_TOOL_KINEMATICS.h8dump.</BlackboxCheck>
  <CompileGuard>R4 restore passed. R4 dotnet build is blocked by unrelated UI/Input/Physics missing types. Unity R4 log is startup-only and not a script-compile proof. ToolKinematics static scans are clean.</CompileGuard>
</SELF_AUDIT>

## Verification Wall
Problem: Full project compile cannot isolate SHINOBU_22 because the workspace already contains unrelated missing source/type errors.
Solution: Earlier verification hit unrelated full-solution walls, so the domain was rechecked with a narrower gate. Unity 6000.4.1f1 batch import R2 exited 0 without ToolKinematics compiler-error matches, and targeted `dotnet build Hecton8.Core.csproj --no-restore` now passes after restore with 0 errors and one unrelated CS2002 duplicate-source warning.
Rejected Alternatives: Reverting or editing unrelated RealtimeCSG/Construction/DroneFleet code; that is outside the assigned domain.
Scalability potential: ToolKinematics code remains self-contained behind contracts/vault buffers; no sibling domain reference added.
Hardware Impact: No runtime impact; full Play Mode/profiler/player proof remains pending by project policy.

## Polish Gate - Assembly Dependency Trim
Problem: Post-core CURRENT_BATCH scan found no <POLISH_MANDATE> tag, but the available self-reflection mandate required dependency audit before final output.
Solution: Removed unnecessary Hecton8.Core.Contracts and Hecton8.World.Contracts references from Hecton8.Tools.ToolKinematics.asmdef; kept GlobalRegistry/SignalBus through Hecton8.Core and memory contracts through Hecton8.Core.Memory.
Rejected Alternatives: Keeping broad references "just in case"; adding direct references to sibling inventory, VFX, voxel, or rendering runtime domains.
Scalability potential: Smaller assembly graph reduces rebuild blast radius for Low/Middle/High/Ultra tool tuning changes.
Hardware Impact: No runtime frame impact; editor/import graph is narrower and safer.

## Ultra Polish Decision 09 - Pivot-Correct Pose Output Lane
Problem: The first recoil pass exported hit/recoil state but did not expose a final wrist-pivot transform lane for downstream render/tool presentation.
Solution: Added `ToolPoseOutputDTO` as a 96-byte explicit-layout vault buffer and `BufferID.ToolKinematicsPoseOutputs = 619`. `SdfRaymarchJob` now writes a finite-checked `float4x4` plus recoil offset/radians, using `PivotLocal` compensation so the fake collision rotates around the wrist instead of sliding the whole tool body.
Rejected Alternatives: Unity Rigging constraint, FixedJoint collision, runtime Transform mutation, and a visual-only GameObject bridge. These reintroduce main-thread sync or physics jitter.
Scalability potential: Low ignores recoil and writes controller snap; Middle/High/Ultra keep pivot recoil and can feed richer visual overkill without changing gameplay truth.
Hardware Impact: i3/MX350 keeps bounded math in the same Burst job; estimated 2.5 us collision-feel cost instead of an unbounded contact/constraint path.

## Ultra Polish Decision 10 - CSV I/O Evicted From Dispatcher Thread
Problem: The previous CSV override path was cold but still used file timestamp and FileStream work from `SlowTick`, which can hitch on Steam Deck MicroSD or slow laptop storage.
Solution: Added a background CSV watcher thread with fixed 4096-byte I/O, pending, and consume buffers. The dispatcher now copies fixed bytes under a short lock and parses ASCII only when a new sequence arrives. I/O faults set `CsvIoFault` into tuning flags and therefore into telemetry.
Rejected Alternatives: Main-thread FileStream polling, FileSystemWatcher allocation churn, CsvHelper/string-split parser, and full MMF machinery for a 4 KB tuning file.
Scalability potential: Low tier avoids storage hitches; Ultra tier can still hot-reload richer tool tuning without code recompilation.
Hardware Impact: Hot-frame cost remains 0 us; cold SlowTick parse is bounded to 4096 bytes.

## Ultra Polish Decision 11 - ARM64 Runtime Layout Audit
Problem: The ultra mandate required proof that runtime structs were not packed or implicitly aligned in a way that kills ARM64 cache behavior.
Solution: Re-scanned ToolKinematics for `Pack=1` and sequential runtime layout; no matches. Primary DTO layouts are explicit and multiples of 8: ToolStateDTO 56, ToolHitResultDTO 32, ScreenExport 16, Tuning 48, FrameInput 96, IkOutput 64, Recoil 64, BeamVertex 32, PoseOutput 96, Telemetry 64, MockSdfSample 8.
Rejected Alternatives: `[StructLayout(Pack=1)]`, C# auto-layout classes, properties around NativeArrays, and local private NativeArray ownership.
Scalability potential: One ABI works across Quest/ARM64, Steam Deck, MX350, and desktop; Ultra adds buffer consumers, not different struct truth.
Hardware Impact: Estimated 0.2-0.4 us saved per direct hot DTO mutation lane, with lower ARM64 misalignment risk.

## Ultra Polish Decision 12 - Compile Guard And Dependency Boundary
Problem: The project has concurrent agent churn, so compile evidence must distinguish this domain from unrelated Core graph failures.
Solution: Unity 6000.4.1f1 batch import R2 exited 0 with no `error CS`, `Compilation failed`, `ToolKinematics`, or `Exception` matches in the captured log. `dotnet restore Hecton8.Core.csproj` succeeded, then `dotnet build Hecton8.Core.csproj --no-restore` succeeded with 0 errors and one pre-existing CS2002 duplicate-source warning for `HectonPhysicsContract.cs`. Runtime asmdef still avoids sibling inventory/VFX/voxel references.
Rejected Alternatives: Editing unrelated Ecosystem/World/Construction/DroneFleet code, or claiming Play Mode/profiler proof from static imports.
Scalability potential: Narrow assembly graph protects iteration time while allowing production bridges through GlobalRegistry/SignalBus.
Hardware Impact: No frame impact; developer hardware impact is reduced rebuild blast radius and a targeted compile gate.

<SELF_AUDIT>
  <TwentyTaskCheck>
    <Task id="01" status="PASS">Binary archaeology executed; no valid legacy binary found; emergency mock tools seed vault data.</Task>
    <Task id="02" status="PASS">Unity IK/Rigging forbidden path absent; Burst law-of-cosines IK implemented.</Task>
    <Task id="03" status="PASS">ToolStateDTO uses raw fields and ref-capable vault access, no DTO properties.</Task>
    <Task id="04" status="PASS">ToolHitResultDTO is explicit 32 bytes; ToolStateDTO is explicit 56 bytes.</Task>
    <Task id="05" status="PASS">MockSDF, MockTriggerPullSignal, and MockCarveRequestSignal exist for blind dependency proof.</Task>
    <Task id="06" status="PASS">TwoBoneIKJob computes shoulder/elbow/wrist in Burst.</Task>
    <Task id="07" status="PASS">SDF penetration drives Dear Lie spring recoil and wrist-pivot pose output.</Task>
    <Task id="08" status="PASS">SdfRaymarchJob steps analytic SDF, flags budget saturation, no Physics.Raycast.</Task>
    <Task id="09" status="PASS">Heat ramp/cooling/overheat flags and ToolHeatSignal are implemented.</Task>
    <Task id="10" status="PASS">Energy drains locally in ToolStateDTO; inventory coupling rejected.</Task>
    <Task id="11" status="PASS">Critically damped recoil state is procedural, vault-backed, and Low-tier disabled.</Task>
    <Task id="12" status="PASS">Beam tube vertices are generated by Burst into vault buffers, no LineRenderer.</Task>
    <Task id="13" status="PASS">SystemHealthIndex selects Low/Middle/High/Ultra math LODs.</Task>
    <Task id="14" status="PASS">AUP stays double3; raymarch/collision math uses camera-relative float3 deltas.</Task>
    <Task id="15" status="PASS">ToolScreenExportDTO is explicit 16 bytes.</Task>
    <Task id="16" status="PASS">VfxSparkRequestSignal routes spark intent without Instantiate.</Task>
    <Task id="17" status="PASS">300-frame telemetry ring exists; NaN/fault/budget overflow dumps blackbox .h8dump.</Task>
    <Task id="18" status="PASS">Tool Kinematics Tuner EditorWindow writes vault tuning.</Task>
    <Task id="19" status="PASS">CSV override now uses fixed buffers plus background I/O handoff; parser is no-string ASCII.</Task>
    <Task id="20" status="PASS">SceneView gizmo visualizer draws ray, hit normal, and beam tube from vault DTOs.</Task>
  </TwentyTaskCheck>
  <ARM64Check>
    <ToolStateDTO>0 double3 AUP 24; 24 float3 Forward 12; 36 float HeatLevel 4; 40 uint ToolTypeHash 4; 44 float EnergyRemaining 4; 48 uint _pad0 4; 52 uint _pad1 4; total 56.</ToolStateDTO>
    <ToolPoseOutputDTO>0 float4 c0 16; 16 float4 c1 16; 32 float4 c2 16; 48 float4 c3 16; 64 float3 RecoilOffset 12; 76 float RecoilRadians 4; 80 uint Flags 4; 84/88/92 uint pads; total 96.</ToolPoseOutputDTO>
    <MockSdfSample>0 float Distance 4; 4 uint MaterialHash 4; total 8.</MockSdfSample>
  </ARM64Check>
  <ZeroGCCheck>FixedTick/PostFixedTick jobs use for-loops, NativeArrays, and vault handles. No LINQ, foreach, new NativeArray, Allocator.Temp, string split, Raycast, LineRenderer, or Unity Update methods in ToolKinematics. CSV FileStream allocation is background cold path; dump FileStream is fatal-only blackbox path.</ZeroGCCheck>
  <AUPCheck>Tool AUP is stored as double3. Per-frame raymarch/collision subtracts camera AUP and casts only the local delta to float3 through ToLocalFloat3; absolute 100km positions are never directly downcast for SDF math.</AUPCheck>
  <DearLieCheck>Rigidbody contact was replaced with SDF tip penetration, damped spring recoil, wrist-pivot compensation, and finite-checked pose matrices. Low tier fakes mass by snapping the tool and omitting recoil.</DearLieCheck>
  <DependencyCheck>Runtime uses GlobalRegistry DataVault, dispatcher tick registration, and typed SignalBus lanes. No direct inventory, VFX, voxel, terrain modifier, Unity Rigging, or sibling runtime assembly dependency was added. Existing global Debris/Voxel signals were observed; local mock signals remain proof contracts because the assignment explicitly required them.</DependencyCheck>
  <HPhiCheck>All NativeArrays are resolved from GlobalDataVault through VaultBufferHandle fields. Jobs are stateless kernels over vault buffers. No private NativeArray fields or update-loop allocations exist in this domain.</HPhiCheck>
  <BlackboxCheck>ToolKinematicsTelemetryEntry ring is 300 frames per tool and dumps to Docs/AgentLogs/Dump_TOOL_KINEMATICS.h8dump on Fault, NaN, or raymarch budget saturation.</BlackboxCheck>
  <CompileGuard>Superseded by Ultra Polish R2 evidence below: current project compile is blocked by unrelated UI/Core errors; ToolKinematics static scans remain clean.</CompileGuard>
</SELF_AUDIT>

## Ultra Polish Decision 13 - Human Tuning Sovereignty
Problem: The EditorWindow facade wrote directly to the tuning vault buffer, but the runtime then rewrote the same DTO every FixedTick from serialized fields. Designer edits were therefore visually accepted and functionally discarded.
Solution: Added `_tuningDirty` ownership. `OnValidate()` and CSV overrides mark serialized tuning dirty; otherwise `WriteTuning()` preserves a valid vault DTO and only updates the CSV fault flag.
Rejected Alternatives: ScriptableObject indirection, reflection-based editor sync, or letting the runtime be the only tuning owner.
Scalability potential: Low/Middle/High/Ultra tuning can be balanced live without C# recompilation or fighting FixedTick writes.
Hardware Impact: Hot cost is one predictable branch and one DTO read/write; editor and CSV paths stay cold.

## Ultra Polish Decision 14 - Low-Tier And Fault Flag Hygiene
Problem: Low tier still carried parts of recoil state math and `BeamActive` could survive overheat or energy depletion for one downstream consumer frame.
Solution: `SdfRaymarchJob` now zeros recoil state in Low tier, normalizes controller quaternions through `SafeNormalizeQuaternion`, and clears `Active | BeamActive` on idle, overheat, and low-power transitions.
Rejected Alternatives: Leaving visual cleanup to VFX/render consumers or relying on Unity Transform state.
Scalability potential: Low tier becomes a strict controller snap path; higher tiers keep spring recoil and beam overkill.
Hardware Impact: Low tier saves about 1.5 us per active tool by evicting recoil spring math and prevents stale beam work.

## Ultra Polish Decision 15 - AUP-Safe Scene Gizmo
Problem: The SceneView gizmo mixed local-space raymarch hit points with a float cast of absolute `state.AUP`, which could show false jitter in large-world coordinates.
Solution: The editor visualizer now derives the start point from `ToolPoseOutputDTO.MatrixColumn3` or `ToolKinematicsFrameInputDTO.ControllerLocalPosition`, both already local. Absolute double3 AUP is not downcast for gizmo rays.
Rejected Alternatives: Using `state.AUP` directly in editor drawing or adding a renderer-domain bridge.
Scalability potential: Debugging remains truthful on a 100x100km world; all hardware tiers inspect the same local-space truth.
Hardware Impact: Editor-only, no runtime frame impact.

## Ultra Polish Decision 16 - Compile Wall R3 Evidence
Problem: The previous targeted compile proof was stale after the second polish pass and concurrent agents introduced new unrelated project compile errors.
Solution: Re-ran restore/build/import. `dotnet restore Hecton8.Core.csproj` passed. `dotnet build Hecton8.Core.csproj --no-restore` is currently blocked by unrelated UI `SubtitleManager.cs` missing methods: `ShowSubtitleCommand`, `EnqueueSubtitleCommand`, `AdvanceTmpTypewriter`, `StopTmpTypewriter`, `TryDequeueSubtitleCommand`. Unity import R3 exited 0 but its log reports unrelated Core `HomeostasisBrain.ScalabilityDictatorFallback.cs` duplicate CS0111 members. The R3 log has no ToolKinematics match.
Rejected Alternatives: Editing UI/Core Homeostasis from the ToolKinematics domain, or reporting a stale compile pass.
Scalability potential: Domain remains isolated behind `GlobalRegistry`, `GlobalDataVault`, and typed signals; no sibling runtime reference was added.
Hardware Impact: No runtime impact; developer iteration is protected by not expanding the compile blast radius.

<SELF_AUDIT>
  <TwentyTaskCheck>
    <Task id="01" status="PASS">Legacy binary reconnaissance executed; emergency mock tool data seeds GlobalDataVault when no binary spec exists.</Task>
    <Task id="02" status="PASS">Unity Rigging and Animator IK are absent; analytical Burst two-bone IK is implemented.</Task>
    <Task id="03" status="PASS">DTOs use raw fields and ref-capable vault access; no CS1612 property copy path.</Task>
    <Task id="04" status="PASS">Runtime DTO sizes are explicit and multiples of 8; no Pack=1 exists under ToolKinematics.</Task>
    <Task id="05" status="PASS">Mock SDF, mock trigger, and mock carve contracts exist without terrain/inventory coupling.</Task>
    <Task id="06" status="PASS">TwoBoneIKJob uses law-of-cosines shoulder/elbow/wrist math.</Task>
    <Task id="07" status="PASS">SDF penetration drives procedural recoil instead of collision physics.</Task>
    <Task id="08" status="PASS">SdfRaymarchJob performs bounded analytic SDF marching; no Physics.Raycast path exists.</Task>
    <Task id="09" status="PASS">Heat ramp, cooling, overheat flagging, and ToolHeatSignal export are implemented.</Task>
    <Task id="10" status="PASS">Energy drains in ToolStateDTO and disables Active/BeamActive on depletion.</Task>
    <Task id="11" status="PASS">Recoil is a procedural spring in ToolRecoilStateDTO; Low tier zeros it.</Task>
    <Task id="12" status="PASS">Beam vertices are generated into vault buffers; no LineRenderer exists.</Task>
    <Task id="13" status="PASS">SystemHealthIndex maps Low/Middle/High/Ultra math LODs.</Task>
    <Task id="14" status="PASS">AUP is double3; math uses camera-relative float3 deltas only.</Task>
    <Task id="15" status="PASS">ToolScreenExportDTO is 16 bytes and unmanaged.</Task>
    <Task id="16" status="PASS">Spark intent routes through typed signal DTOs; no Instantiate path.</Task>
    <Task id="17" status="PASS">300-frame blackbox ring writes ToolKinematicsTelemetryEntry and dumps .h8dump on fatal state.</Task>
    <Task id="18" status="PASS">Editor tuner facade writes live vault tuning without runtime overwrite after R2 fix.</Task>
    <Task id="19" status="PASS">CSV override uses background fixed-buffer I/O and ASCII parsing without string split.</Task>
    <Task id="20" status="PASS">SceneView raymarch visualizer uses local pose/frame buffers and draws ray, normal, beam tube.</Task>
  </TwentyTaskCheck>
  <ARM64Check>
    <ToolStateDTO>0 double3 AUP 24; 24 float3 Forward 12; 36 float HeatLevel 4; 40 uint ToolTypeHash 4; 44 float EnergyRemaining 4; 48 uint _pad0 4; 52 uint _pad1 4; total 56.</ToolStateDTO>
    <ToolKinematicsFrameInputDTO>0 double3 CameraAup 24; 24 float3 ControllerLocalPosition 12; 36 quaternion ControllerRotation 16; 52 float3 ShoulderLocalPosition 12; 64 float3 PoleLocalDirection 12; 76 float DeltaTime 4; 80 float SystemHealthIndex 4; 84 uint TriggerFlags 4; 88 uint FrameIndex 4; 92 uint _pad0 4; total 96.</ToolKinematicsFrameInputDTO>
    <ToolPoseOutputDTO>0 float4 c0 16; 16 float4 c1 16; 32 float4 c2 16; 48 float4 c3 16; 64 float3 RecoilOffset 12; 76 float RecoilRadians 4; 80 uint Flags 4; 84/88/92 uint pads; total 96.</ToolPoseOutputDTO>
    <TelemetryEntry>0 uint FrameIndex 4; 4 uint ToolHash 4; 8 float Heat 4; 12 float Energy 4; 16 float HitDistance 4; 20 int Steps 4; 24 float IkEstimate 4; 28 uint Flags 4; 32 float3 ToolLocalPosition 12; 44 float3 HitPoint 12; 56 uint MaterialHash 4; 60 uint pad; total 64.</TelemetryEntry>
  </ARM64Check>
  <ZeroGCCheck>FixedTick/PostFixedTick scheduling and Burst jobs use NativeArrays, for-loops, value DTOs, and vault handles. Static scan found no LINQ, foreach, new NativeArray, Allocator.Temp, string split, Raycast, LineRenderer, Unity Update method, GetComponent, or Find path in ToolKinematics. FileStream is background CSV cold path and fatal-only blackbox path.</ZeroGCCheck>
  <AUPCheck>ToolStateDTO.AUP stays double3. SDF, recoil, beam, telemetry, and editor gizmo math use local float3 derived after subtracting CameraAup; absolute AUP is not directly cast to float.</AUPCheck>
  <DearLieCheck>RigidBody/FixedJoint contact is faked by SDF tip penetration, damped spring recoil, and wrist-pivot pose matrix. Low tier fakes mass by snapping to controller and disabling recoil overkill.</DearLieCheck>
  <DependencyCheck>Runtime uses GlobalRegistry/DataVault/SignalBus only. Removed Hecton8.World namespace and DispatcherJobSwap usage. No inventory, VFX, voxel, terrain, renderer, Unity Rigging, or sibling runtime assembly dependency was added.</DependencyCheck>
  <HPhiCheck>All hot arrays are vault buffers resolved via VaultBufferHandle. Jobs are stateless kernels over those buffers. No private NativeArray fields or update-loop allocations exist in the domain.</HPhiCheck>
  <BlackboxCheck>ToolKinematicsTelemetryEntry ring is 300 frames per tool. Fatal state writes Docs/AgentLogs/Dump_TOOL_KINEMATICS.h8dump.</BlackboxCheck>
  <CompileGuard>R3 restore passed. R3 dotnet build is blocked by unrelated UI SubtitleManager errors. R3 Unity log is blocked by unrelated Homeostasis duplicate CS0111 errors. No ToolKinematics compile-error match was found; domain forbidden API scans are clean.</CompileGuard>
</SELF_AUDIT>
