namespace Hecton8.Optimization
{
    internal static partial class GeneratedAssetGuidIdTable
    {
        // Generated by Hecton8/Bootstrap/Generate PreInit Asset GUID Map.
        internal const int RecordCount = 0;

        internal static void CopyTo(Unity.Collections.NativeArray<AssetGuidIdRecord> records)
        {
        }
    }
}
