using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using H8BridgeFacadeRuntime = global::Hecton8.Core.Bridge.H8BridgeFacadeRuntime;
using H8DesignDataFacade = global::Hecton8.Core.Bridge.H8DesignDataFacade;

namespace Hecton8.Core.Bridge.EditorTools
{
    public static class H8BridgeContractGenerator
    {
        private const string OutputPath = "Assets/_Project/Scripts/Core/Bridge/Generated/H8DesignFacadeContracts.generated.cs";

        [MenuItem("Hecton-8/Bridge/Generate Design Facade Contracts")]
        public static void GenerateAllContracts()
        {
            string[] guids = AssetDatabase.FindAssets("t:H8DesignDataFacade");
            StringBuilder builder = new StringBuilder(4096);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("namespace Hecton8.Core.Bridge.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class H8DesignFacadeContracts");
            builder.AppendLine("    {");

            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                H8DesignDataFacade facade = AssetDatabase.LoadAssetAtPath<H8DesignDataFacade>(path);
                if (facade == null)
                    continue;

                uint assetHash = global::Hecton8.Core.Bridge.H8BridgeHashes.ComputeFnv1A(path);
                for (int j = 0; j < facade.BindingCount; j++)
                {
                    H8DesignDataFacade.FloatBinding binding = facade.GetBinding(j);
                    if (binding == null)
                        continue;

                    int alignedOffsetBytes = H8BridgeFacadeRuntime.AlignFloatOffsetBytes(binding.OffsetBytes);
                    string identifier = MakeIdentifier(binding.DisplayName, assetHash, binding.FieldHash, j);
                    builder.Append("        public const float ");
                    builder.Append(identifier);
                    builder.Append(" = ");
                    builder.Append(binding.Value.ToString("R", CultureInfo.InvariantCulture));
                    builder.AppendLine("f;");

                    builder.Append("        public const int ");
                    builder.Append(identifier);
                    builder.Append("_OffsetBytes = ");
                    builder.Append(alignedOffsetBytes.ToString(CultureInfo.InvariantCulture));
                    builder.AppendLine(";");

                    builder.Append("        public const uint ");
                    builder.Append(identifier);
                    builder.Append("_Hash = ");
                    builder.Append(binding.FieldHash.ToString(CultureInfo.InvariantCulture));
                    builder.AppendLine("u;");
                }
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            string fullPath = Path.GetFullPath(OutputPath);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(fullPath, builder.ToString());
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log("[H8Bridge] Design facade contracts generated.");
        }

        private static string MakeIdentifier(string source, uint assetHash, uint fieldHash, int bindingIndex)
        {
            if (string.IsNullOrEmpty(source))
                source = "Value";

            StringBuilder builder = new StringBuilder(source.Length + 8);
            for (int i = 0; i < source.Length; i++)
            {
                char c = source[i];
                if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_')
                {
                    builder.Append(c);
                    continue;
                }

                if (c >= '0' && c <= '9')
                {
                    if (builder.Length == 0)
                        builder.Append('_');
                    builder.Append(c);
                    continue;
                }

                if (builder.Length > 0 && builder[builder.Length - 1] != '_')
                    builder.Append('_');
            }

            if (builder.Length == 0)
                builder.Append("Value");

            if (IsCSharpKeyword(builder.ToString()))
                builder.Insert(0, '_');

            builder.Append("_");
            builder.Append(assetHash.ToString("X8", CultureInfo.InvariantCulture));
            builder.Append("_");
            builder.Append(fieldHash.ToString("X8", CultureInfo.InvariantCulture));
            builder.Append("_");
            builder.Append(bindingIndex.ToString(CultureInfo.InvariantCulture));
            return builder.ToString();
        }

        private static bool IsCSharpKeyword(string value)
        {
            switch (value)
            {
                case "abstract":
                case "as":
                case "base":
                case "bool":
                case "break":
                case "byte":
                case "case":
                case "catch":
                case "char":
                case "checked":
                case "class":
                case "const":
                case "continue":
                case "decimal":
                case "default":
                case "delegate":
                case "do":
                case "double":
                case "else":
                case "enum":
                case "event":
                case "explicit":
                case "extern":
                case "false":
                case "finally":
                case "fixed":
                case "float":
                case "for":
                case "foreach":
                case "goto":
                case "if":
                case "implicit":
                case "in":
                case "int":
                case "interface":
                case "internal":
                case "is":
                case "lock":
                case "long":
                case "namespace":
                case "new":
                case "null":
                case "object":
                case "operator":
                case "out":
                case "override":
                case "params":
                case "private":
                case "protected":
                case "public":
                case "readonly":
                case "ref":
                case "return":
                case "sbyte":
                case "sealed":
                case "short":
                case "sizeof":
                case "stackalloc":
                case "static":
                case "string":
                case "struct":
                case "switch":
                case "this":
                case "throw":
                case "true":
                case "try":
                case "typeof":
                case "uint":
                case "ulong":
                case "unchecked":
                case "unsafe":
                case "ushort":
                case "using":
                case "virtual":
                case "void":
                case "volatile":
                case "while":
                    return true;
                default:
                    return false;
            }
        }
    }
}
