using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using H8DesignDataFacade = global::Hecton8.Core.Bridge.H8DesignDataFacade;

namespace Hecton8.Core.Bridge.EditorTools
{
    public static class H8BridgeContractGenerator
    {
        private const string OutputPath = "Assets/_Project/Scripts/Core/Bridge/Generated/H8DesignFacadeContracts.generated.cs";

        [MenuItem("Hecton-8/Bridge/Generate Design Facade Contracts")]
        public static void GenerateAllContracts()
        {
            string[] guids = AssetDatabase.FindAssets("t:H8DesignDataFacade");
            StringBuilder builder = new StringBuilder(4096);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("namespace Hecton8.Core.Bridge.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class H8DesignFacadeContracts");
            builder.AppendLine("    {");

            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                H8DesignDataFacade facade = AssetDatabase.LoadAssetAtPath<H8DesignDataFacade>(path);
                if (facade == null)
                    continue;

                for (int j = 0; j < facade.BindingCount; j++)
                {
                    H8DesignDataFacade.FloatBinding binding = facade.GetBinding(j);
                    if (binding == null)
                        continue;

                    string identifier = MakeIdentifier(binding.DisplayName);
                    builder.Append("        public const float ");
                    builder.Append(identifier);
                    builder.Append(" = ");
                    builder.Append(binding.Value.ToString("R", CultureInfo.InvariantCulture));
                    builder.AppendLine("f;");

                    builder.Append("        public const int ");
                    builder.Append(identifier);
                    builder.Append("_OffsetBytes = ");
                    builder.Append(binding.OffsetBytes.ToString(CultureInfo.InvariantCulture));
                    builder.AppendLine(";");

                    builder.Append("        public const uint ");
                    builder.Append(identifier);
                    builder.Append("_Hash = ");
                    builder.Append(binding.FieldHash.ToString(CultureInfo.InvariantCulture));
                    builder.AppendLine("u;");
                }
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            string fullPath = Path.GetFullPath(OutputPath);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(fullPath, builder.ToString());
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log("[H8Bridge] Design facade contracts generated.");
        }

        private static string MakeIdentifier(string source)
        {
            if (string.IsNullOrEmpty(source))
                return "Value";

            StringBuilder builder = new StringBuilder(source.Length + 8);
            for (int i = 0; i < source.Length; i++)
            {
                char c = source[i];
                if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_')
                {
                    builder.Append(c);
                    continue;
                }

                if (c >= '0' && c <= '9')
                {
                    if (builder.Length == 0)
                        builder.Append('_');
                    builder.Append(c);
                    continue;
                }

                if (builder.Length > 0 && builder[builder.Length - 1] != '_')
                    builder.Append('_');
            }

            if (builder.Length == 0)
                builder.Append("Value");

            return builder.ToString();
        }
    }
}
