using Hecton8.Gameplay;
using Hecton8.Ecosystem;
using Hecton8.Meta;
using Hecton8.Core;
using UnityEngine;

namespace Hecton8.AI
{
    public partial class FaunaBrain
    {
        private const float InfectionHazardRadiusBase = 3f;
        private const float InfectionHazardIntensityBase = 0.9f;
        private const float PredatorThreatPulseHoldSeconds = 0.65f;
        private const float PredatorThreatPulseRadiusPadding = 4f;
        private const float PredatorThreatPulseStrengthBase = 0.28f;
        private const float PredatorThreatPulseStrengthAggressiveBonus = 0.16f;

        private static readonly int _ColorId = Shader.PropertyToID("_Color");
        private static readonly int _BaseColorId = Shader.PropertyToID("_BaseColor");
        private static readonly int _EmissionColorId = Shader.PropertyToID("_EmissionColor");

        // COLD ALLOC: MaterialPropertyBlock[1] - per-fauna infection tint overlay without material clones - owner: FaunaBrain
        private MaterialPropertyBlock _ecosystemPropertyBlock;
        private Vector3 _baseLocalScale = Vector3.one;
        private bool _baseLocalScaleCaptured;
        private float _baseAggroDistance;
        private float _baseDeaggroDistance;
        private float _baseAttackDamage;
        private float _baseCruiseSpeed;
        private float _baseBurstSpeed;
        private float _baseTurnSpeed;
        private float _baseMaxHealth = 1f;
        private float _runtimeAggressionScale = 1f;
        private FaunaGeneticTraits _geneticTraits;
        private bool _hasGeneticTraits;
        private bool _isInfected;
        private float _infectionSeverity;
        private int _infectionHazardSourceId;
        private string _lootProfileId = string.Empty;

        /// <summary>Returns true when this fauna instance currently carries the infection overlay.</summary>
        public bool IsInfected => _isInfected;

        /// <summary>Returns true when the instance represents poisoned non-predator loot.</summary>
        public bool HasPoisonedYield => _isInfected && !isAggressive;

        /// <summary>Authoring loot-profile identifier inherited from the applied archetype.</summary>
        public string LootProfileId => _lootProfileId;

        /// <summary>
        /// Applies deterministic runtime genetic traits generated by the ecosystem genetics owner.
        /// </summary>
        public void ApplyGeneticTraits(FaunaGeneticTraits traits)
        {
            _geneticTraits = traits;
            _hasGeneticTraits = true;
            ApplyRuntimeEcosystemOverlays();
        }

        /// <summary>
        /// Clears previously applied runtime genetic traits.
        /// </summary>
        public void ClearGeneticTraits()
        {
            _geneticTraits = default;
            _hasGeneticTraits = false;
            ApplyRuntimeEcosystemOverlays();
        }

        /// <summary>
        /// Applies or clears the infection overlay for the spawned fauna instance.
        /// </summary>
        public void SetInfectedState(bool infected, float severity)
        {
            _isInfected = infected;
            _infectionSeverity = infected ? Mathf.Clamp01(severity) : 0f;
            ApplyRuntimeEcosystemOverlays();
            UpdateInfectionHazardRegistration();
        }

        private void RefreshRuntimeEcosystemState()
        {
            if (_isDead)
            {
                ClearInfectionHazardRegistration();
                return;
            }

            float ecosystemHostilityScale = 1f;
            IEcosystemDirectorService ecosystemDirector = GlobalRegistry.EcosystemDirector;
            if (ecosystemDirector != null && ecosystemDirector.IsInitialized)
                ecosystemHostilityScale = Mathf.Lerp(1f, 1.35f, ecosystemDirector.BiomeHostility01);

            float nextAggressionScale = isAggressive ? DynamicDifficultyDirector.Current.PredatorAggressionScale * ecosystemHostilityScale : 1f;
            if (Mathf.Abs(nextAggressionScale - _runtimeAggressionScale) > 0.001f)
            {
                _runtimeAggressionScale = nextAggressionScale;
                ApplyRuntimeEcosystemOverlays();
            }

            UpdateInfectionHazardRegistration();
            UpdatePredatorThreatPulse();
        }

        private void ApplyRuntimeEcosystemOverlays()
        {
            EnsureBaseLocalScaleCaptured();

            float scaleMultiplier = _hasGeneticTraits ? _geneticTraits.ScaleMultiplier : 1f;
            float healthMultiplier = _hasGeneticTraits ? _geneticTraits.HealthMultiplier : 1f;
            float moveMultiplier = _hasGeneticTraits ? _geneticTraits.SpeedMultiplier : 1f;
            float aggressionMultiplier = Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f);

            if (_isInfected)
            {
                aggressionMultiplier *= Mathf.Lerp(1f, 1.12f, _infectionSeverity);
                healthMultiplier *= Mathf.Lerp(1f, 1.18f, _infectionSeverity);
            }

            transform.localScale = _baseLocalScale * scaleMultiplier;

            float previousHealthNormalized = _maxHealth > 0.001f ? _currentHealth / _maxHealth : 1f;
            _maxHealth = Mathf.Max(1f, _baseMaxHealth * healthMultiplier);
            _currentHealth = _isDead ? 0f : Mathf.Clamp(_maxHealth * previousHealthNormalized, 0f, _maxHealth);
            if (!_isDead && _currentHealth <= 0.001f)
                _currentHealth = _maxHealth;

            _sensorSuite.aggroDistance = Mathf.Max(0f, _baseAggroDistance * aggressionMultiplier);
            _sensorSuite.deaggroDistance = Mathf.Max(_sensorSuite.aggroDistance, _baseDeaggroDistance * aggressionMultiplier);
            _steeringEngine.moveSpeed = Mathf.Max(0.1f, _baseCruiseSpeed * moveMultiplier);
            _steeringEngine.maxSpeed = _steeringEngine.moveSpeed;
            _steeringEngine.turnSpeed = Mathf.Max(0.1f, _baseTurnSpeed * moveMultiplier);
            _steeringEngine.swimForce = Mathf.Max(_steeringEngine.moveSpeed, _baseBurstSpeed * moveMultiplier);

            ApplyInfectionVisuals();
        }

        private float ResolveCurrentAttackDamage()
        {
            float baseDamage = _baseAttackDamage > 0.001f
                ? _baseAttackDamage
                : (_speciesProfile != null ? _speciesProfile.attackDamage : _stateMachine.attackDamage);

            return Mathf.Max(0f, baseDamage * ResolveRuntimeAttackDamageMultiplier());
        }

        private float ResolveRuntimeAttackDamageMultiplier()
        {
            float multiplier = isAggressive ? Mathf.Lerp(1f, Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f), 0.65f) : 1f;
            if (_isInfected)
                multiplier *= Mathf.Lerp(1f, 1.22f, _infectionSeverity);

            return Mathf.Clamp(multiplier, 0.75f, 2.1f);
        }

        private float ResolveRuntimeSpeedMultiplierForState(AIState state)
        {
            switch (state)
            {
                case AIState.Aggressive:
                case AIState.Stalk:
                case AIState.Threaten:
                case AIState.Loom:
                case AIState.Feint:
                    float multiplier = Mathf.Lerp(1f, Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f), 0.55f);
                    if (_isInfected)
                        multiplier *= Mathf.Lerp(1f, 1.08f, _infectionSeverity);

                    return Mathf.Clamp(multiplier, 0.8f, 1.8f);

                default:
                    return 1f;
            }
        }

        private void ApplyInfectionVisuals()
        {
            if (_renderer == null)
                return;

            EnsureEcosystemPropertyBlock();
            _renderer.GetPropertyBlock(_ecosystemPropertyBlock);

            if (!_isInfected)
            {
                _ecosystemPropertyBlock.Clear();
                _renderer.SetPropertyBlock(_ecosystemPropertyBlock);
                return;
            }

            Color infectedColor = Color.Lerp(Color.white, new Color(0.45f, 1f, 0.58f, 1f), _infectionSeverity);
            Color infectedEmission = Color.Lerp(Color.black, new Color(0.08f, 0.35f, 0.12f, 1f), _infectionSeverity);
            _ecosystemPropertyBlock.SetColor(_ColorId, infectedColor);
            _ecosystemPropertyBlock.SetColor(_BaseColorId, infectedColor);
            _ecosystemPropertyBlock.SetColor(_EmissionColorId, infectedEmission);
            _renderer.SetPropertyBlock(_ecosystemPropertyBlock);
        }

        private void EnsureEcosystemPropertyBlock()
        {
            if (_ecosystemPropertyBlock != null)
                return;

            // COLD ALLOC: MaterialPropertyBlock[1] — per-fauna infection tint overlay without material clones — owner: FaunaBrain
            _ecosystemPropertyBlock = new MaterialPropertyBlock();
        }

        private void UpdateInfectionHazardRegistration()
        {
            if (!_isInfected || !isAggressive || _isDead || !isActiveAndEnabled)
            {
                ClearInfectionHazardRegistration();
                return;
            }

            if (_infectionHazardSourceId == 0)
                _infectionHazardSourceId = unchecked((int)(EntityId.ToULong(GetEntityId()) ^ 0x4E434654u));

            float aggressionScale = Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f);
            float radius = InfectionHazardRadiusBase * Mathf.Lerp(0.9f, 1.3f, _infectionSeverity) * aggressionScale;
            float intensity = InfectionHazardIntensityBase * Mathf.Lerp(0.8f, 1.45f, _infectionSeverity) * aggressionScale;
            HectonHazardManager.Register(_infectionHazardSourceId, transform.position, intensity, radius, HazardType.Toxicity);
        }

        private void ClearInfectionHazardRegistration()
        {
            if (_infectionHazardSourceId == 0)
                return;

            HectonHazardManager.Unregister(_infectionHazardSourceId);
        }

        private void UpdatePredatorThreatPulse()
        {
            if (_isDead || !isActiveAndEnabled || !isAggressive)
                return;

            if (!ShouldEmitPredatorThreatPulse(_stateMachine.currentState))
                return;

            Hecton8.World.HectonMapMagicVegetationBridge bridge = Hecton8.World.HectonMapMagicVegetationBridge.ActiveRuntimeInstance;
            if (bridge == null)
                return;

            float aggressionScale = Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f);
            float attackRadius = Mathf.Max(0f, _speciesProfile != null ? _speciesProfile.attackRadius : _stateMachine.attackRadius);
            float aggroRadius = Mathf.Max(0f, _sensorSuite.aggroDistance);
            float threatRadius = Mathf.Max(attackRadius * 2f, aggroRadius * 0.55f) + PredatorThreatPulseRadiusPadding;
            if (threatRadius <= 0f)
                return;

            float threatStrength = PredatorThreatPulseStrengthBase + (aggressionScale * 0.18f);
            if (_stateMachine.currentState == AIState.Aggressive || _stateMachine.currentState == AIState.Threaten)
                threatStrength += PredatorThreatPulseStrengthAggressiveBonus;

            if (_isInfected)
                threatStrength *= Mathf.Lerp(1f, 1.12f, _infectionSeverity);

            bridge.ApplyExternalThreatPulse(
                transform.position,
                threatRadius,
                Mathf.Clamp01(threatStrength),
                PredatorThreatPulseHoldSeconds);
        }

        private static bool ShouldEmitPredatorThreatPulse(AIState state)
        {
            switch (state)
            {
                case AIState.Investigate:
                case AIState.Threaten:
                case AIState.Stalk:
                case AIState.Loom:
                case AIState.Feint:
                case AIState.Escape:
                case AIState.Aggressive:
                case AIState.ApexForcedRetreat:
                case AIState.Retreat:
                case AIState.ThreatDisplay:
                    return true;

                default:
                    return false;
            }
        }

        private void EnsureBaseLocalScaleCaptured()
        {
            if (_baseLocalScaleCaptured)
                return;

            _baseLocalScale = transform.localScale;
            _baseLocalScaleCaptured = true;
        }
    }
}
