using Hecton8.Gameplay;
using Hecton8.Ecosystem;
using Hecton8.Meta;
using Hecton8.Core;
using Hecton8.World;
using Unity.Mathematics;
using UnityEngine;

namespace Hecton8.AI
{
    public partial class FaunaBrain
    {
        private const float InfectionHazardRadiusBase = 3f;
        private const float InfectionHazardIntensityBase = 0.9f;
        private const float PredatorThreatPulseHoldSeconds = 0.65f;
        private const float PredatorThreatPulseRadiusPadding = 4f;
        private const float PredatorThreatPulseStrengthBase = 0.28f;
        private const float PredatorThreatPulseStrengthAggressiveBonus = 0.16f;
        private const float GenomeMutationCadenceSeconds = 5f;
        private const uint FaunaGenomeMutationHashSalt = 0x4D555441u;

        private static readonly int _ColorId = Shader.PropertyToID("_Color");
        private static readonly int _BaseColorId = Shader.PropertyToID("_BaseColor");
        private static readonly int _EmissionColorId = Shader.PropertyToID("_EmissionColor");

        private static readonly Color FaunaInfectionTint = new Color(0.45f, 1f, 0.58f, 1f);
        private static readonly Color FaunaInfectionEmission = new Color(0.08f, 0.35f, 0.12f, 1f);
        private Vector3 _baseLocalScale = Vector3.one;
        private bool _baseLocalScaleCaptured;
        private float _baseAggroDistance;
        private float _baseDeaggroDistance;
        private float _baseAttackDamage;
        private float _baseCruiseSpeed;
        private float _baseBurstSpeed;
        private float _baseTurnSpeed;
        private float _baseMaxHealth = 1f;
        private float _runtimeAggressionScale = 1f;
        private FaunaGeneticTraits _baseGeneticTraits;
        private FaunaGeneticTraits _geneticTraits;
        private float _genomeMutationAccumulator;
        private uint _genomeMutationRollIndex;
        private IEcosystemDirectorService _cachedEcosystemDirectorService;
        private EcosystemDirector _cachedEcosystemDirectorConcrete;
        private bool _hasGeneticTraits;
        private bool _isInfected;
        private bool _isDiseased;
        private float _infectionSeverity;
        private float _diseaseSeverity;
        private int _infectionHazardSourceId;
        private string _lootProfileId = string.Empty;

        /// <summary>Returns true when this fauna instance currently carries the infection overlay.</summary>
        public bool IsInfected => _isInfected;
        public bool IsDiseased => _isDiseased;

        /// <summary>Returns true when the instance represents poisoned non-predator loot.</summary>
        public bool HasPoisonedYield => (_isInfected && !isAggressive) || (_hasGeneticTraits && FaunaGenome64.HasContaminatedYield(_geneticTraits.Genome));

        /// <summary>Stable contaminated meat hash exposed to death/drop systems when mutation flags are active.</summary>
        public uint ContaminatedMeatItemHash => _hasGeneticTraits && _geneticTraits.ContaminatedMeatHash != 0u
            ? _geneticTraits.ContaminatedMeatHash
            : 0u;

        /// <summary>Authoring loot-profile identifier inherited from the applied archetype.</summary>
        public string LootProfileId => _lootProfileId;

        /// <summary>
        /// Applies deterministic runtime genetic traits generated by the ecosystem genetics owner.
        /// </summary>
        public void ApplyGeneticTraits(FaunaGeneticTraits traits)
        {
            _baseGeneticTraits = traits;
            _geneticTraits = FaunaGenome64.ResolveRuntimeTraitsFromGenome(traits, traits.Genome != 0UL ? traits.Genome : traits.BaseGenome);
            _genomeMutationAccumulator = 0f;
            _genomeMutationRollIndex = 0u;
            _hasGeneticTraits = true;
            ApplyRuntimeEcosystemOverlays();
        }

        /// <summary>
        /// Clears previously applied runtime genetic traits.
        /// </summary>
        public void ClearGeneticTraits()
        {
            _baseGeneticTraits = default;
            _geneticTraits = default;
            _genomeMutationAccumulator = 0f;
            _genomeMutationRollIndex = 0u;
            _hasGeneticTraits = false;
            ApplyRuntimeEcosystemOverlays();
        }

        /// <summary>
        /// Applies or clears the infection overlay for the spawned fauna instance.
        /// </summary>
        public void SetInfectedState(bool infected, float severity)
        {
            _isInfected = infected;
            _infectionSeverity = infected ? Mathf.Clamp01(severity) : 0f;
            ApplyRuntimeEcosystemOverlays();
            UpdateInfectionHazardRegistration();
        }

        public void SetDiseasedState(bool diseased, float severity)
        {
            _isDiseased = diseased;
            _diseaseSeverity = diseased ? Mathf.Clamp01(severity) : 0f;
            ApplyRuntimeEcosystemOverlays();
        }

        private void RefreshRuntimeEcosystemState()
        {
            if (_isDead)
            {
                ClearInfectionHazardRegistration();
                return;
            }

            float ecosystemHostilityScale = 1f;
            IEcosystemDirectorService ecosystemDirector = ResolveCachedEcosystemDirectorService();
            if (ecosystemDirector != null && ecosystemDirector.IsInitialized)
                ecosystemHostilityScale = Mathf.Lerp(1f, 1.35f, ecosystemDirector.BiomeHostility01);

            float nextAggressionScale = isAggressive ? DynamicDifficultyDirector.Current.PredatorAggressionScale * ecosystemHostilityScale : 1f;
            if (Mathf.Abs(nextAggressionScale - _runtimeAggressionScale) > 0.001f)
            {
                _runtimeAggressionScale = nextAggressionScale;
                ApplyRuntimeEcosystemOverlays();
            }

            TryApplyRuntimeGenomeMutation(ecosystemDirector);
            RefreshCorpseDiseaseState();
            UpdateInfectionHazardRegistration();
            UpdatePredatorThreatPulse();
        }

        private void TryApplyRuntimeGenomeMutation(IEcosystemDirectorService ecosystemDirector)
        {
            if (!_hasGeneticTraits ||
                ecosystemDirector == null ||
                !ecosystemDirector.IsInitialized ||
                _isDead)
            {
                return;
            }

            _genomeMutationAccumulator += SlowTickIntervalSeconds;
            if (_genomeMutationAccumulator < GenomeMutationCadenceSeconds)
                return;

            _genomeMutationAccumulator = 0f;
            if (!TryResolveSelfLogicPosition(out Vector3 runtimePosition))
                return;

            _genomeMutationRollIndex++;
            if (_genomeMutationRollIndex == 0u)
                _genomeMutationRollIndex = 1u;

            FaunaGenomeMutationRequest request = new FaunaGenomeMutationRequest
            {
                RuntimePosition = runtimePosition,
                Genome = _geneticTraits.Genome,
                StableEntityHash = ResolveStableFaunaHash(FaunaGenomeMutationHashSalt, 0u),
                SpeciesId = ComputeStableSpeciesId(),
                RollIndex = _genomeMutationRollIndex,
                Slot = (ushort)(ResolveStableFaunaHash(FaunaGenomeMutationHashSalt, 1u) & ushort.MaxValue),
                Flags = FaunaGenomeMutationRequestFlags.LoadedEntity
            };

            if (!ecosystemDirector.TryMutateFaunaGenome(ref request))
                return;

            _geneticTraits = FaunaGenome64.ResolveRuntimeTraitsFromGenome(_baseGeneticTraits, request.Genome);
            ApplyRuntimeEcosystemOverlays();
        }

        private void RefreshCorpseDiseaseState()
        {
            EcosystemDirector ecosystemDirector = ResolveCachedEcosystemDirectorConcrete();
            if (ecosystemDirector == null)
            {
                if (_isDiseased)
                    SetDiseasedState(false, 0f);

                return;
            }

            if (!TryResolveSelfLogicAup(out AbsoluteUniversePosition selfAup))
            {
                if (_isDiseased)
                    SetDiseasedState(false, 0f);

                return;
            }

            if (ecosystemDirector.TryResolveCorpseDiseaseExposure(in selfAup, _cognitionTimeSeconds, out float severity01, out _))
            {
                if (!_isDiseased || Mathf.Abs(severity01 - _diseaseSeverity) > 0.01f)
                    SetDiseasedState(true, severity01);
                return;
            }

            if (_isDiseased)
                SetDiseasedState(false, 0f);
        }

        private void RefreshCachedEcosystemDirectorReference()
        {
            IEcosystemDirectorService ecosystemDirector = GlobalRegistry.EcosystemDirector;
            _cachedEcosystemDirectorService = ecosystemDirector;
            _cachedEcosystemDirectorConcrete = ecosystemDirector as EcosystemDirector;
        }

        private void ClearCachedEcosystemDirectorReference()
        {
            _cachedEcosystemDirectorService = null;
            _cachedEcosystemDirectorConcrete = null;
        }

        private IEcosystemDirectorService ResolveCachedEcosystemDirectorService()
        {
            IEcosystemDirectorService ecosystemDirector = _cachedEcosystemDirectorService;
            if (ecosystemDirector != null && ecosystemDirector.IsInitialized)
                return ecosystemDirector;

            RefreshCachedEcosystemDirectorReference();
            return _cachedEcosystemDirectorService;
        }

        private EcosystemDirector ResolveCachedEcosystemDirectorConcrete()
        {
            EcosystemDirector ecosystemDirector = _cachedEcosystemDirectorConcrete;
            if (ecosystemDirector != null && ecosystemDirector.IsInitialized)
                return ecosystemDirector;

            RefreshCachedEcosystemDirectorReference();
            return _cachedEcosystemDirectorConcrete != null && _cachedEcosystemDirectorConcrete.IsInitialized
                ? _cachedEcosystemDirectorConcrete
                : null;
        }

        private void ApplyRuntimeEcosystemOverlays()
        {
            EnsureBaseLocalScaleCaptured();

            float scaleMultiplier = _hasGeneticTraits ? _geneticTraits.ScaleMultiplier : 1f;
            float healthMultiplier = _hasGeneticTraits ? _geneticTraits.HealthMultiplier : 1f;
            float moveMultiplier = _hasGeneticTraits ? _geneticTraits.SpeedMultiplier : 1f;
            float geneticsAggressionMultiplier = _hasGeneticTraits ? _geneticTraits.AggressionMultiplier : 1f;
            float aggressionMultiplier = Mathf.Clamp(_runtimeAggressionScale * geneticsAggressionMultiplier, 0.85f, 2.25f);

            if (_isInfected)
            {
                aggressionMultiplier *= Mathf.Lerp(1f, 1.12f, _infectionSeverity);
                healthMultiplier *= Mathf.Lerp(1f, 1.18f, _infectionSeverity);
            }

            if (_isDiseased)
                moveMultiplier *= Mathf.Lerp(1f, 0.7f, _diseaseSeverity);

            transform.localScale = _baseLocalScale * scaleMultiplier;

            float previousHealthNormalized = _maxHealth > 0.001f ? _currentHealth * math.rcp(_maxHealth) : 1f;
            _maxHealth = Mathf.Max(1f, _baseMaxHealth * healthMultiplier);
            _currentHealth = _isDead ? 0f : Mathf.Clamp(_maxHealth * previousHealthNormalized, 0f, _maxHealth);
            if (!_isDead && _currentHealth <= 0.001f)
                _currentHealth = _maxHealth;

            _sensorSuite.aggroDistance = Mathf.Max(0f, _baseAggroDistance * aggressionMultiplier);
            _sensorSuite.deaggroDistance = Mathf.Max(_sensorSuite.aggroDistance, _baseDeaggroDistance * aggressionMultiplier);
            _steeringEngine.moveSpeed = Mathf.Max(0.1f, _baseCruiseSpeed * moveMultiplier);
            _steeringEngine.maxSpeed = _steeringEngine.moveSpeed;
            _steeringEngine.turnSpeed = Mathf.Max(0.1f, _baseTurnSpeed * moveMultiplier);
            _steeringEngine.swimForce = Mathf.Max(_steeringEngine.moveSpeed, _baseBurstSpeed * moveMultiplier);

            ApplyInfectionVisuals();
        }

        private float ResolveCurrentAttackDamage()
        {
            float baseDamage = _baseAttackDamage > 0.001f
                ? _baseAttackDamage
                : (_speciesProfile != null ? _speciesProfile.attackDamage : _stateMachine.attackDamage);

            return Mathf.Max(0f, baseDamage * ResolveRuntimeAttackDamageMultiplier());
        }

        private float ResolveRuntimeAttackDamageMultiplier()
        {
            float geneticsAggressionMultiplier = _hasGeneticTraits ? _geneticTraits.AggressionMultiplier : 1f;
            float runtimeAggression = _runtimeAggressionScale * geneticsAggressionMultiplier;
            float multiplier = isAggressive ? Mathf.Lerp(1f, Mathf.Clamp(runtimeAggression, 0.85f, 2.25f), 0.65f) : 1f;
            if (_isInfected)
                multiplier *= Mathf.Lerp(1f, 1.22f, _infectionSeverity);

            return Mathf.Clamp(multiplier, 0.75f, 2.1f);
        }

        private float ResolveRuntimeSpeedMultiplierForState(AIState state)
        {
            switch (state)
            {
                case AIState.Aggressive:
                case AIState.Stalk:
                case AIState.Threaten:
                case AIState.Loom:
                case AIState.Feint:
                    float geneticsAggressionMultiplier = _hasGeneticTraits ? _geneticTraits.AggressionMultiplier : 1f;
                    float runtimeAggression = _runtimeAggressionScale * geneticsAggressionMultiplier;
                    float multiplier = Mathf.Lerp(1f, Mathf.Clamp(runtimeAggression, 0.85f, 2.25f), 0.55f);
                    if (_isInfected)
                        multiplier *= Mathf.Lerp(1f, 1.08f, _infectionSeverity);

                    if (_isDiseased)
                        multiplier *= Mathf.Lerp(1f, 0.7f, _diseaseSeverity);

                    return Mathf.Clamp(multiplier, 0.8f, 1.8f);

                default:
                    return _isDiseased ? Mathf.Lerp(1f, 0.7f, _diseaseSeverity) : 1f;
            }
        }

        private void ApplyInfectionVisuals()
        {
            int runtimeMaterialCount = _faunaPresentationRuntimeMaterials.Count;
            if (runtimeMaterialCount <= 0)
                return;

            float resolvedSeverity01 = _isInfected ? math.saturate(_infectionSeverity) : 0f;
            if (_lastAppliedInfectionShaderActive == _isInfected &&
                math.abs(_lastAppliedInfectionShaderSeverity01 - resolvedSeverity01) < 0.001f)
            {
                return;
            }

            _lastAppliedInfectionShaderActive = _isInfected;
            _lastAppliedInfectionShaderSeverity01 = resolvedSeverity01;
            Color infectedColor = Color.Lerp(Color.white, FaunaInfectionTint, resolvedSeverity01);
            Color infectedEmission = Color.Lerp(Color.black, FaunaInfectionEmission, resolvedSeverity01);
            int originalMaterialCount = _faunaPresentationOriginalMaterials.Count;
            for (int i = 0; i < runtimeMaterialCount; i++)
            {
                Material runtimeMaterial = _faunaPresentationRuntimeMaterials[i];
                if (runtimeMaterial == null)
                    continue;

                Material originalMaterial = i < originalMaterialCount ? _faunaPresentationOriginalMaterials[i] : null;
                ushort propertyMask = _faunaPresentationRuntimeMaterialMasks[i];
                if ((propertyMask & FaunaPresentationColorMask) != 0)
                {
                    Color color = _isInfected ? infectedColor : ResolveOriginalMaterialColor(originalMaterial, _ColorId, Color.white);
                    runtimeMaterial.SetColor(_ColorId, color);
                }

                if ((propertyMask & FaunaPresentationBaseColorMask) != 0)
                {
                    Color color = _isInfected ? infectedColor : ResolveOriginalMaterialColor(originalMaterial, _BaseColorId, Color.white);
                    runtimeMaterial.SetColor(_BaseColorId, color);
                }

                if ((propertyMask & FaunaPresentationEmissionColorMask) != 0)
                {
                    Color color = _isInfected ? infectedEmission : ResolveOriginalMaterialColor(originalMaterial, _EmissionColorId, Color.black);
                    runtimeMaterial.SetColor(_EmissionColorId, color);
                }
            }
        }

        private static Color ResolveOriginalMaterialColor(Material originalMaterial, int shaderId, Color fallback)
        {
            return originalMaterial != null && originalMaterial.HasProperty(shaderId)
                ? originalMaterial.GetColor(shaderId)
                : fallback;
        }

        private void UpdateInfectionHazardRegistration()
        {
            if (!_isInfected || !isAggressive || _isDead || !isActiveAndEnabled)
            {
                ClearInfectionHazardRegistration();
                return;
            }

            if (_infectionHazardSourceId == 0)
                _infectionHazardSourceId = unchecked((int)(EntityId.ToULong(GetEntityId()) ^ 0x4E434654u));

            float aggressionScale = Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f);
            float radius = InfectionHazardRadiusBase * Mathf.Lerp(0.9f, 1.3f, _infectionSeverity) * aggressionScale;
            float intensity = InfectionHazardIntensityBase * Mathf.Lerp(0.8f, 1.45f, _infectionSeverity) * aggressionScale;
            HectonHazardManager.Register(_infectionHazardSourceId, transform.position, intensity, radius, HazardType.Toxicity);
        }

        private void ClearInfectionHazardRegistration()
        {
            if (_infectionHazardSourceId == 0)
                return;

            HectonHazardManager.Unregister(_infectionHazardSourceId);
        }

        private void UpdatePredatorThreatPulse()
        {
            if (_isDead || !isActiveAndEnabled || !isAggressive)
                return;

            if (!ShouldEmitPredatorThreatPulse(_stateMachine.currentState))
                return;

            Hecton8.World.HectonMapMagicVegetationBridge bridge = Hecton8.World.HectonMapMagicVegetationBridge.ActiveRuntimeInstance;
            if (bridge == null)
                return;

            float aggressionScale = Mathf.Clamp(_runtimeAggressionScale, 0.85f, 2f);
            float attackRadius = Mathf.Max(0f, _speciesProfile != null ? _speciesProfile.attackRadius : _stateMachine.attackRadius);
            float aggroRadius = Mathf.Max(0f, _sensorSuite.aggroDistance);
            float threatRadius = Mathf.Max(attackRadius * 2f, aggroRadius * 0.55f) + PredatorThreatPulseRadiusPadding;
            if (threatRadius <= 0f)
                return;

            float threatStrength = PredatorThreatPulseStrengthBase + (aggressionScale * 0.18f);
            if (_stateMachine.currentState == AIState.Aggressive || _stateMachine.currentState == AIState.Threaten)
                threatStrength += PredatorThreatPulseStrengthAggressiveBonus;

            if (_isInfected)
                threatStrength *= Mathf.Lerp(1f, 1.12f, _infectionSeverity);

            bridge.ApplyExternalThreatPulse(
                transform.position,
                threatRadius,
                Mathf.Clamp01(threatStrength),
                PredatorThreatPulseHoldSeconds);
        }

        private static bool ShouldEmitPredatorThreatPulse(AIState state)
        {
            switch (state)
            {
                case AIState.Investigate:
                case AIState.Threaten:
                case AIState.Stalk:
                case AIState.Loom:
                case AIState.Feint:
                case AIState.Escape:
                case AIState.Aggressive:
                case AIState.ApexForcedRetreat:
                case AIState.Retreat:
                case AIState.ThreatDisplay:
                    return true;

                default:
                    return false;
            }
        }

        private void EnsureBaseLocalScaleCaptured()
        {
            if (_baseLocalScaleCaptured)
                return;

            _baseLocalScale = transform.localScale;
            _baseLocalScaleCaptured = true;
        }
    }
}
