import subprocess
import sys
import os
import re
import json

# Key business logic files for Hecton-8
KEY_BUSINESS_LOGIC_FILES = [
    "PowerGridManager.cs",
    "PowerGrid.cs",
    "SubmarineOsThermalGridRuntime.cs",
    "WfcOutpostPowerBootRuntime.cs",
    "ShinobuLogisticsRouter.cs",
    "SaveManager.cs",
    "SignalBus.cs",
    "OceanRenderer.cs"
]

def run_git_cmd(args, cwd):
    try:
        res = subprocess.run(args, cwd=cwd, capture_output=True, check=True)
        return res.stdout.decode("utf-8", errors="replace").strip()
    except subprocess.CalledProcessError as e:
        stderr_str = e.stderr.decode("utf-8", errors="replace")
        print(f"Error running git command {args} in {cwd}: {stderr_str}", file=sys.stderr)
        return ""
    except Exception as e:
        print(f"Unexpected error running git command {args} in {cwd}: {e}", file=sys.stderr)
        return ""

def get_unmerged_branches(repo_dir):
    run_git_cmd(["git", "fetch", "origin"], repo_dir)
    branches_str = run_git_cmd(["git", "branch", "-r", "--no-merged", "HEAD"], repo_dir)
    if not branches_str:
        return []
    branches = []
    for line in branches_str.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("origin/") and "HEAD ->" not in line:
            branches.append(line)
    return branches

def get_diff_stats(repo_dir, branch):
    numstat = run_git_cmd(["git", "diff", "--numstat", "HEAD..." + branch], repo_dir)
    total_added = 0
    total_deleted = 0
    modified_files = []
    
    if numstat:
        for line in numstat.split("\n"):
            parts = line.split(maxsplit=2)
            if len(parts) >= 3:
                added, deleted, filepath = parts[0], parts[1], parts[2]
                if added.isdigit() and deleted.isdigit():
                    total_added += int(added)
                    total_deleted += int(deleted)
                modified_files.append(filepath)
    return total_added, total_deleted, modified_files

def get_full_diff(repo_dir, branch):
    return run_git_cmd(["git", "diff", "HEAD..." + branch], repo_dir)

def is_test_file(filepath):
    basename = os.path.basename(filepath).lower()
    ext = os.path.splitext(filepath)[1].lower()
    return (
        "test" in basename or
        "spec" in basename or
        "mock" in basename or
        filepath.startswith("tests/") or
        "/test/" in filepath or
        "/tests/" in filepath or
        basename.startswith("test_")
    )

def analyze_diff(branch, files, added_lines, deleted_lines, full_diff):
    total_changes = added_lines + deleted_lines
    
    if total_changes == 0:
        return "REJECT", "Empty branch or no diff against main."
        
    is_noise_only = True
    for f in files:
        ext = os.path.splitext(f)[1].lower()
        if ext in [".cs", ".shader", ".compute", ".py", ".md", ".json", ".sql", ".css"]:
            basename = os.path.basename(f)
            if basename in ["package-lock.json", "pnpm-lock.yaml", "yarn.lock"]:
                continue
            is_noise_only = False
            break
            
    if is_noise_only:
        return "REJECT", "Noise: Only lock files, temporary logs, or autogenerated files changed."

    lines = full_diff.split("\n")
    added_diff_lines = [l[1:] for l in lines if l.startswith("+") and not l.startswith("+++")]
    deleted_diff_lines = [l[1:] for l in lines if l.startswith("-") and not l.startswith("---")]

    # Check for memory allocations in loops
    loop_pattern = re.compile(r"\b(for|while)\b|(\.map|\.filter|\.forEach)\(")
    allocation_in_loop = False
    
    loop_context = False
    for line in added_diff_lines:
        if loop_pattern.search(line):
            loop_context = True
        if loop_context:
            if "new " in line or ".ToList(" in line or ".ToArray(" in line or "GetComponent<" in line or "GetComponent(" in line:
                allocation_in_loop = True
                break

    if allocation_in_loop:
        return "REJECT", "Performance: Memory allocation (new object, list, array, or GetComponent) inside loop in C# code."

    # Check for security issues (hardcoded keys etc)
    hardcoded_secret = False
    secret_regex = re.compile(r"password\s*=\s*['\"][^'\"]+['\"]|api_key\s*=\s*['\"][^'\"]+['\"]|secret\s*=\s*['\"][^'\"]+['\"]|token\s*=\s*['\"][^'\"]+['\"]|aes\s*=\s*['\"][^'\"]+['\"]", re.IGNORECASE)
    
    for line in added_diff_lines:
        if secret_regex.search(line):
            if "env" not in line.lower() and "process" not in line.lower() and "os." not in line.lower():
                hardcoded_secret = True

    if hardcoded_secret:
        return "REJECT", "Security: Hardcoded secrets or credentials detected."

    all_tests_or_docs = True
    for f in files:
        ext = os.path.splitext(f)[1].lower()
        basename = os.path.basename(f).lower()
        is_test = "test" in basename or "spec" in basename
        is_doc = ext in [".md", ".txt"] or "docs/" in f or "documentation" in f
        if not (is_test or is_doc):
            all_tests_or_docs = False
            break

    if all_tests_or_docs:
        return "ACCEPT", "Documentation, test additions, or documentation adjustments."

    if total_changes < 50:
        return "ACCEPT", f"Small localized modification ({total_changes} lines)."

    if added_lines < deleted_lines and total_changes < 80:
        return "ACCEPT", f"Code cleanup / dead code removal (lines added: {added_lines}, deleted: {deleted_lines})."

    # Evaluate MANUAL_REVIEW
    has_key_file = False
    for f in files:
        basename = os.path.basename(f)
        if basename in KEY_BUSINESS_LOGIC_FILES:
            has_key_file = True
            break

    if total_changes > 150 and has_key_file:
        return "MANUAL_REVIEW", f"Large diff ({total_changes} lines) in key business logic files: {', '.join([os.path.basename(x) for x in files if os.path.basename(x) in KEY_BUSINESS_LOGIC_FILES])}."

    if total_changes > 200:
        return "MANUAL_REVIEW", f"Broad changes across multiple files ({total_changes} total lines changed)."

    return "MANUAL_REVIEW", f"Requires manual review (diff of {total_changes} lines)."

def main():
    if len(sys.argv) < 2:
        print("Usage: python audit_prs.py <repo_directory>")
        sys.exit(1)
        
    repo_dir = os.path.abspath(sys.argv[1])
    results = {}
    branches = get_unmerged_branches(repo_dir)
    print(f"Found {len(branches)} unmerged remote branches.")
    
    for branch in branches:
        added, deleted, files = get_diff_stats(repo_dir, branch)
        full_diff = get_full_diff(repo_dir, branch)
        verdict, reason = analyze_diff(branch, files, added, deleted, full_diff)
        
        results[branch] = {
            "verdict": verdict,
            "reason": reason,
            "added_lines": added,
            "deleted_lines": deleted,
            "files_modified": files
        }
        print(f"Branch: {branch} -> Verdict: {verdict} ({reason})")

    report_path = os.path.join(repo_dir, "pr_audit_report.json")
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    print(f"Report written to {report_path}")

if __name__ == "__main__":
    main()
