using UnityEngine;

namespace Hecton8.Core.Contracts
{
    public interface IPlayerMovementPoseReadModel
    {
        Vector2 CurrentLocalWaveSlope { get; }

        bool TryGetRuntimePosition(out Vector3 position);
    }

    public interface IPlayerMovementForceSink
    {
        void QueueExternalAcceleration(Vector3 acceleration);

        void QueueExternalVelocityChange(Vector3 velocityChange);
    }

    public interface IPlayerMovementTraumaSink
    {
        void ApplyPhysicalTrauma(Vector3 impulse, float weight);

        void ForceTransportBailout(Vector3 worldImpulse, float severity);
    }

    public interface IPlayerMovementEnvironmentSink
    {
        void ApplyExternalThermalUpdraft(Vector3 velocityChange);

        void RequestExternalHullStress(float normalizedStress);

        void RequestLocalGravityOverride(Vector3 gravityVector, float holdSeconds);
    }

    public interface IPlayerMovementSonarEmitter
    {
        bool TriggerActiveSonarPing();
    }

    /// <summary>
    /// Narrow movement surface used by the player kinematics bridge without a concrete movement dependency.
    /// </summary>
    public interface IPlayerKinematicsMovementRuntime
    {
        /// <summary>Current water immersion ratio clamped by the movement owner.</summary>
        float WaterImmersionRatio { get; }

        /// <summary>True when the movement owner currently treats the player as submerged.</summary>
        bool IsPlayerSubmerged { get; }

        /// <summary>Byte-coded locomotion mode; the enum stays in the gameplay owner assembly.</summary>
        byte CurrentLocomotionModeCode { get; }

        /// <summary>True when the movement owner can provide kinematic authority.</summary>
        bool IsKinematicMovementActive { get; }

        /// <summary>Requests a visual inertia roll generated by kinematic collision response.</summary>
        void RequestKinematicInertiaRoll(float signedRollDegrees);
    }

    /// <summary>
    /// Narrow motor surface used by the player kinematics bridge without a concrete motor dependency.
    /// </summary>
    public interface IPlayerKinematicsMotorSyncSink
    {
        /// <summary>Returns the most recent ladder contact point inside the requested fixed-frame age.</summary>
        bool TryGetRecentLadderContact(int maxPhysicsFrameAge, out Vector3 point);

        /// <summary>Returns the most recent wall-slide contact inside the requested fixed-frame age.</summary>
        bool TryGetRecentWallSlideContact(
            int maxPhysicsFrameAge,
            out Vector3 normal,
            out Vector3 point,
            out float blockedSpeed,
            out float slideAngleDegrees,
            out float velocityReduction01,
            out int physicsFrame);

        /// <summary>Applies a synchronized kinematic position to the authoritative motor.</summary>
        void MovePosition(Vector3 position);

        /// <summary>Applies a synchronized velocity to the authoritative motor.</summary>
        void SetLinearVelocity(Vector3 velocity);

        /// <summary>Applies a synchronized rotation to the authoritative motor.</summary>
        void MoveRotation(Quaternion rotation);
    }

    public interface IPlayerMovementContracts :
        IPlayerMovementPoseReadModel,
        IPlayerMovementForceSink,
        IPlayerMovementTraumaSink,
        IPlayerMovementEnvironmentSink,
        IPlayerMovementSonarEmitter
    {
    }
}
