
#include "Include/PlatformDefines.hlsl"

#pragma kernel CSArgsBufferDoubleInstanceCount

uniform RWStructuredBuffer<uint> argsBuffer;
uniform uint count;
uniform uint argsBufferLength;

[numthreads(GPUI_THREADS, 1, 1)]
void CSArgsBufferDoubleInstanceCount(uint2 id : SV_DispatchThreadID)
{
    if (id.x >= count)
        return;

    uint argsIndex = id.x * 5 + 1;
    if (argsIndex >= argsBufferLength)
        return;

    argsBuffer[argsIndex] *= 2;
}
