
#include "Include/PlatformDefines.hlsl"

#pragma kernel CSInstancedComputeBufferSetDataPartialKernel
#pragma kernel CSInstancedComputeBufferSetDataSingleKernel

RWStructuredBuffer<float4x4> gpuiInstanceData;
RWStructuredBuffer<float4x4> gpuiManagedData;

uniform float4x4 dataToSet;
uniform uint computeBufferStartIndex;
uniform uint computeBufferCapacity;
uniform uint managedBufferCapacity;
uniform uint count;

[numthreads(GPUI_THREADS, 1, 1)]
void CSInstancedComputeBufferSetDataPartialKernel(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= count || id.x >= managedBufferCapacity)
        return;

    uint destinationIndex = computeBufferStartIndex + id.x;
    if (destinationIndex < computeBufferStartIndex || destinationIndex >= computeBufferCapacity)
        return;

    gpuiInstanceData[destinationIndex] = gpuiManagedData[id.x];
}

[numthreads(1, 1, 1)]
void CSInstancedComputeBufferSetDataSingleKernel(uint3 id : SV_DispatchThreadID)
{
    if (computeBufferStartIndex >= computeBufferCapacity)
        return;

    gpuiInstanceData[computeBufferStartIndex] = dataToSet;
}
