import json
from pathlib import Path

PATH = Path("Docs/Lore/AppliedContent/packets/RS079_REPLAY_CONTRACT_SEED_FAMILIES.packets.json")
PACKET_ID = "P395_RECOVERY_COMPLIANCE_BAIT_CONTRACT_SEED"
SOURCE_STATUS = "source_authority"
DRAFT_STATUS = "draft_machine_or_llm"

localized = {
    "en_US": {
        "localization_status": SOURCE_STATUS,
        "title": "Recovery Compliance Bait Contract Seed",
        "scanner": "Contract seed: Recovery Compliance bait. High payout, contaminated receiver chain, concealed coordinate demand.",
        "terminal": "SEED BAIT: payout raised, Recovery Compliance receiver masked, coordinate disclosure clause hidden, withholding pressure active, Deep Reach routing likely.",
        "audio": "A rescue stamp can buy a dockhand's trust faster than a gun.",
        "in_game_wiki": "Recovery Compliance bait contracts arrive as generous salvage recovery work, but the receiver chain is already bent toward Deep Reach. The payout is real. The cost is the hidden requirement to disclose where the wreck, corpse tag, sample crate or sealed machine was found.",
        "external_site": "Recovery Compliance bait turns a lucrative rescue docket into an ownership trap: every recovered part begins to carry a return address.",
        "field_note": "Marauder note: if the job pays too clean, check who owns the towel.",
        "external_site_article": "Recovery Compliance bait is one of the dirtiest clean contracts on the board. The docket wears a public-service face: recover flooded medical lockers, retrieve dead-suit identifiers, remove dangerous machine cores, return sealed cargo before decay or pressure damage ruins the record. The listed payout is high enough to look merciful in a hard week.\n\nThe trap sits in the receiver chain. A Recovery Compliance stamp can be routed through neutral salvage offices, colony insurers or disaster-cleanup desks, but the final reader often belongs to Deep Reach or to a proxy that sells them priority access. The operator is paid for material recovery and quietly bound to provide coordinate proof, hatch-state evidence and custody notes. Refusing the handoff does not void the risk. It marks the route as withholding-sensitive and makes future safe receivers less patient.\n\nThese contracts work because desperation makes good paperwork look like shelter. A crew short on filters, battery plates or pressure tape sees a clean payout and accepts the docket before reading the coordinate clause. By the time the first sealed crate is aboard, the board has learned where the crew can still reach and what the abandoned zone has not finished burying.",
    },
    "ar_SA": {
        "localization_status": DRAFT_STATUS,
        "title": "بذرة عقد طُعم امتثال الاسترداد",
        "scanner": "بذرة عقد: طُعم امتثال الاسترداد. أجر مرتفع، سلسلة مستلم ملوثة، ومطلب إحداثيات مخفي.",
        "terminal": "بذرة طُعم: رفع الأجر، إخفاء مستلم امتثال الاسترداد، بند كشف الإحداثيات مستتر، ضغط حجب نشط، واحتمال توجيه عبر Deep Reach.",
        "audio": "ختم الإنقاذ قد يشتري ثقة عامل الرصيف أسرع من السلاح.",
        "in_game_wiki": "تصل عقود طُعم امتثال الاسترداد كأعمال انتشال سخية، لكن سلسلة المستلم تكون مائلة مسبقا نحو Deep Reach. الأجر حقيقي. الكلفة هي الشرط المخفي: كشف مكان العثور على الحطام أو بطاقة الجثة أو صندوق العينة أو الآلة المختومة.",
        "external_site": "يحول طُعم امتثال الاسترداد ملف إنقاذ مربحا إلى فخ ملكية: كل قطعة مستعادة تبدأ بحمل عنوان عودة.",
        "field_note": "ملاحظة مارودر: إذا كان العمل يدفع بنظافة زائدة، فتفقد من يملك المنشفة.",
        "external_site_article": "طُعم امتثال الاسترداد من أقذر العقود النظيفة على اللوحة. يظهر الملف بوجه خدمة عامة: استرداد خزائن طبية غمرتها المياه، جلب معرفات بدلات الموتى، إزالة نوى آلات خطرة، وإرجاع شحنات مختومة قبل أن يفسدها التحلل أو ضغط العمق. الأجر المعلن مرتفع بما يكفي ليبدو رحمة في أسبوع قاس.\n\nالفخ موجود في سلسلة المستلم. يمكن تمرير ختم امتثال الاسترداد عبر مكاتب إنقاذ محايدة أو شركات تأمين مستعمرات أو مكاتب تنظيف كوارث، لكن القارئ الأخير غالبا يتبع Deep Reach أو وكيلا يبيع لها أولوية الوصول. يتقاضى المشغل أجر الاسترداد، ثم يربط بهدوء بإثبات الإحداثيات، وسجل حالة الفتحة، وملاحظات الحيازة. رفض التسليم لا يمحو الخطر. إنه يعلّم الطريق كمسار حساس للحجب ويجعل المستلمين الآمنين لاحقا أقل صبرا.\n\nتنجح هذه العقود لأن اليأس يجعل الورق الجيد يبدو مأوى. طاقم ناقص المرشحات أو صفائح البطارية أو شريط الضغط يرى أجرا نظيفا ويقبل الملف قبل قراءة بند الإحداثيات. وعندما يدخل أول صندوق مختوم إلى المركبة، تكون اللوحة قد تعلمت أين ما زال الطاقم قادرا على الوصول، وما الذي لم تنجح المنطقة المهجورة في دفنه بعد.",
    },
    "de_DE": {
        "localization_status": DRAFT_STATUS,
        "title": "Vertragskeim: Bergungs-Compliance-Köder",
        "scanner": "Vertragskeim: Bergungs-Compliance-Köder. Hohe Auszahlung, kontaminierte Empfängerkette, verdeckte Koordinatenforderung.",
        "terminal": "KÖDERKEIM: Auszahlung erhöht, Recovery-Compliance-Empfänger maskiert, Koordinatenoffenlegung verborgen, Zurückhaltungsdruck aktiv, Deep-Reach-Route wahrscheinlich.",
        "audio": "Ein Rettungsstempel kauft das Vertrauen am Dock schneller als eine Waffe.",
        "in_game_wiki": "Recovery-Compliance-Köder erscheinen als großzügige Bergungsaufträge, doch die Empfängerkette ist bereits in Richtung Deep Reach gebogen. Die Auszahlung ist echt. Der Preis ist die versteckte Pflicht, offenzulegen, wo Wrack, Leichenmarke, Probenkiste oder versiegelte Maschine gefunden wurden.",
        "external_site": "Ein Recovery-Compliance-Köder macht aus einem lukrativen Rettungsauftrag eine Besitzfalle: Jedes geborgene Teil trägt plötzlich eine Rücksendeadresse.",
        "field_note": "Marauder-Notiz: Wenn der Auftrag zu sauber zahlt, prüf, wem das Handtuch gehört.",
        "external_site_article": "Recovery-Compliance-Köder gehören zu den schmutzigsten sauberen Aufträgen auf dem Brett. Die Akte trägt das Gesicht eines öffentlichen Dienstes: überflutete Medizinschränke bergen, Tote-Anzug-Kennungen zurückholen, gefährliche Maschinenkerne entfernen, versiegelte Fracht zurückbringen, bevor Verfall oder Druckschäden den Datensatz ruinieren. Die angegebene Auszahlung ist hoch genug, um in einer harten Woche wie Gnade auszusehen.\n\nDie Falle liegt in der Empfängerkette. Ein Recovery-Compliance-Stempel kann über neutrale Bergungsbüros, Kolonieversicherer oder Katastrophenräumstellen laufen, doch der letzte Leser gehört oft Deep Reach oder einem Stellvertreter, der Prioritätszugang verkauft. Der Operator wird für Materialbergung bezahlt und zugleich still an Koordinatennachweis, Lukenzustandsbelege und Verwahrnotizen gebunden. Eine verweigerte Übergabe beseitigt das Risiko nicht. Sie markiert die Route als zurückhaltungssensibel und macht spätere sichere Empfänger ungeduldiger.\n\nDiese Verträge funktionieren, weil Verzweiflung gute Formulare wie Schutz aussehen lässt. Eine Crew mit zu wenigen Filtern, Batterieplatten oder Druckbändern sieht eine saubere Auszahlung und nimmt die Akte an, bevor sie die Koordinatenklausel liest. Sobald die erste versiegelte Kiste an Bord ist, weiß das Brett, wohin die Crew noch reicht und was die verlassene Zone noch nicht begraben konnte.",
    },
    "es_ES": {
        "localization_status": DRAFT_STATUS,
        "title": "Semilla de contrato cebo de Cumplimiento de Recuperación",
        "scanner": "Semilla de contrato: cebo de Cumplimiento de Recuperación. Pago alto, cadena de receptor contaminada, demanda de coordenadas oculta.",
        "terminal": "SEMILLA CEBO: pago elevado, receptor de Cumplimiento de Recuperación enmascarado, cláusula de coordenadas oculta, presión por retención activa, ruta Deep Reach probable.",
        "audio": "Un sello de rescate compra la confianza del muelle más rápido que un arma.",
        "in_game_wiki": "Los contratos cebo de Cumplimiento de Recuperación llegan como trabajos de rescate generosos, pero la cadena de receptor ya está inclinada hacia Deep Reach. El pago es real. El coste es la obligación oculta de revelar dónde se encontró el pecio, la placa de cadáver, la caja de muestras o la máquina sellada.",
        "external_site": "El cebo de Cumplimiento de Recuperación convierte un expediente lucrativo en una trampa de propiedad: cada pieza recuperada empieza a llevar dirección de retorno.",
        "field_note": "Nota de merodeador: si el trabajo paga demasiado limpio, mira quién es dueño de la toalla.",
        "external_site_article": "El cebo de Cumplimiento de Recuperación es uno de los contratos limpios más sucios del tablón. El expediente lleva cara de servicio público: recuperar botiquines inundados, traer identificadores de trajes muertos, retirar núcleos de maquinaria peligrosa, devolver carga sellada antes de que la descomposición o la presión arruinen el registro. El pago anunciado es lo bastante alto para parecer compasión en una semana mala.\n\nLa trampa está en la cadena de receptor. Un sello de Cumplimiento de Recuperación puede pasar por oficinas neutrales de salvamento, aseguradoras coloniales o mesas de limpieza de desastres, pero el lector final suele pertenecer a Deep Reach o a un intermediario que le vende acceso prioritario. El operador cobra por recuperar material y queda atado en silencio a pruebas de coordenadas, tiras de estado de escotilla y notas de custodia. Negarse a entregar no elimina el riesgo. Marca la ruta como sensible a retención y vuelve menos pacientes a los receptores seguros posteriores.\n\nEstos contratos funcionan porque la desesperación hace que el buen papeleo parezca refugio. Una tripulación corta de filtros, placas de batería o cinta de presión ve un pago limpio y acepta el expediente antes de leer la cláusula de coordenadas. Para cuando la primera caja sellada entra a bordo, el tablón ya ha aprendido hasta dónde puede llegar la tripulación y qué no ha terminado de enterrar la zona abandonada.",
    },
    "fr_FR": {
        "localization_status": DRAFT_STATUS,
        "title": "Graine de contrat appât de conformité de récupération",
        "scanner": "Graine de contrat : appât de conformité de récupération. Forte prime, chaîne de réception contaminée, exigence de coordonnées dissimulée.",
        "terminal": "GRAINE APPÂT : prime augmentée, récepteur de conformité masqué, clause de coordonnées cachée, pression de rétention active, routage Deep Reach probable.",
        "audio": "Un tampon de secours achète la confiance du quai plus vite qu'une arme.",
        "in_game_wiki": "Les contrats appâts de conformité de récupération se présentent comme des missions de sauvetage généreuses, mais la chaîne de réception penche déjà vers Deep Reach. La prime est réelle. Le coût, c'est l'obligation cachée de révéler l'endroit où l'épave, l'étiquette de cadavre, la caisse d'échantillons ou la machine scellée ont été trouvées.",
        "external_site": "L'appât de conformité de récupération transforme un dossier de secours lucratif en piège de propriété : chaque pièce récupérée commence à porter une adresse de retour.",
        "field_note": "Note de maraudeur : si le boulot paie trop proprement, vérifie à qui appartient la serviette.",
        "external_site_article": "L'appât de conformité de récupération fait partie des contrats propres les plus sales du tableau. Le dossier affiche un visage de service public : récupérer des armoires médicales noyées, rapporter des identifiants de combinaisons mortes, retirer des noyaux de machines dangereuses, rendre une cargaison scellée avant que la décomposition ou la pression ne ruinent le registre. La prime affichée est assez haute pour passer pour de la clémence dans une mauvaise semaine.\n\nLe piège se trouve dans la chaîne de réception. Un tampon de conformité de récupération peut transiter par des bureaux de sauvetage neutres, des assureurs coloniaux ou des cellules de nettoyage après sinistre, mais le dernier lecteur appartient souvent à Deep Reach ou à un mandataire qui lui vend un accès prioritaire. L'opérateur est payé pour la récupération matérielle et lié en silence à des preuves de coordonnées, des bandes d'état de sas et des notes de garde. Refuser la remise n'annule pas le risque. Cela marque la route comme sensible à la rétention et rend les récepteurs sûrs ultérieurs moins patients.\n\nCes contrats fonctionnent parce que le désespoir donne aux bons formulaires l'apparence d'un abri. Un équipage à court de filtres, de plaques de batterie ou de ruban de pression voit une prime nette et accepte le dossier avant de lire la clause de coordonnées. Quand la première caisse scellée monte à bord, le tableau sait déjà jusqu'où l'équipage peut encore aller et ce que la zone abandonnée n'a pas fini d'enterrer.",
    },
    "he_IL": {
        "localization_status": DRAFT_STATUS,
        "title": "זרע חוזה פיתיון תאימות שחזור",
        "scanner": "זרע חוזה: פיתיון תאימות שחזור. תשלום גבוה, שרשרת מקבל מזוהמת, דרישת קואורדינטות מוסתרת.",
        "terminal": "זרע פיתיון: תשלום הוגדל, מקבל תאימות שחזור מוסווה, סעיף גילוי קואורדינטות מוסתר, לחץ אי-מסירה פעיל, ניתוב Deep Reach סביר.",
        "audio": "חותמת חילוץ קונה אמון ברציף מהר יותר מנשק.",
        "in_game_wiki": "חוזי פיתיון תאימות שחזור מגיעים כעבודות חילוץ נדיבות, אבל שרשרת המקבל כבר מוטה לעבר Deep Reach. התשלום אמיתי. המחיר הוא הדרישה המוסתרת לחשוף היכן נמצאו השבר, תג הגופה, תיבת הדגימות או המכונה האטומה.",
        "external_site": "פיתיון תאימות שחזור הופך תיק חילוץ משתלם למלכודת בעלות: כל חלק שהוחזר מתחיל לשאת כתובת חזרה.",
        "field_note": "הערת מארודר: אם העבודה משלמת נקי מדי, בדוק למי שייכת המגבת.",
        "external_site_article": "פיתיון תאימות שחזור הוא אחד החוזים הנקיים המלוכלכים ביותר על הלוח. התיק עוטה פנים של שירות ציבורי: חילוץ ארוניות רפואיות מוצפות, החזרת מזהי חליפות מתות, פינוי ליבות מכונה מסוכנות, והחזרת מטען אטום לפני שריקבון או נזקי לחץ יהרסו את הרשומה. התשלום הרשום גבוה מספיק כדי להיראות כמו רחמים בשבוע קשה.\n\nהמלכודת נמצאת בשרשרת המקבל. חותמת תאימות שחזור יכולה לעבור דרך משרדי חילוץ ניטרליים, מבטחי מושבות או שולחנות ניקוי אסונות, אבל הקורא האחרון שייך לעיתים קרובות ל-Deep Reach או לשליח שמוכר לה גישה מועדפת. המפעיל מקבל תשלום על שחזור חומרי ונקשר בשקט להוכחת קואורדינטות, לרצועות מצב פתח ולרשומות משמורת. סירוב למסירה אינו מבטל את הסיכון. הוא מסמן את המסלול כרגיש לאי-מסירה והופך מקבלים בטוחים בעתיד לפחות סבלניים.\n\nהחוזים האלה עובדים כי ייאוש גורם לניירת טובה להיראות כמו מחסה. צוות שחסרים לו מסננים, לוחות סוללה או סרט לחץ רואה תשלום נקי ומקבל את התיק לפני קריאת סעיף הקואורדינטות. עד שהתיבה האטומה הראשונה כבר על הסיפון, הלוח למד לאן הצוות עדיין מסוגל להגיע ומה האזור הנטוש עוד לא הצליח לקבור.",
    },
    "id_ID": {
        "localization_status": DRAFT_STATUS,
        "title": "Benih Kontrak Umpan Kepatuhan Pemulihan",
        "scanner": "Benih kontrak: umpan Kepatuhan Pemulihan. Bayaran tinggi, rantai penerima tercemar, tuntutan koordinat tersembunyi.",
        "terminal": "BENIH UMPAN: bayaran dinaikkan, penerima Kepatuhan Pemulihan disamarkan, klausul pembukaan koordinat disembunyikan, tekanan penahanan aktif, rute Deep Reach mungkin.",
        "audio": "Stempel penyelamatan bisa membeli kepercayaan dermaga lebih cepat daripada senjata.",
        "in_game_wiki": "Kontrak umpan Kepatuhan Pemulihan datang sebagai pekerjaan salvage yang murah hati, tetapi rantai penerimanya sudah condong ke Deep Reach. Bayarannya nyata. Biayanya adalah kewajiban tersembunyi untuk mengungkap tempat bangkai, tag jenazah, peti sampel, atau mesin tersegel ditemukan.",
        "external_site": "Umpan Kepatuhan Pemulihan mengubah docket penyelamatan yang menguntungkan menjadi perangkap kepemilikan: setiap bagian yang dipulihkan mulai membawa alamat balik.",
        "field_note": "Catatan marauder: kalau pekerjaannya membayar terlalu bersih, periksa siapa pemilik handuknya.",
        "external_site_article": "Umpan Kepatuhan Pemulihan adalah salah satu kontrak bersih paling kotor di papan. Docket-nya memakai wajah layanan publik: mengambil loker medis yang kebanjiran, memulangkan pengenal suit jenazah, menyingkirkan inti mesin berbahaya, mengembalikan kargo tersegel sebelum pembusukan atau kerusakan tekanan merusak catatan. Bayaran yang tercantum cukup tinggi untuk terlihat seperti belas kasihan pada minggu yang buruk.\n\nPerangkapnya berada di rantai penerima. Stempel Kepatuhan Pemulihan dapat dirutekan melalui kantor salvage netral, asuransi koloni, atau meja pembersihan bencana, tetapi pembaca terakhir sering kali milik Deep Reach atau proksi yang menjual akses prioritas kepadanya. Operator dibayar untuk pemulihan material dan diam-diam diikat pada bukti koordinat, strip status palka, dan catatan kustodi. Menolak serah terima tidak menghapus risiko. Itu menandai rute sebagai sensitif terhadap penahanan dan membuat penerima aman berikutnya kurang sabar.\n\nKontrak ini berhasil karena keputusasaan membuat dokumen rapi terlihat seperti tempat berlindung. Kru yang kekurangan filter, pelat baterai, atau pita tekanan melihat bayaran bersih dan menerima docket sebelum membaca klausul koordinat. Saat peti tersegel pertama sudah naik, papan sudah belajar sejauh mana kru masih bisa menjangkau dan apa yang belum berhasil dikubur oleh zona terbengkalai.",
    },
    "ja_JP": {
        "localization_status": DRAFT_STATUS,
        "title": "回収コンプライアンス餌契約シード",
        "scanner": "契約シード: 回収コンプライアンス餌。高額報酬、汚染された受領者チェーン、隠された座標要求。",
        "terminal": "餌シード: 報酬引き上げ、回収コンプライアンス受領者を偽装、座標開示条項を秘匿、差し止め圧力有効、Deep Reach 経路の可能性大。",
        "audio": "救助の印章は、銃より早く桟橋の信用を買える。",
        "in_game_wiki": "回収コンプライアンス餌契約は、気前のよいサルベージ回収として届く。しかし受領者チェーンは最初から Deep Reach 側へ曲げられている。報酬は本物だ。代償は、残骸、遺体タグ、試料箱、密封機械をどこで見つけたか開示する隠し義務である。",
        "external_site": "回収コンプライアンス餌は、儲かる救助案件を所有権の罠へ変える。回収品の一つ一つに返送先が付く。",
        "field_note": "マローダー記録: 支払いがきれいすぎる仕事なら、そのタオルの持ち主を調べろ。",
        "external_site_article": "回収コンプライアンス餌は、掲示板で最も汚れた清潔な契約の一つだ。案件は公共奉仕の顔をしている。浸水した医療ロッカーを回収し、死亡スーツの識別子を取り戻し、危険な機械コアを除去し、腐敗や圧力損傷で記録が崩れる前に密封貨物を返す。表示報酬は、苦しい週には慈悲に見えるほど高い。\n\n罠は受領者チェーンにある。回収コンプライアンスの印章は、中立サルベージ事務所、植民地保険会社、災害清掃デスクを経由できる。しかし最後の読み手は Deep Reach か、同社へ優先アクセスを売る代理であることが多い。オペレーターは物資回収の報酬を受け取り、同時に座標証明、ハッチ状態記録、保管メモへ静かに縛られる。引き渡し拒否で危険は消えない。経路は差し止め警戒対象として記録され、後の安全な受領者は忍耐を失いやすくなる。\n\nこの契約が機能するのは、追い詰められた時ほど整った書類が避難所に見えるからだ。フィルター、バッテリープレート、圧力テープが足りないクルーは、きれいな報酬を見て座標条項を読む前に案件を受ける。最初の密封箱が船内に入った時点で、掲示板はそのクルーがまだ届く場所と、放棄区域がまだ埋めきれていないものを知っている。",
    },
    "ko_KR": {
        "localization_status": DRAFT_STATUS,
        "title": "회수 준수 미끼 계약 시드",
        "scanner": "계약 시드: 회수 준수 미끼. 높은 보수, 오염된 수령자 사슬, 숨겨진 좌표 요구.",
        "terminal": "미끼 시드: 보수 상승, 회수 준수 수령자 은폐, 좌표 공개 조항 은닉, 보류 압박 활성, Deep Reach 경로 가능성 높음.",
        "audio": "구조 도장은 총보다 빠르게 부두의 신뢰를 산다.",
        "in_game_wiki": "회수 준수 미끼 계약은 후한 인양 작업처럼 들어오지만, 수령자 사슬은 이미 Deep Reach 쪽으로 휘어 있다. 보수는 진짜다. 대가는 잔해, 사망자 태그, 표본 상자, 밀봉 기계가 발견된 위치를 밝히라는 숨겨진 의무다.",
        "external_site": "회수 준수 미끼는 수익성 좋은 구조 문서를 소유권 함정으로 바꾼다. 회수된 모든 부품에 반송 주소가 붙기 시작한다.",
        "field_note": "마로더 메모: 일이 너무 깨끗하게 돈을 주면, 그 수건의 주인이 누구인지 확인하라.",
        "external_site_article": "회수 준수 미끼는 게시판에서 가장 더러운 깨끗한 계약 중 하나다. 문서는 공공 서비스의 얼굴을 쓴다. 침수된 의료 보관함을 회수하고, 죽은 슈트의 식별자를 가져오고, 위험한 기계 코어를 제거하고, 부패나 압력 손상이 기록을 망치기 전에 밀봉 화물을 반환하라고 한다. 표시된 보수는 힘든 주간에는 자비처럼 보일 만큼 높다.\n\n함정은 수령자 사슬에 있다. 회수 준수 도장은 중립 인양 사무소, 식민지 보험사, 재난 정리 창구를 거쳐 갈 수 있지만, 마지막 판독자는 종종 Deep Reach이거나 그들에게 우선 접근권을 파는 대리인이다. 운영자는 물질 회수 대가를 받고, 동시에 좌표 증명, 해치 상태 스트립, 보관 기록에 조용히 묶인다. 인계를 거부해도 위험은 사라지지 않는다. 그 경로는 보류 민감 경로로 표시되고, 이후의 안전한 수령자는 더 참을성이 없어진다.\n\n이 계약이 통하는 이유는 절박함이 좋은 서류를 피난처처럼 보이게 만들기 때문이다. 필터, 배터리 판, 압력 테이프가 부족한 승무원은 깨끗한 보수를 보고 좌표 조항을 읽기 전에 문서를 받아들인다. 첫 밀봉 상자가 선내에 오를 때쯤, 게시판은 그 승무원이 아직 닿을 수 있는 곳과 버려진 구역이 아직 묻지 못한 것을 이미 배운다.",
    },
    "nl_NL": {
        "localization_status": DRAFT_STATUS,
        "title": "Contractzaad: herstelcompliance-lokker",
        "scanner": "Contractzaad: herstelcompliance-lokker. Hoge uitbetaling, besmette ontvangersketen, verborgen coördinateneis.",
        "terminal": "LOKZAAD: uitbetaling verhoogd, Recovery Compliance-ontvanger gemaskeerd, coördinatenclausule verborgen, inhoudingsdruk actief, Deep Reach-routering waarschijnlijk.",
        "audio": "Een reddingsstempel koopt dokvertrouwen sneller dan een wapen.",
        "in_game_wiki": "Recovery Compliance-lokcontracten komen binnen als royaal bergingswerk, maar de ontvangersketen is al naar Deep Reach toe gebogen. De uitbetaling is echt. De prijs is de verborgen plicht om te melden waar het wrak, het lijklabel, de monsterkist of de verzegelde machine is gevonden.",
        "external_site": "Een Recovery Compliance-lokker verandert een lucratief reddingsdossier in een eigendomsval: elk geborgen onderdeel krijgt ineens een retouradres.",
        "field_note": "Marauder-notitie: als de klus te schoon betaalt, kijk dan van wie de handdoek is.",
        "external_site_article": "Recovery Compliance-lokkers behoren tot de vuilste schone contracten op het bord. Het dossier draagt een publiek-dienstverlenend gezicht: overstroomde medische lockers bergen, identificaties van dode pakken ophalen, gevaarlijke machinekernen verwijderen, verzegelde vracht terugbrengen voordat verval of drukschade het dossier ruïneert. De genoemde uitbetaling is hoog genoeg om in een slechte week barmhartig te lijken.\n\nDe val zit in de ontvangersketen. Een Recovery Compliance-stempel kan via neutrale bergingskantoren, koloniale verzekeraars of rampenruimingsbalies lopen, maar de laatste lezer hoort vaak bij Deep Reach of bij een tussenpartij die prioriteitstoegang verkoopt. De operator wordt betaald voor materiaalherstel en stil vastgezet aan coördinatenbewijs, luikstatusstroken en bewaarnotities. Een overdracht weigeren haalt het risico niet weg. Het markeert de route als inhoudingsgevoelig en maakt latere veilige ontvangers minder geduldig.\n\nDeze contracten werken omdat wanhoop goed papierwerk op onderdak laat lijken. Een crew met te weinig filters, batterijplaten of druktape ziet een schone uitbetaling en accepteert het dossier voordat de coördinatenclausule is gelezen. Tegen de tijd dat de eerste verzegelde kist aan boord is, weet het bord waar de crew nog kan komen en wat de verlaten zone nog niet heeft kunnen begraven.",
    },
    "pl_PL": {
        "localization_status": DRAFT_STATUS,
        "title": "Ziarno kontraktu-przynęty zgodności odzysku",
        "scanner": "Ziarno kontraktu: przynęta zgodności odzysku. Wysoka wypłata, skażony łańcuch odbiorcy, ukryte żądanie współrzędnych.",
        "terminal": "ZIARNO PRZYNĘTY: wypłata podniesiona, odbiorca Recovery Compliance zamaskowany, klauzula ujawnienia współrzędnych ukryta, presja wstrzymania aktywna, trasa Deep Reach prawdopodobna.",
        "audio": "Stempel ratunkowy kupuje zaufanie doku szybciej niż broń.",
        "in_game_wiki": "Kontrakty-przynęty zgodności odzysku wyglądają jak hojne zlecenia ratunkowe, ale łańcuch odbiorcy jest już wygięty ku Deep Reach. Wypłata jest prawdziwa. Kosztem jest ukryty obowiązek ujawnienia miejsca znalezienia wraku, znacznika zwłok, skrzyni próbek albo zaplombowanej maszyny.",
        "external_site": "Przynęta zgodności odzysku zmienia zyskowne zlecenie ratunkowe w pułapkę własności: każdy odzyskany element zaczyna nosić adres zwrotny.",
        "field_note": "Notatka marudera: jeśli robota płaci zbyt czysto, sprawdź, do kogo należy ręcznik.",
        "external_site_article": "Przynęta zgodności odzysku to jeden z najbrudniejszych czystych kontraktów na tablicy. Akta noszą twarz usługi publicznej: odzyskać zalane szafki medyczne, przynieść identyfikatory martwych skafandrów, usunąć niebezpieczne rdzenie maszyn, zwrócić zaplombowany ładunek, zanim rozkład lub uszkodzenia ciśnieniowe zniszczą zapis. Wypłata na liście jest dość wysoka, by w ciężkim tygodniu wyglądać jak miłosierdzie.\n\nPułapka siedzi w łańcuchu odbiorcy. Stempel zgodności odzysku może przejść przez neutralne biura salvage, kolonialnych ubezpieczycieli albo punkty sprzątania katastrof, lecz ostatni czytnik często należy do Deep Reach albo do pośrednika sprzedającego im priorytetowy dostęp. Operator otrzymuje zapłatę za odzysk materiału i po cichu zostaje związany dowodem współrzędnych, paskami stanu włazu oraz notami przechowania. Odmowa przekazania nie usuwa ryzyka. Oznacza trasę jako wrażliwą na wstrzymanie i sprawia, że późniejsi bezpieczni odbiorcy mają mniej cierpliwości.\n\nTe kontrakty działają, bo desperacja sprawia, że dobre formularze wyglądają jak schronienie. Załoga bez filtrów, płyt baterii albo taśmy ciśnieniowej widzi czystą wypłatę i przyjmuje akta przed przeczytaniem klauzuli współrzędnych. Gdy pierwsza zaplombowana skrzynia trafia na pokład, tablica już wie, dokąd załoga nadal sięga i czego opuszczona strefa nie zdążyła pogrzebać.",
    },
    "pt_BR": {
        "localization_status": DRAFT_STATUS,
        "title": "Semente de contrato-isca de Conformidade de Recuperação",
        "scanner": "Semente de contrato: isca de Conformidade de Recuperação. Pagamento alto, cadeia de receptor contaminada, exigência de coordenadas oculta.",
        "terminal": "SEMENTE-ISCA: pagamento elevado, receptor de Conformidade de Recuperação mascarado, cláusula de coordenadas escondida, pressão de retenção ativa, roteamento Deep Reach provável.",
        "audio": "Um carimbo de resgate compra confiança no cais mais rápido que uma arma.",
        "in_game_wiki": "Contratos-isca de Conformidade de Recuperação chegam como trabalhos generosos de resgate, mas a cadeia de receptor já está inclinada para a Deep Reach. O pagamento é real. O custo é a exigência oculta de revelar onde o destroço, a etiqueta de cadáver, a caixa de amostras ou a máquina lacrada foram encontrados.",
        "external_site": "A isca de Conformidade de Recuperação transforma uma ordem lucrativa de resgate em armadilha de propriedade: cada peça recuperada passa a carregar um endereço de retorno.",
        "field_note": "Nota de saqueador: se o trabalho paga limpo demais, veja quem é dono da toalha.",
        "external_site_article": "A isca de Conformidade de Recuperação é um dos contratos limpos mais sujos do quadro. A ordem usa uma cara de serviço público: recuperar armários médicos inundados, trazer identificadores de trajes mortos, remover núcleos de máquinas perigosas, devolver carga lacrada antes que decomposição ou dano por pressão destruam o registro. O pagamento listado é alto o bastante para parecer misericórdia numa semana ruim.\n\nA armadilha fica na cadeia de receptor. Um carimbo de Conformidade de Recuperação pode passar por escritórios neutros de salvage, seguradoras coloniais ou mesas de limpeza de desastre, mas o leitor final muitas vezes pertence à Deep Reach ou a um procurador que vende acesso prioritário para ela. O operador recebe pela recuperação material e fica discretamente preso a prova de coordenadas, tiras de estado de escotilha e notas de custódia. Recusar a entrega não remove o risco. Isso marca a rota como sensível a retenção e torna receptores seguros futuros menos pacientes.\n\nEsses contratos funcionam porque o desespero faz boa papelada parecer abrigo. Uma tripulação com poucos filtros, placas de bateria ou fita de pressão vê um pagamento limpo e aceita a ordem antes de ler a cláusula de coordenadas. Quando a primeira caixa lacrada está a bordo, o quadro já aprendeu até onde a tripulação ainda consegue chegar e o que a zona abandonada ainda não conseguiu enterrar.",
    },
    "ru_RU": {
        "localization_status": DRAFT_STATUS,
        "title": "Зерно контракта-приманки Recovery Compliance",
        "scanner": "Зерно контракта: приманка Recovery Compliance. Высокая выплата, загрязненная цепочка приемки, скрытое требование координат.",
        "terminal": "ЗЕРНО-ПРИМАНКА: выплата повышена, приемщик Recovery Compliance замаскирован, пункт раскрытия координат скрыт, давление за удержание активно, вероятна маршрутизация Deep Reach.",
        "audio": "Спасательная печать покупает доверие дока быстрее, чем оружие.",
        "in_game_wiki": "Контракты-приманки Recovery Compliance приходят как щедрые задания на аварийный возврат, но цепочка приемки уже согнута в сторону Deep Reach. Выплата настоящая. Цена — скрытая обязанность раскрыть, где найдены обломок, трупный жетон, ящик образцов или запечатанная машина.",
        "external_site": "Приманка Recovery Compliance превращает выгодное спасательное дело в ловушку собственности: каждая возвращенная деталь начинает нести обратный адрес.",
        "field_note": "Заметка мародера: если работа платит слишком чисто, проверь, кому принадлежит полотенце.",
        "external_site_article": "Приманка Recovery Compliance — один из самых грязных чистых контрактов на доске. Дело носит лицо общественной службы: достать затопленные медицинские шкафы, вернуть идентификаторы мертвых костюмов, убрать опасные машинные ядра, доставить запечатанный груз до того, как гниение или давление испортят запись. Указанная выплата достаточно высока, чтобы в плохую неделю выглядеть милостью.\n\nЛовушка находится в цепочке приемки. Печать Recovery Compliance может пройти через нейтральные salvage-конторы, колониальных страховщиков или столы ликвидации аварий, но последний читатель часто принадлежит Deep Reach или посреднику, который продает им приоритетный доступ. Оператор получает деньги за материальный возврат и тихо привязывается к доказательству координат, лентам состояния люка и заметкам о хранении. Отказ от передачи не снимает риск. Он помечает маршрут как чувствительный к удержанию и делает будущих безопасных приемщиков менее терпеливыми.\n\nЭти контракты работают потому, что отчаяние заставляет хорошую бумагу выглядеть укрытием. Команда без фильтров, батарейных пластин или гермоленты видит чистую выплату и принимает дело до чтения пункта о координатах. К моменту, когда первый запечатанный ящик уже на борту, доска знает, куда команда еще может дотянуться и что заброшенная зона еще не успела похоронить.",
    },
    "uk_UA": {
        "localization_status": DRAFT_STATUS,
        "title": "Зерно контракту-приманки Recovery Compliance",
        "scanner": "Зерно контракту: приманка Recovery Compliance. Висока виплата, забруднений ланцюг приймання, прихована вимога координат.",
        "terminal": "ЗЕРНО-ПРИМАНКА: виплату підвищено, приймача Recovery Compliance замасковано, пункт розкриття координат приховано, тиск за утримання активний, маршрутизація Deep Reach імовірна.",
        "audio": "Рятувальна печатка купує довіру доку швидше, ніж зброя.",
        "in_game_wiki": "Контракти-приманки Recovery Compliance приходять як щедрі завдання на аварійне повернення, але ланцюг приймання вже зігнутий у бік Deep Reach. Виплата справжня. Ціна — прихований обов'язок розкрити, де знайдено уламок, жетон тіла, ящик зразків або запечатану машину.",
        "external_site": "Приманка Recovery Compliance перетворює вигідну рятувальну справу на пастку власності: кожна повернена деталь починає нести зворотну адресу.",
        "field_note": "Нотатка мародера: якщо робота платить надто чисто, перевір, кому належить рушник.",
        "external_site_article": "Приманка Recovery Compliance — один із найбрудніших чистих контрактів на дошці. Справа має обличчя суспільної служби: дістати затоплені медичні шафи, повернути ідентифікатори мертвих костюмів, прибрати небезпечні машинні ядра, доставити запечатаний вантаж до того, як гниття або тиск зіпсують запис. Зазначена виплата досить висока, щоб у поганий тиждень виглядати милістю.\n\nПастка сидить у ланцюзі приймання. Печатка Recovery Compliance може пройти через нейтральні salvage-контори, колоніальних страховиків або столи ліквідації аварій, але останній читач часто належить Deep Reach або посереднику, який продає їм пріоритетний доступ. Оператор отримує гроші за матеріальне повернення і тихо прив'язується до доказу координат, стрічок стану люка та нотаток про зберігання. Відмова від передачі не знімає ризик. Вона позначає маршрут як чутливий до утримання і робить майбутніх безпечних приймачів менш терплячими.\n\nЦі контракти працюють тому, що відчай змушує добрий папір виглядати прихистком. Команда без фільтрів, батарейних пластин або гермострічки бачить чисту виплату і приймає справу до читання пункту про координати. Коли перший запечатаний ящик уже на борту, дошка знає, куди команда ще може дотягнутися і що покинута зона ще не встигла поховати.",
    },
    "zh_CN": {
        "localization_status": DRAFT_STATUS,
        "title": "回收合规诱饵合同种子",
        "scanner": "合同种子：回收合规诱饵。高额报酬，受污染的接收链，隐藏坐标要求。",
        "terminal": "诱饵种子：报酬提高，回收合规接收方被掩盖，坐标披露条款隐藏，扣留压力激活，Deep Reach 路由可能性高。",
        "audio": "一枚救援印章买下码头信任，比枪还快。",
        "in_game_wiki": "回收合规诱饵合同看起来像慷慨的打捞回收工作，但接收链已经向 Deep Reach 倾斜。报酬是真的。代价是隐藏义务：必须说明残骸、尸体标签、样本箱或封存机器是在何处发现的。",
        "external_site": "回收合规诱饵把有利可图的救援案卷变成所有权陷阱：每一件回收物都开始带上退回地址。",
        "field_note": "掠夺者笔记：如果这活儿付钱太干净，先查查毛巾是谁的。",
        "external_site_article": "回收合规诱饵是合同板上最脏的干净合同之一。案卷披着公共服务的面孔：回收进水的医疗柜，带回死亡潜服的识别件，移除危险机器核心，在腐败或压力损伤毁掉记录前送回封存货物。列出的报酬足够高，在艰难的一周里像是一点仁慈。\n\n陷阱藏在接收链里。回收合规印章可以经过中立打捞办公室、殖民地保险方或灾后清理台面，但最后的读取方常常属于 Deep Reach，或属于向他们出售优先访问权的代理。操作者拿到物资回收的钱，同时被悄悄绑上坐标证明、舱门状态条和保管记录。拒绝交接并不会消除风险。它会把路线标成扣留敏感，让后续安全接收方更没有耐心。\n\n这些合同会奏效，因为绝望会让漂亮文件看起来像庇护。缺少过滤器、电池板或压力胶带的队伍看到一笔干净报酬，往往在读完坐标条款前就接下案卷。等第一只封存箱上船时，合同板已经知道这支队伍还能抵达哪里，也知道废弃区还有什么没来得及埋掉。",
    },
}

data = json.loads(PATH.read_text(encoding="utf-8"))
for packet in data["packets"]:
    if packet.get("packet_id") == PACKET_ID:
        packet["localized"] = localized
        break
else:
    raise SystemExit(f"missing packet {PACKET_ID}")

PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
