#!/usr/bin/env python3
"""Deterministic echo-tap and clipping simulator for HECTON-8 acoustic material data."""

from __future__ import annotations

import argparse
import json
import math
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Mapping, Sequence


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE_PATH = ROOT_DIR / "Data" / "Audio" / "Acoustic_Material_Profiles.json"
DEFAULT_JSON_OUTPUT_PATH = ROOT_DIR / "Data" / "Audio" / "AudioSim_LastRun.json"

STATUS_OK = "ACOUSTIC_TAPS_SIMULATED"
SOUND_SPEED_SEAWATER_MPS = 1480.0
SONAR_DECAY_K = 0.0035
EPSILON_DISTANCE_M = 0.001
REQUIRED_MATERIAL_COUNT = 20
ENERGY_SUM_TOLERANCE = 0.0001


@dataclass(frozen=True)
class MaterialProfile:
    """Material response used by the offline echo model."""

    material_id: str
    absorption: float
    reflection: float
    transmission: float
    low_pass_hz: float
    echo_semantic: str


@dataclass(frozen=True)
class Room:
    """Rectangular echo chamber dimensions in meters."""

    width_m: float
    depth_m: float
    height_m: float


@dataclass(frozen=True)
class Tap:
    """Virtual echo tap generated by a reflected sonar path."""

    surface: str
    order: int
    distance_m: float
    delay_ms: float
    amplitude: float
    low_pass_hz: float
    channel_hint: str
    material_id: str


def clamp(value: float, minimum: float, maximum: float) -> float:
    """Clamp a scalar without importing nonstandard dependencies."""

    return max(minimum, min(maximum, value))


def load_profile_payload(profile_path: Path) -> Mapping[str, object]:
    """Load the acoustic profile JSON."""

    with profile_path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError("profile root must be a JSON object")
    return payload


def parse_materials(payload: Mapping[str, object]) -> dict[str, MaterialProfile]:
    """Parse and validate material rows."""

    raw_materials = payload.get("materialProfiles")
    if not isinstance(raw_materials, list):
        raise ValueError("materialProfiles must be a list")
    if len(raw_materials) != REQUIRED_MATERIAL_COUNT:
        raise ValueError(f"material profile count must be {REQUIRED_MATERIAL_COUNT}, got {len(raw_materials)}")

    materials: dict[str, MaterialProfile] = {}
    for index, raw in enumerate(raw_materials):
        if not isinstance(raw, dict):
            raise ValueError(f"materialProfiles[{index}] must be an object")
        material_id = str(raw.get("id", ""))
        if not material_id:
            raise ValueError(f"materialProfiles[{index}].id is empty")
        if material_id in materials:
            raise ValueError(f"duplicate material id: {material_id}")

        coeffs = raw.get("coefficients")
        if not isinstance(coeffs, dict):
            raise ValueError(f"{material_id}.coefficients must be an object")
        absorption = float(coeffs.get("absorption"))
        reflection = float(coeffs.get("reflection"))
        transmission = float(coeffs.get("transmission"))
        for label, value in (("absorption", absorption), ("reflection", reflection), ("transmission", transmission)):
            if not math.isfinite(value) or value < 0.0 or value > 1.0:
                raise ValueError(f"{material_id}.{label} must be finite within 0..1")
        energy_sum = absorption + reflection + transmission
        if abs(energy_sum - 1.0) > ENERGY_SUM_TOLERANCE:
            raise ValueError(f"{material_id} coefficients sum to {energy_sum:.8f}, expected 1.0")

        low_pass_hz = float(raw.get("reflectionLowPassHz"))
        if not math.isfinite(low_pass_hz) or low_pass_hz < 80.0 or low_pass_hz > 22000.0:
            raise ValueError(f"{material_id}.reflectionLowPassHz outside safe range")

        materials[material_id] = MaterialProfile(
            material_id=material_id,
            absorption=absorption,
            reflection=reflection,
            transmission=transmission,
            low_pass_hz=low_pass_hz,
            echo_semantic=str(raw.get("echoSemantic", "Unknown")),
        )

    return materials


def validate_recipes(payload: Mapping[str, object]) -> None:
    """Validate granular recipes and sonar signatures referenced by the prompt."""

    recipes = payload.get("granularTextureRecipes")
    if not isinstance(recipes, list) or len(recipes) != 3:
        raise ValueError("granularTextureRecipes must contain exactly 3 recipes")
    expected_recipes = {"metal_stress", "ice_cracking", "water_pressure"}
    actual_recipes = {str(row.get("id", "")) for row in recipes if isinstance(row, dict)}
    if actual_recipes != expected_recipes:
        raise ValueError(f"granular recipe ids mismatch: {sorted(actual_recipes)}")

    signatures = payload.get("sonarPingSignatures")
    if not isinstance(signatures, list) or len(signatures) < 10:
        raise ValueError("sonarPingSignatures must contain at least 10 object signatures")

    doppler = payload.get("alphaLeviathanDopplerCurve")
    if not isinstance(doppler, dict):
        raise ValueError("alphaLeviathanDopplerCurve missing")
    thresholds = doppler.get("thresholds")
    if not isinstance(thresholds, list) or len(thresholds) < 5:
        raise ValueError("alphaLeviathanDopplerCurve.thresholds must contain at least 5 rows")
    previous_speed = -math.inf
    previous_pitch = -math.inf
    for row in thresholds:
        if not isinstance(row, dict):
            raise ValueError("doppler threshold rows must be objects")
        speed = float(row.get("relativeSpeedMps"))
        pitch = float(row.get("authoredPitchRatio"))
        if speed <= previous_speed:
            raise ValueError("doppler thresholds must be sorted by relativeSpeedMps")
        if pitch < previous_pitch:
            raise ValueError("doppler pitch ratios must be monotonic")
        if pitch < 0.5 or pitch > 2.0:
            raise ValueError("doppler pitch ratio outside safe authored range")
        previous_speed = speed
        previous_pitch = pitch


def transmission_loss_amplitude(path_distance_m: float) -> float:
    """Return normalized sonar amplitude after spherical and absorption loss."""

    safe_distance = max(path_distance_m, EPSILON_DISTANCE_M)
    transmission_loss_db = 20.0 * math.log10(safe_distance) + SONAR_DECAY_K * safe_distance
    return max(0.0, math.pow(10.0, -transmission_loss_db / 20.0))


def resolve_channel_hint(surface: str) -> str:
    """Map room surface to a cheap 7.1 channel hint."""

    if surface == "left_wall":
        return "SL"
    if surface == "right_wall":
        return "SR"
    if surface == "front_wall":
        return "C"
    if surface == "back_wall":
        return "RR"
    if surface == "floor":
        return "LFE"
    if surface == "ceiling":
        return "C+Height"
    if "corner" in surface:
        return "RL+RR"
    return "C"


def make_tap(surface: str, order: int, one_way_distance_m: float, material: MaterialProfile) -> Tap:
    """Build one reflected active-sonar tap."""

    path_distance_m = max(one_way_distance_m * 2.0, EPSILON_DISTANCE_M)
    delay_ms = (path_distance_m / SOUND_SPEED_SEAWATER_MPS) * 1000.0
    raw_amplitude = transmission_loss_amplitude(path_distance_m)
    reflected = raw_amplitude * material.reflection * (1.0 - material.absorption * 0.35)
    if order > 1:
        reflected *= math.pow(0.58, order - 1)
    amplitude = clamp(reflected, 0.0, 1.0)
    return Tap(
        surface=surface,
        order=order,
        distance_m=path_distance_m,
        delay_ms=delay_ms,
        amplitude=amplitude,
        low_pass_hz=material.low_pass_hz,
        channel_hint=resolve_channel_hint(surface),
        material_id=material.material_id,
    )


def simulate_echo_taps(room: Room, material: MaterialProfile, include_second_order: bool) -> List[Tap]:
    """Simulate first-order wall taps and optional second-order corner taps in a 10x10 room."""

    half_width = room.width_m * 0.5
    half_depth = room.depth_m * 0.5
    half_height = room.height_m * 0.5
    taps = [
        make_tap("left_wall", 1, half_width, material),
        make_tap("right_wall", 1, half_width, material),
        make_tap("front_wall", 1, half_depth, material),
        make_tap("back_wall", 1, half_depth, material),
        make_tap("floor", 1, half_height, material),
        make_tap("ceiling", 1, half_height, material),
    ]

    if include_second_order:
        corner_distance = math.sqrt((half_width * half_width) + (half_depth * half_depth))
        vertical_corner_distance = math.sqrt((half_width * half_width) + (half_height * half_height))
        taps.extend(
            [
                make_tap("front_left_corner", 2, corner_distance, material),
                make_tap("front_right_corner", 2, corner_distance, material),
                make_tap("back_left_corner", 2, corner_distance, material),
                make_tap("back_right_corner", 2, corner_distance, material),
                make_tap("floor_left_edge", 2, vertical_corner_distance, material),
                make_tap("ceiling_right_edge", 2, vertical_corner_distance, material),
            ]
        )

    taps.sort(key=lambda tap: (tap.delay_ms, tap.surface))
    return taps


def audit_clipping(taps: Sequence[Tap], payload: Mapping[str, object], voice_count: int) -> dict[str, float | int | str]:
    """Compute conservative peak bound for N aligned procedural voices."""

    mix_safety = payload.get("mixSafety")
    if not isinstance(mix_safety, dict):
        raise ValueError("mixSafety missing")
    target_peak = float(mix_safety.get("targetPeakCeiling", 0.98))
    nominal_gain = float(mix_safety.get("perVoiceNominalGain", 0.058))
    tap_sum = sum(abs(tap.amplitude) for tap in taps)
    single_voice_unscaled = 1.0 + tap_sum
    safe_gain = target_peak / max(1.0, float(voice_count) * single_voice_unscaled)
    applied_gain = min(nominal_gain, safe_gain)
    peak_bound = applied_gain * float(voice_count) * single_voice_unscaled
    status = "PASS" if peak_bound <= 1.0 else "FAIL"
    return {
        "voiceCount": voice_count,
        "tapCount": len(taps),
        "tapAmplitudeSum": round(tap_sum, 8),
        "singleVoiceUnscaledPeakBound": round(single_voice_unscaled, 8),
        "nominalGain": round(nominal_gain, 8),
        "appliedGain": round(applied_gain, 8),
        "peakBound16Voices": round(peak_bound, 8),
        "targetPeakCeiling": round(target_peak, 8),
        "status": status,
    }


def audit_all_material_clipping(
    materials: Mapping[str, MaterialProfile],
    payload: Mapping[str, object],
    room: Room,
    voice_count: int,
    include_second_order: bool,
) -> dict[str, object]:
    """Audit every material and return the worst 16-voice clipping case."""

    rows: List[dict[str, float | int | str]] = []
    worst_peak = -1.0
    worst_material_id = ""
    failed_count = 0
    for material_id in sorted(materials):
        taps = simulate_echo_taps(room, materials[material_id], include_second_order=include_second_order)
        clipping = audit_clipping(taps, payload, voice_count)
        peak_bound = float(clipping["peakBound16Voices"])
        if peak_bound > worst_peak:
            worst_peak = peak_bound
            worst_material_id = material_id
        if clipping["status"] != "PASS":
            failed_count += 1
        rows.append(
            {
                "materialId": material_id,
                "tapCount": int(clipping["tapCount"]),
                "tapAmplitudeSum": float(clipping["tapAmplitudeSum"]),
                "appliedGain": float(clipping["appliedGain"]),
                "peakBound16Voices": peak_bound,
                "status": str(clipping["status"]),
            }
        )

    return {
        "status": "PASS" if failed_count == 0 else "FAIL",
        "materialCount": len(rows),
        "failedCount": failed_count,
        "worstMaterialId": worst_material_id,
        "worstPeakBound16Voices": round(worst_peak, 8),
        "rows": rows,
    }


def build_report_payload(
    profile_path: Path,
    material: MaterialProfile,
    room: Room,
    taps: Sequence[Tap],
    clipping: Mapping[str, float | int | str],
    all_material_audit: Mapping[str, object],
    elapsed_us: float,
) -> dict[str, object]:
    """Build a deterministic JSON report."""

    return {
        "status": STATUS_OK,
        "profilePath": str(profile_path.relative_to(ROOT_DIR) if profile_path.is_relative_to(ROOT_DIR) else profile_path),
        "materialId": material.material_id,
        "roomMeters": {
            "width": room.width_m,
            "depth": room.depth_m,
            "height": room.height_m,
        },
        "constants": {
            "soundSpeedMps": SOUND_SPEED_SEAWATER_MPS,
            "sonarDecayK": SONAR_DECAY_K,
        },
        "virtualTaps": [
            {
                "surface": tap.surface,
                "order": tap.order,
                "distanceM": round(tap.distance_m, 6),
                "delayMs": round(tap.delay_ms, 6),
                "amplitude": round(tap.amplitude, 8),
                "lowPassHz": round(tap.low_pass_hz, 3),
                "channelHint": tap.channel_hint,
                "materialId": tap.material_id,
            }
            for tap in taps
        ],
        "clippingAudit": dict(clipping),
        "allMaterialClippingAudit": dict(all_material_audit),
        "elapsedUs": round(elapsed_us, 2),
    }


def print_report(report: Mapping[str, object]) -> None:
    """Print a compact deterministic CLI report."""

    print(f"STATUS: {report['status']}")
    print(
        "ROOM: "
        f"{report['roomMeters']['width']:.2f}x{report['roomMeters']['depth']:.2f}x"
        f"{report['roomMeters']['height']:.2f} m material={report['materialId']}"
    )
    print("VIRTUAL_TAPS:")
    for tap in report["virtualTaps"]:
        print(
            "  "
            f"{tap['surface']:>18} order={tap['order']} "
            f"delayMs={tap['delayMs']:.6f} amp={tap['amplitude']:.8f} "
            f"lpfHz={tap['lowPassHz']:.1f} ch={tap['channelHint']}"
        )
    clipping = report["clippingAudit"]
    print(
        "CLIPPING: "
        f"voices={clipping['voiceCount']} taps={clipping['tapCount']} "
        f"tapSum={clipping['tapAmplitudeSum']:.8f} appliedGain={clipping['appliedGain']:.8f} "
        f"peakBound={clipping['peakBound16Voices']:.8f} status={clipping['status']}"
    )
    all_material = report["allMaterialClippingAudit"]
    print(
        "ALL_MATERIAL_CLIPPING: "
        f"materials={all_material['materialCount']} failed={all_material['failedCount']} "
        f"worst={all_material['worstMaterialId']} "
        f"peakBound={all_material['worstPeakBound16Voices']:.8f} status={all_material['status']}"
    )
    print(f"ELAPSED_US: {report['elapsedUs']:.2f}")


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description="Simulate HECTON-8 acoustic echo taps in a rectangular room.")
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE_PATH)
    parser.add_argument("--material", default="steel_hull")
    parser.add_argument("--width", type=float, default=10.0)
    parser.add_argument("--depth", type=float, default=10.0)
    parser.add_argument("--height", type=float, default=3.0)
    parser.add_argument("--voices", type=int, default=16)
    parser.add_argument("--first-order-only", action="store_true")
    parser.add_argument("--json-output", type=Path, default=None)
    return parser.parse_args(list(argv))


def run(args: argparse.Namespace) -> dict[str, object]:
    """Run the simulation and return the report payload."""

    started = time.perf_counter()
    payload = load_profile_payload(args.profile)
    materials = parse_materials(payload)
    validate_recipes(payload)

    if args.material not in materials:
        raise ValueError(f"unknown material id: {args.material}")
    if args.width <= 0.0 or args.depth <= 0.0 or args.height <= 0.0:
        raise ValueError("room dimensions must be positive")
    if args.voices <= 0 or args.voices > 128:
        raise ValueError("voices must be within 1..128")

    material = materials[args.material]
    room = Room(args.width, args.depth, args.height)
    taps = simulate_echo_taps(room, material, include_second_order=not args.first_order_only)
    clipping = audit_clipping(taps, payload, args.voices)
    all_material_audit = audit_all_material_clipping(
        materials,
        payload,
        room,
        args.voices,
        include_second_order=not args.first_order_only,
    )
    elapsed_us = (time.perf_counter() - started) * 1_000_000.0
    return build_report_payload(args.profile, material, room, taps, clipping, all_material_audit, elapsed_us)


def main(argv: Iterable[str]) -> int:
    """CLI entry point."""

    args = parse_args(argv)
    report = run(args)
    print_report(report)
    if args.json_output is not None:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return 0 if report["clippingAudit"]["status"] == "PASS" and report["allMaterialClippingAudit"]["status"] == "PASS" else 2


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
