import sys
import unittest
from pathlib import Path


TOOLS_ROOT = Path(__file__).resolve().parent
if str(TOOLS_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOLS_ROOT))

import ValidateVisualReferenceOwnerMatrix as validator  # noqa: E402


class ValidateVisualReferenceOwnerMatrixTests(unittest.TestCase):
    def test_current_project_visual_reference_owner_matrix_matches_images(self) -> None:
        rows = validator.validate_visual_reference_owner_matrix()

        self.assertEqual(15, len(rows))
        self.assertEqual("VREF-01", rows[0].vref_id)
        self.assertEqual("VREF-15", rows[-1].vref_id)

    def test_png_dimensions_are_read(self) -> None:
        path = validator.ROOT / "Docs/mandatory if you work on systems that user sees (water, terrain, sky, flora, ui) - read this and all images inside (references)/BEST ILLUST - ON SURFACE (WITH TREES AND GRASS) - CHECK WATER, GAS GIANT. it is perfect! your goal to look like it! make plan and do it.png"

        self.assertEqual((1375, 768), validator.read_image_dimensions(path))

    def test_jpeg_dimensions_are_read(self) -> None:
        path = validator.ROOT / "Docs/mandatory if you work on systems that user sees (water, terrain, sky, flora, ui) - read this and all images inside (references)/UNDERWATER-GENERATED BY AI - MIDDLE DEEP.jpg"

        self.assertEqual((1280, 714), validator.read_image_dimensions(path))

    def test_webp_dimensions_are_read(self) -> None:
        path = validator.ROOT / "Docs/mandatory if you work on systems that user sees (water, terrain, sky, flora, ui) - read this and all images inside (references)/beauty.webp"

        self.assertEqual((960, 540), validator.read_image_dimensions(path))

    def test_dimension_drift_rejected(self) -> None:
        rows = validator.load_matrix_rows()
        edited = list(rows)
        edited[0] = validator.VisualReferenceRow(
            vref_id=rows[0].vref_id,
            source_file=rows[0].source_file,
            dimensions="1x1",
            primary_surface=rows[0].primary_surface,
            owner_packets=rows[0].owner_packets,
            required_future_h8_artifact=rows[0].required_future_h8_artifact,
            visual_requirement=rows[0].visual_requirement,
            reject_if=rows[0].reject_if,
            status=rows[0].status,
        )

        with self.assertRaises(SystemExit):
            _validate_rows_for_test(edited)


def _validate_rows_for_test(rows: list[validator.VisualReferenceRow]) -> None:
    original_loader = validator.load_matrix_rows
    try:
        validator.load_matrix_rows = lambda path=validator.MATRIX_PATH: rows  # type: ignore[assignment]
        validator.validate_visual_reference_owner_matrix()
    finally:
        validator.load_matrix_rows = original_loader  # type: ignore[assignment]


if __name__ == "__main__":
    unittest.main()
