using Hecton8.Core;
using UnityEngine;
using UnityEngine.Rendering;

namespace Hecton8.Atmosphere
{
    /// <summary>
    /// Scene-local visual rig for above-water rain and lightning presentation.
    /// Driven exclusively by <see cref="HectonSurfaceWeatherDirector"/>.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class SurfaceWeatherVfxRig : MonoBehaviour, IOriginShiftListener
    {
        private const int BoltPointCount = 6;
        private const float RainEmitterHeight = 10f;
        private const float SurfaceImpactHeightOffset = 0.04f;
        private const float BoltDurationSeconds = 0.14f;

        [Header("Rain")]
        [Tooltip("Maximum local rain emission rate at precipitation=1.")]
        [SerializeField, Min(1f)] private float maxRainEmissionRate = 420f;

        [Tooltip("Half extents of the local rain box around the player.")]
        [SerializeField] private Vector3 rainVolumeSize = new Vector3(20f, 2f, 20f);

        [Tooltip("Maximum local rain particles kept alive in the rig.")]
        [SerializeField, Min(16)] private int maxRainParticles = 512;

        [Tooltip("Horizontal wind influence applied to rain streaks.")]
        [SerializeField, Min(0f)] private float rainWindVelocity = 4.5f;

        [Header("Rain Surface")]
        [Tooltip("Radius around the player used for rain water impacts on the ocean surface.")]
        [SerializeField, Min(1f)] private float surfaceImpactRadius = 18f;

        [Tooltip("Maximum rain impact emission rate at precipitation=1.")]
        [SerializeField, Min(1f)] private float maxSurfaceImpactEmissionRate = 180f;

        [Tooltip("Maximum particle budget for surface rain impacts.")]
        [SerializeField, Min(16)] private int maxSurfaceImpactParticles = 320;

        [Header("Lightning")]
        [Tooltip("Height of the lightning source point above the water surface.")]
        [SerializeField, Min(5f)] private float lightningHeight = 95f;

        [Tooltip("Radius of the point light generated by lightning strikes.")]
        [SerializeField, Min(1f)] private float lightningLightRange = 140f;

        [Tooltip("Shared line-renderer material used by lightning bolts. Runtime fallback material creation is forbidden.")]
        [SerializeField] private Material lightningBoltMaterial;

        private Transform _rainRoot;
        private ParticleSystem _rainParticleSystem;
        private Transform _surfaceImpactRoot;
        private ParticleSystem _surfaceImpactParticleSystem;
        private Light _lightningLight;
        private LineRenderer _boltRenderer;
        private float _boltTimer;
        private float _boltIntensity;
        private float _cachedRainEmissionRate = -1f;
        private float _cachedRainVelocityX = float.MinValue;
        private float _cachedRainVelocityY = float.MinValue;
        private float _cachedRainVelocityZ = float.MinValue;
        private float _cachedSurfaceImpactEmissionRate = -1f;
        private float _cachedSurfaceImpactVelocityX = float.MinValue;
        private float _cachedSurfaceImpactVelocityY = float.MinValue;
        private float _cachedSurfaceImpactVelocityZ = float.MinValue;
        private float _cachedRainAreaScale = float.MinValue;
        private float _cachedSurfaceImpactRadiusScale = float.MinValue;
        private float _currentSurfaceImpactDensityMultiplier = 1f;
        private bool _loggedMissingBoltMaterial;

        // COLD ALLOC: Vector3[6] - reusable bolt polyline points for world lightning - owner: SurfaceWeatherVfxRig
        private readonly Vector3[] _boltPoints = new Vector3[BoltPointCount];
        // COLD ALLOC: ParticleSystem.Particle[maxRainParticles] - reusable world-space rain shift buffer - owner: SurfaceWeatherVfxRig
        private ParticleSystem.Particle[] _rainShiftParticles;
        // COLD ALLOC: ParticleSystem.Particle[maxSurfaceImpactParticles] - reusable world-space surface-impact shift buffer - owner: SurfaceWeatherVfxRig
        private ParticleSystem.Particle[] _surfaceImpactShiftParticles;

        private void Awake()
        {
            EnsureRigBuilt();
            EnsureShiftBuffers();
            ClearState();
        }

        private void OnEnable()
        {
            HectonFloatingOrigin.RegisterListener(this);
        }

        private void OnDisable()
        {
            HectonFloatingOrigin.UnregisterListener(this);
        }

        private void OnDestroy()
        {
            HectonFloatingOrigin.UnregisterListener(this);
        }

        internal void ConfigureAuthoring(Material authoredLightningBoltMaterial)
        {
            if (authoredLightningBoltMaterial == null)
                return;

            lightningBoltMaterial = authoredLightningBoltMaterial;
            if (_boltRenderer != null)
                _boltRenderer.sharedMaterial = lightningBoltMaterial;
        }

        /// <summary>
        /// Updates local rain presentation and fades active lightning visuals.
        /// </summary>
        /// <param name="deltaTime">Tick delta time.</param>
        /// <param name="followPosition">Tracked player/world position.</param>
        /// <param name="surfaceY">Current water surface Y.</param>
        /// <param name="windDirection">Normalized XZ wind direction.</param>
        /// <param name="precipitationIntensity">Current precipitation intensity.</param>
        /// <param name="active">True when surface-local VFX should remain visible.</param>
        internal void ApplyState(
            float deltaTime,
            Vector3 followPosition,
            float surfaceY,
            Vector2 windDirection,
            float precipitationIntensity,
            float localRainAreaScale,
            float localRainDensityMultiplier,
            float surfaceImpactRadiusScale,
            float surfaceImpactDensityMultiplier,
            bool active)
        {
            EnsureRigBuilt();
            UpdateRainState(followPosition, surfaceY, windDirection, precipitationIntensity, localRainAreaScale, localRainDensityMultiplier, active);
            UpdateSurfaceImpactState(followPosition, surfaceY, windDirection, precipitationIntensity, surfaceImpactRadiusScale, surfaceImpactDensityMultiplier, active);
            UpdateLightningState(deltaTime);
        }

        public void OnOriginShift(in OriginShiftEventData shiftData)
        {
            Vector3 shiftOffset = shiftData.ShiftOffset;
            if (!isActiveAndEnabled || shiftOffset.sqrMagnitude <= 0.000001f)
                return;

            EnsureShiftBuffers();
            RebaseWorldSpaceParticles(_rainParticleSystem, _rainShiftParticles, shiftOffset);
            RebaseWorldSpaceParticles(_surfaceImpactParticleSystem, _surfaceImpactShiftParticles, shiftOffset);
            RebaseBoltPositions(shiftOffset);
        }

        /// <summary>
        /// Triggers one world lightning bolt and synchronized flash light.
        /// </summary>
        internal void TriggerLightningStrike(
            Vector3 impactPosition,
            Vector2 windDirection,
            float flashStrength,
            float randomA,
            float randomB,
            float boltWidthMultiplier,
            float lightRangeMultiplier)
        {
            EnsureRigBuilt();

            Vector3 strikeDirection = new Vector3(windDirection.x, 0f, windDirection.y);
            if (strikeDirection.sqrMagnitude < 0.0001f)
            {
                strikeDirection.x = Mathf.Cos(randomA * Mathf.PI * 2f);
                strikeDirection.z = Mathf.Sin(randomA * Mathf.PI * 2f);
            }

            strikeDirection.Normalize();

            Vector3 endPoint = impactPosition;

            Vector3 startPoint = endPoint + Vector3.up * lightningHeight;
            Vector3 side = Vector3.Cross(Vector3.up, strikeDirection);
            if (side.sqrMagnitude < 0.0001f)
                side = Vector3.right;
            side.Normalize();

            Vector3 windOffset = new Vector3(windDirection.x, 0f, windDirection.y) * 3f;

            for (int i = 0; i < BoltPointCount; i++)
            {
                float t = i / (BoltPointCount - 1f);
                Vector3 point = Vector3.Lerp(startPoint, endPoint, t);
                float jitterAmplitude = Mathf.Lerp(14f, 1.5f, t);
                float phase = (randomA * 13.37f) + (randomB * 7.11f) + (i * 1.618f);
                point += side * (Mathf.Sin(phase) * jitterAmplitude);
                point += windOffset * (1f - t) * 0.2f;
                _boltPoints[i] = point;
            }

            _boltPoints[0] = startPoint;
            _boltPoints[BoltPointCount - 1] = endPoint;

            _boltRenderer.positionCount = BoltPointCount;
            _boltRenderer.SetPositions(_boltPoints);
            float widthScale = Mathf.Max(0.5f, boltWidthMultiplier);
            _boltRenderer.startWidth = Mathf.Lerp(0.9f, 1.6f, Mathf.Clamp01(flashStrength)) * widthScale;
            _boltRenderer.endWidth = Mathf.Lerp(0.12f, 0.24f, Mathf.Clamp01(flashStrength)) * widthScale;
            _boltRenderer.enabled = true;

            _lightningLight.transform.position = endPoint + Vector3.up * 18f;
            _lightningLight.intensity = Mathf.Lerp(3f, 10f, Mathf.Clamp01(flashStrength));
            _lightningLight.range = lightningLightRange * Mathf.Max(0.5f, lightRangeMultiplier);
            _lightningLight.enabled = true;

            _boltTimer = BoltDurationSeconds;
            _boltIntensity = Mathf.Clamp01(flashStrength);
        }

        /// <summary>
        /// Emits a localized water splash burst on the surface near the player.
        /// </summary>
        internal void TriggerSurfaceSplashBurst(
            Vector3 centerPosition,
            float surfaceY,
            Vector2 windDirection,
            float intensity)
        {
            const float VelocityEpsilon = 0.01f;

            EnsureRigBuilt();

            if (_surfaceImpactParticleSystem == null || _surfaceImpactRoot == null)
                return;

            var surfaceImpactVelocity = _surfaceImpactParticleSystem.velocityOverLifetime;
            Vector3 surfacePosition = centerPosition;
            surfacePosition.y = surfaceY + SurfaceImpactHeightOffset;
            _surfaceImpactRoot.position = surfacePosition;

            float intensityScale = Mathf.Clamp01(intensity) * Mathf.Max(0.25f, _currentSurfaceImpactDensityMultiplier);
            Vector3 windVelocity = new Vector3(windDirection.x, 0f, windDirection.y) * rainWindVelocity * intensityScale * 0.35f;
            float upwardVelocity = Mathf.Lerp(0.7f, 1.8f, intensity);
            if (Mathf.Abs(_cachedSurfaceImpactVelocityX - windVelocity.x) > VelocityEpsilon)
            {
                surfaceImpactVelocity.x = new ParticleSystem.MinMaxCurve(windVelocity.x);
                _cachedSurfaceImpactVelocityX = windVelocity.x;
            }

            if (Mathf.Abs(_cachedSurfaceImpactVelocityY - upwardVelocity) > VelocityEpsilon)
            {
                surfaceImpactVelocity.y = new ParticleSystem.MinMaxCurve(upwardVelocity);
                _cachedSurfaceImpactVelocityY = upwardVelocity;
            }

            if (Mathf.Abs(_cachedSurfaceImpactVelocityZ - windVelocity.z) > VelocityEpsilon)
            {
                surfaceImpactVelocity.z = new ParticleSystem.MinMaxCurve(windVelocity.z);
                _cachedSurfaceImpactVelocityZ = windVelocity.z;
            }

            if (!_surfaceImpactParticleSystem.isPlaying)
                _surfaceImpactParticleSystem.Play(true);

            int burstCount = Mathf.Clamp(Mathf.RoundToInt(Mathf.Lerp(8f, 22f, intensity) * Mathf.Max(0.25f, _currentSurfaceImpactDensityMultiplier)), 1, 40);
            _surfaceImpactParticleSystem.Emit(burstCount);
        }

        /// <summary>
        /// Stops rain emission and hides any active lightning presentation.
        /// </summary>
        internal void ClearState()
        {
            if (_rainParticleSystem != null)
            {
                var rainEmission = _rainParticleSystem.emission;
                rainEmission.rateOverTime = 0f;
                _rainParticleSystem.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
            }

            if (_surfaceImpactParticleSystem != null)
            {
                var surfaceImpactEmission = _surfaceImpactParticleSystem.emission;
                surfaceImpactEmission.rateOverTime = 0f;
                _surfaceImpactParticleSystem.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
            }

            _boltTimer = 0f;
            _boltIntensity = 0f;

            if (_boltRenderer != null)
                _boltRenderer.enabled = false;

            if (_lightningLight != null)
            {
                _lightningLight.enabled = false;
                _lightningLight.intensity = 0f;
            }

            _cachedRainEmissionRate = -1f;
            _cachedRainVelocityX = float.MinValue;
            _cachedRainVelocityY = float.MinValue;
            _cachedRainVelocityZ = float.MinValue;
            _cachedSurfaceImpactEmissionRate = -1f;
            _cachedSurfaceImpactVelocityX = float.MinValue;
            _cachedSurfaceImpactVelocityY = float.MinValue;
            _cachedSurfaceImpactVelocityZ = float.MinValue;
            _cachedRainAreaScale = float.MinValue;
            _cachedSurfaceImpactRadiusScale = float.MinValue;
            _currentSurfaceImpactDensityMultiplier = 1f;
        }

        private void EnsureRigBuilt()
        {
            if (_rainParticleSystem != null &&
                _surfaceImpactParticleSystem != null &&
                _boltRenderer != null &&
                _lightningLight != null)
                return;

            if (_rainRoot == null)
            {
                // COLD ALLOC: GameObject[1] - local rain emitter root under weather rig - owner: SurfaceWeatherVfxRig
                GameObject root = new GameObject("RainRoot");
                _rainRoot = root.transform;
                _rainRoot.SetParent(transform, false);
            }

            if (_rainParticleSystem == null)
                BuildRainParticleSystem();

            if (_surfaceImpactParticleSystem == null)
                BuildSurfaceImpactParticleSystem();

            if (_boltRenderer == null)
                BuildLightningBolt();

            if (_lightningLight == null)
                BuildLightningLight();
        }

        private void BuildRainParticleSystem()
        {
            // COLD ALLOC: GameObject[1] - local rain particle emitter - owner: SurfaceWeatherVfxRig
            GameObject rainObject = new GameObject("LocalRain");
            rainObject.transform.SetParent(_rainRoot, false);
            _rainParticleSystem = rainObject.AddComponent<ParticleSystem>();

            var main = _rainParticleSystem.main;
            main.loop = true;
            main.playOnAwake = false;
            main.simulationSpace = ParticleSystemSimulationSpace.World;
            main.maxParticles = maxRainParticles;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.9f, 1.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(18f, 24f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.03f, 0.05f);
            main.startColor = new ParticleSystem.MinMaxGradient(new Color(0.82f, 0.9f, 1f, 0.65f));
            main.gravityModifier = 0.65f;

            var emission = _rainParticleSystem.emission;
            emission.rateOverTime = 0f;

            var shape = _rainParticleSystem.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Box;
            shape.scale = rainVolumeSize;

            var velocity = _rainParticleSystem.velocityOverLifetime;
            velocity.enabled = true;

            var noise = _rainParticleSystem.noise;
            noise.enabled = true;
            noise.strength = 0.3f;
            noise.frequency = 0.22f;

            var renderer = _rainParticleSystem.GetComponent<ParticleSystemRenderer>();
            renderer.renderMode = ParticleSystemRenderMode.Stretch;
            renderer.lengthScale = 3f;
            renderer.velocityScale = 0.2f;
            renderer.shadowCastingMode = ShadowCastingMode.Off;
            renderer.receiveShadows = false;
            renderer.motionVectorGenerationMode = MotionVectorGenerationMode.ForceNoMotion;
        }

        private void EnsureShiftBuffers()
        {
            int rainCapacity = Mathf.Max(1, maxRainParticles);
            if (_rainShiftParticles == null || _rainShiftParticles.Length < rainCapacity)
                _rainShiftParticles = new ParticleSystem.Particle[rainCapacity];

            int surfaceImpactCapacity = Mathf.Max(1, maxSurfaceImpactParticles);
            if (_surfaceImpactShiftParticles == null || _surfaceImpactShiftParticles.Length < surfaceImpactCapacity)
                _surfaceImpactShiftParticles = new ParticleSystem.Particle[surfaceImpactCapacity];
        }

        private void RebaseBoltPositions(Vector3 shiftOffset)
        {
            if (_boltRenderer == null || !_boltRenderer.enabled || _boltRenderer.positionCount <= 0)
                return;

            int positionCount = Mathf.Min(_boltRenderer.positionCount, _boltPoints.Length);
            if (positionCount <= 0)
                return;

            _boltRenderer.GetPositions(_boltPoints);
            for (int i = 0; i < positionCount; i++)
                _boltPoints[i] -= shiftOffset;

            _boltRenderer.SetPositions(_boltPoints);
        }

        private static void RebaseWorldSpaceParticles(ParticleSystem particleSystem, ParticleSystem.Particle[] buffer, Vector3 shiftOffset)
        {
            if (particleSystem == null || buffer == null)
                return;

            ParticleSystem.MainModule main = particleSystem.main;
            if (main.simulationSpace != ParticleSystemSimulationSpace.World)
                return;

            int particleCount = particleSystem.GetParticles(buffer);
            for (int i = 0; i < particleCount; i++)
                buffer[i].position -= shiftOffset;

            particleSystem.SetParticles(buffer, particleCount);
        }

        private void BuildSurfaceImpactParticleSystem()
        {
            // COLD ALLOC: GameObject[1] - local rain surface impact emitter - owner: SurfaceWeatherVfxRig
            GameObject impactObject = new GameObject("RainSurfaceImpacts");
            impactObject.transform.SetParent(transform, false);
            _surfaceImpactRoot = impactObject.transform;
            _surfaceImpactParticleSystem = impactObject.AddComponent<ParticleSystem>();

            var main = _surfaceImpactParticleSystem.main;
            main.loop = true;
            main.playOnAwake = false;
            main.simulationSpace = ParticleSystemSimulationSpace.World;
            main.maxParticles = maxSurfaceImpactParticles;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.25f, 0.5f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.2f, 0.8f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.06f, 0.15f);
            main.startColor = new ParticleSystem.MinMaxGradient(new Color(0.9f, 0.96f, 1f, 0.38f));
            main.gravityModifier = 0f;

            var emission = _surfaceImpactParticleSystem.emission;
            emission.rateOverTime = 0f;

            var shape = _surfaceImpactParticleSystem.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Box;
            shape.scale = new Vector3(surfaceImpactRadius * 2f, 0.05f, surfaceImpactRadius * 2f);

            var velocity = _surfaceImpactParticleSystem.velocityOverLifetime;
            velocity.enabled = true;

            var noise = _surfaceImpactParticleSystem.noise;
            noise.enabled = true;
            noise.strength = 0.18f;
            noise.frequency = 0.35f;

            var renderer = _surfaceImpactParticleSystem.GetComponent<ParticleSystemRenderer>();
            renderer.renderMode = ParticleSystemRenderMode.Billboard;
            renderer.shadowCastingMode = ShadowCastingMode.Off;
            renderer.receiveShadows = false;
            renderer.motionVectorGenerationMode = MotionVectorGenerationMode.ForceNoMotion;
        }

        private void BuildLightningBolt()
        {
            // COLD ALLOC: GameObject[1] - world lightning bolt renderer - owner: SurfaceWeatherVfxRig
            GameObject boltObject = new GameObject("LightningBolt");
            boltObject.transform.SetParent(transform, false);

            _boltRenderer = boltObject.AddComponent<LineRenderer>();
            _boltRenderer.alignment = LineAlignment.View;
            _boltRenderer.textureMode = LineTextureMode.Stretch;
            _boltRenderer.shadowCastingMode = ShadowCastingMode.Off;
            _boltRenderer.receiveShadows = false;
            _boltRenderer.useWorldSpace = true;
            _boltRenderer.numCapVertices = 2;
            _boltRenderer.positionCount = BoltPointCount;
            _boltRenderer.startColor = new Color(0.82f, 0.9f, 1f, 0.92f);
            _boltRenderer.endColor = new Color(0.76f, 0.84f, 1f, 0.28f);
            _boltRenderer.sharedMaterial = ResolveBoltMaterial();
            _boltRenderer.enabled = false;
        }

        private void BuildLightningLight()
        {
            // COLD ALLOC: GameObject[1] - point light for lightning strike flash - owner: SurfaceWeatherVfxRig
            GameObject lightObject = new GameObject("LightningLight");
            lightObject.transform.SetParent(transform, false);
            _lightningLight = lightObject.AddComponent<Light>();
            _lightningLight.type = LightType.Point;
            _lightningLight.color = new Color(0.73f, 0.82f, 1f, 1f);
            _lightningLight.range = lightningLightRange;
            _lightningLight.intensity = 0f;
            _lightningLight.shadows = LightShadows.None;
            _lightningLight.enabled = false;
        }

        private Material ResolveBoltMaterial()
        {
            if (lightningBoltMaterial != null)
                return lightningBoltMaterial;

            if (!_loggedMissingBoltMaterial)
            {
                _loggedMissingBoltMaterial = true;
                Debug.LogError("[SurfaceWeatherVfxRig] Missing lightningBoltMaterial asset. Runtime material creation is forbidden for lightning bolt rendering.", this);
            }

            return null;
        }

        private void UpdateRainState(
            Vector3 followPosition,
            float surfaceY,
            Vector2 windDirection,
            float precipitationIntensity,
            float areaScale,
            float densityMultiplier,
            bool active)
        {
            const float RainPropertyEpsilon = 0.01f;

            if (_rainParticleSystem == null || _rainRoot == null)
                return;

            var rainEmission = _rainParticleSystem.emission;
            var rainVelocity = _rainParticleSystem.velocityOverLifetime;
            float clampedAreaScale = Mathf.Max(0.5f, areaScale);
            if (Mathf.Abs(_cachedRainAreaScale - clampedAreaScale) > RainPropertyEpsilon)
            {
                var shape = _rainParticleSystem.shape;
                Vector3 scale = rainVolumeSize;
                scale.x *= clampedAreaScale;
                scale.z *= clampedAreaScale;
                shape.scale = scale;
                _cachedRainAreaScale = clampedAreaScale;
            }

            if (!active || precipitationIntensity <= 0.025f)
            {
                if (_cachedRainEmissionRate != 0f)
                {
                    rainEmission.rateOverTime = 0f;
                    _cachedRainEmissionRate = 0f;
                }

                if (_rainParticleSystem.isPlaying)
                    _rainParticleSystem.Stop(true, ParticleSystemStopBehavior.StopEmitting);
                return;
            }

            float clampedIntensity = Mathf.Clamp01(precipitationIntensity);
            Vector2 normalizedWindDirection = windDirection;
            float windMagnitude = normalizedWindDirection.magnitude;
            if (windMagnitude > 0.0001f)
                normalizedWindDirection /= windMagnitude;
            else
                normalizedWindDirection = Vector2.zero;

            float windLeadDistance = ((rainVolumeSize.x + rainVolumeSize.z) * 0.125f) * clampedAreaScale * clampedIntensity;
            Vector3 emitterPosition = followPosition;
            emitterPosition.x -= normalizedWindDirection.x * windLeadDistance;
            emitterPosition.z -= normalizedWindDirection.y * windLeadDistance;
            emitterPosition.y = Mathf.Max(followPosition.y, surfaceY) + RainEmitterHeight;
            _rainRoot.position = emitterPosition;

            float emissionRate = Mathf.Lerp(12f, maxRainEmissionRate * Mathf.Max(0.25f, densityMultiplier), clampedIntensity * clampedIntensity);
            if (Mathf.Abs(_cachedRainEmissionRate - emissionRate) > RainPropertyEpsilon)
            {
                rainEmission.rateOverTime = emissionRate;
                _cachedRainEmissionRate = emissionRate;
            }

            Vector3 windVelocity = new Vector3(windDirection.x, 0f, windDirection.y) * rainWindVelocity * clampedIntensity;
            float verticalVelocity = -1.5f * clampedIntensity;
            if (Mathf.Abs(_cachedRainVelocityX - windVelocity.x) > RainPropertyEpsilon)
            {
                rainVelocity.x = new ParticleSystem.MinMaxCurve(windVelocity.x);
                _cachedRainVelocityX = windVelocity.x;
            }

            if (Mathf.Abs(_cachedRainVelocityY - verticalVelocity) > RainPropertyEpsilon)
            {
                rainVelocity.y = new ParticleSystem.MinMaxCurve(verticalVelocity);
                _cachedRainVelocityY = verticalVelocity;
            }

            if (Mathf.Abs(_cachedRainVelocityZ - windVelocity.z) > RainPropertyEpsilon)
            {
                rainVelocity.z = new ParticleSystem.MinMaxCurve(windVelocity.z);
                _cachedRainVelocityZ = windVelocity.z;
            }

            if (!_rainParticleSystem.isPlaying)
                _rainParticleSystem.Play(true);
        }

        private void UpdateSurfaceImpactState(
            Vector3 followPosition,
            float surfaceY,
            Vector2 windDirection,
            float precipitationIntensity,
            float radiusScale,
            float densityMultiplier,
            bool active)
        {
            const float SurfaceImpactEpsilon = 0.01f;

            if (_surfaceImpactParticleSystem == null || _surfaceImpactRoot == null)
                return;

            var surfaceImpactEmission = _surfaceImpactParticleSystem.emission;
            var surfaceImpactVelocity = _surfaceImpactParticleSystem.velocityOverLifetime;
            float clampedRadiusScale = Mathf.Max(0.5f, radiusScale);
            float resolvedRadius = surfaceImpactRadius * clampedRadiusScale;
            Vector2 normalizedWindDirection = windDirection;
            float windMagnitude = normalizedWindDirection.magnitude;
            if (windMagnitude > 0.0001f)
                normalizedWindDirection /= windMagnitude;
            else
                normalizedWindDirection = Vector2.zero;

            float clampedIntensity = Mathf.Clamp01(precipitationIntensity);
            Vector3 surfacePosition = followPosition;
            float impactOffsetDistance = resolvedRadius * 0.12f * clampedIntensity;
            surfacePosition.x += normalizedWindDirection.x * impactOffsetDistance;
            surfacePosition.z += normalizedWindDirection.y * impactOffsetDistance;
            surfacePosition.y = surfaceY + SurfaceImpactHeightOffset;
            _surfaceImpactRoot.position = surfacePosition;
            _currentSurfaceImpactDensityMultiplier = Mathf.Max(0.25f, densityMultiplier);

            if (Mathf.Abs(_cachedSurfaceImpactRadiusScale - clampedRadiusScale) > SurfaceImpactEpsilon)
            {
                var shape = _surfaceImpactParticleSystem.shape;
                shape.scale = new Vector3(resolvedRadius * 2f, 0.05f, resolvedRadius * 2f);
                _cachedSurfaceImpactRadiusScale = clampedRadiusScale;
            }

            if (!active || precipitationIntensity <= 0.08f)
            {
                if (_cachedSurfaceImpactEmissionRate != 0f)
                {
                    surfaceImpactEmission.rateOverTime = 0f;
                    _cachedSurfaceImpactEmissionRate = 0f;
                }

                if (_surfaceImpactParticleSystem.isPlaying)
                    _surfaceImpactParticleSystem.Stop(true, ParticleSystemStopBehavior.StopEmitting);
                return;
            }

            float emissionRate = Mathf.Lerp(10f, maxSurfaceImpactEmissionRate * _currentSurfaceImpactDensityMultiplier, clampedIntensity * clampedIntensity);
            if (Mathf.Abs(_cachedSurfaceImpactEmissionRate - emissionRate) > SurfaceImpactEpsilon)
            {
                surfaceImpactEmission.rateOverTime = emissionRate;
                _cachedSurfaceImpactEmissionRate = emissionRate;
            }

            Vector3 windVelocity = new Vector3(windDirection.x, 0f, windDirection.y) * rainWindVelocity * clampedIntensity * 0.25f;
            float upwardVelocity = Mathf.Lerp(0.45f, 1.15f, clampedIntensity);
            if (Mathf.Abs(_cachedSurfaceImpactVelocityX - windVelocity.x) > SurfaceImpactEpsilon)
            {
                surfaceImpactVelocity.x = new ParticleSystem.MinMaxCurve(windVelocity.x);
                _cachedSurfaceImpactVelocityX = windVelocity.x;
            }

            if (Mathf.Abs(_cachedSurfaceImpactVelocityY - upwardVelocity) > SurfaceImpactEpsilon)
            {
                surfaceImpactVelocity.y = new ParticleSystem.MinMaxCurve(upwardVelocity);
                _cachedSurfaceImpactVelocityY = upwardVelocity;
            }

            if (Mathf.Abs(_cachedSurfaceImpactVelocityZ - windVelocity.z) > SurfaceImpactEpsilon)
            {
                surfaceImpactVelocity.z = new ParticleSystem.MinMaxCurve(windVelocity.z);
                _cachedSurfaceImpactVelocityZ = windVelocity.z;
            }

            if (!_surfaceImpactParticleSystem.isPlaying)
                _surfaceImpactParticleSystem.Play(true);
        }

        private void UpdateLightningState(float deltaTime)
        {
            if (_boltTimer <= 0f)
                return;

            _boltTimer -= deltaTime;
            if (_boltTimer <= 0f)
            {
                _boltTimer = 0f;
                _boltIntensity = 0f;
                if (_boltRenderer != null)
                    _boltRenderer.enabled = false;

                if (_lightningLight != null)
                {
                    _lightningLight.enabled = false;
                    _lightningLight.intensity = 0f;
                }

                return;
            }

            float fade = _boltTimer / BoltDurationSeconds;
            if (_lightningLight != null)
            {
                _lightningLight.enabled = true;
                _lightningLight.intensity = Mathf.Lerp(0f, 10f, _boltIntensity) * fade;
            }
        }
    }
}
